using System;

namespace Apollo
{
	public enum ApolloResult
	{
		Success,
		Error,
		NetworkException,
		Timeout,
		InvalidArgument,
		LengthError,
		Unknown,
		Empty,
		PlatformNotInstall = 10,
		PlatformNotSupportApi,
		UserCancel,
		UserDenied,
		LoginFailed,
		NoAccessToken,
		TokenInvalid,
		AccessTokenExpired = 16,
		RefreshTokenExpired,
		PayTokenExpired,
		NeedReset,
		NoPermission,
		CheckToken,
		NeedRealNameAuth,
		InitializeError = 50,
		MarketError,
		ItemInvalidate,
		Incomplete,
		NotYetConsume,
		TransactionIdNotExist,
		GooglePlayNotSupport,
		LbsNeedOpenLocation = 70,
		LbsLocateFail,
		WebviewClosed = 80,
		PluginEnd = 99,
		InnerError,
		NotInitialized,
		NoConnection,
		ConnectFailed,
		InvalidServiceId,
		IsConnecting,
		GcpError = 120,
		PeerCloseConnection,
		PeerStopSession,
		PkgNotCompleted,
		SendFailed,
		StayInQueue,
		SvrIsFull,
		TokenSvrError,
		AuthFailed,
		HttpOtherError = 270,
		HttpBadVersion,
		HttpBadURL,
		HttpBadMethod,
		HttpReqToLong,
		HttpBadHeader,
		Others = 10000
	}
}
