using System;

namespace CSProtocol
{
	public enum BOOTFRAP_TYPEDEF
	{
		BOOTFRAP_TYPE_NULL,
		BOOTFRAP_TYPE_CC,
		BOOTFRAP_TYPE_CS,
		BOOTFRAP_TYPE_ACNTSTATECHG,
		BOOTFRAP_TYPE_ASSISTSTATECHG,
		BOOTFRAP_TYPE_AISTATECHG,
		BOOTFRAP_TYPE_GAMEOVERNTF,
		BOOTFRAP_TYPE_PAUSE,
		BOOTFRAP_TYPE_MAX
	}
}
