using System;

namespace CSProtocol
{
	public enum COM_ACNT_CLIENT_BITS_TYPE
	{
		COM_ACNT_CLIENT_BITS_TYPE_KILL_SOLDIER,
		COM_ACNT_CLIENT_BITS_TYPE_DESTORY_ARROWTOWER,
		COM_ACNT_CLIENT_BITS_TYPE_DESTORY_BASETOWER,
		COM_ACNT_CLIENT_BITS_TYPE_DESTORY_MONSTERHOME,
		COM_ACNT_CLIENT_BITS_TYPE_KILL_LITTLEDRAGON,
		COM_ACNT_CLIENT_BITS_TYPE_LEARN_TALENT,
		COM_ACNT_CLIENT_BITS_TYPE_UPGRADE_EQUIP,
		COM_ACNT_CLIENT_BITS_TYPE_GET_HERO,
		COM_ACNT_CLIENT_BITS_TYPE_KILL_HERO,
		COM_ACNT_CLIENT_BITS_TYPE_COMBAT_3V3_ENTER,
		COM_ACNT_CLIENT_BITS_TYPE_COMBAT_3V3_LOADOK,
		COM_ACNT_CLIENT_BITS_TYPE_SINGLE_3V3_LOADOK,
		COM_ACNT_CLIENT_BITS_TYPE_1_1_1_ENTER,
		COM_ACNT_CLIENT_BITS_TYPE_1_1_1_LOADOK,
		COM_ACNT_CLIENT_BITS_TYPE_SYMBOL_ENTER,
		COM_ACNT_CLIENT_BITS_TYPE_ARENA_ENTER,
		COM_ACNT_CLIENT_BITS_TYPE_BURNING_ENTER,
		COM_ACNT_CLIENT_BITS_TYPE_OLDPLAYERGUILDED,
		COM_ACNT_CLIENT_BITS_TYPE_MAX
	}
}
