using System;

namespace CSProtocol
{
	public enum COM_APOLLO_PAY_TYPE
	{
		COM_APOLLO_PAY_PAYSHOPBUY = 1,
		COM_APOLLO_PAY_PAYITEMBUY,
		COM_APOLLO_PAY_PAYCOINBUY,
		COM_APOLLO_PAY_PAYMANUALREF,
		COM_APOLLO_PAY_PAYHEROBUY,
		COM_APOLLO_PAY_PAYGAMESWEEP,
		COM_APOLLO_PAY_PAYGUILDCRT,
		COM_APOLLO_PAY_PAYSKINBUY,
		COM_APOLLO_PAY_CLRCD,
		COM_APOLLO_PAY_PAYGUILDDONATE,
		COM_APOLLO_PAY_SPECSALE,
		COM_APOLLO_PAY_MONTHFILLIN,
		COM_APOLLO_PAY_DIRECTBUYITEM,
		COM_APOLLO_PAY_DELETE,
		COM_APOLLO_PAY_PVE_REVIVE,
		COM_APOLLO_PAY_PAYGUILDUPD,
		COM_APOLLO_PAY_PAYTALENTBUY,
		COM_APOLLO_PAY_LUCKYDRAW,
		COM_APOLLO_PAY_CHAT,
		COM_APOLLO_PAY_SALERECMD_BUY,
		COM_APOLLO_PAY_RANDDRAW,
		COM_APOLLO_PAY_PRESENTHERO,
		COM_APOLLO_PAY_PRESENTSKIN,
		COM_APOLLO_PAY_MATCHTICKET,
		COM_APOLLO_PAY_IDIPDELETE,
		COM_APOLLO_PAY_ASKFORREQ,
		COM_APOLLO_PAY_MAX
	}
}
