using System;

namespace CSProtocol
{
	public enum COM_SHOP_DRAW_TYPE
	{
		COM_SHOPDRAW_COIN,
		COM_SHOPDRAW_HERO,
		COM_SHOPDRAW_SKIN,
		COM_SHOPDRAW_SYMBOLCOMMON,
		COM_SHOPDRAW_SYMBOLSENIOR,
		COM_SHOPDRAW_MAX
	}
}
