using System;

namespace CSProtocol
{
	public enum COM_ROOMCHGTYPE
	{
		COM_ROOMCHG_PLAYERADD,
		COM_ROOMCHG_PLAYERLEAVE,
		COM_ROOMCHG_SELFBEKICK,
		COM_ROOMCHG_STATECHG,
		COM_ROOMCHG_MASTERCHG,
		COM_ROOMCHG_CHGMEMBERPOS
	}
}
