using System;

namespace CSProtocol
{
	public enum COM_MAILACCESSMONEY_TYPE
	{
		COM_MAILACCESSMONEY_COIN = 1,
		COM_MAILACCESSMONEY_COUPONS,
		COM_MAILACCESSMONEY_RACEDAIBI,
		COM_MAILACCESSMONEY_BURNINGDAIBI,
		COM_MAILACCESSMONEY_GUILDSHOPDAIBI,
		COM_MAILACCESSMONEY_SYMBOLCOIN,
		COM_MAILACCESSMONEY_DIAMOND
	}
}
