using System;

namespace CSProtocol
{
	public enum COM_HERO_MASK_BITS
	{
		COM_HERO_MASK_BITS_PAKAGE = 1,
		COM_HERO_MASK_BITS_PVP,
		COM_HERO_MASK_BITS_FREE = 4,
		COM_HERO_MASK_BITS_EXPERIENCE = 8
	}
}
