using System;

namespace CSProtocol
{
	public enum COM_REFUSE_TYPE
	{
		COM_REFUSE_TYPE_DONOTE_AND_REC,
		COM_REFUSE_TYPE_ADDFRIEND,
		COM_REFUSE_TYPE_LBSSHARE,
		COM_REFUSE_TYPE_MASTERREQ,
		COM_REFUSE_TYPE_RESERVE_MSG
	}
}
