using System;

namespace CSProtocol
{
	public enum COM_ACNT_NEWBIE_TYPE
	{
		COM_ACNT_NEWBIE_TYPE_NULL,
		COM_ACNT_NEWBIE_TYPE_NEWBIE,
		COM_ACNT_NEWBIE_TYPE_OLDBIRD,
		COM_ACNT_NEWBIE_TYPE_MASTER,
		COM_ACNT_NEWBIE_TYPE_MAX
	}
}
