using System;

namespace CSProtocol
{
	public enum COM_ACNT_GAME_STATE
	{
		COM_ACNT_GAME_STATE_IDLE,
		COM_ACNT_GAME_STATE_SINGLEGAME,
		COM_ACNT_GAME_STATE_MULTIGAME,
		COM_ACNT_GAME_STATE_TEAM,
		COM_ACNT_GAME_STATE_WAITMULTIGAME
	}
}
