using System;

namespace CSProtocol
{
	public enum COM_ACNT_BANTIME_TYPE
	{
		COM_ACNT_BANTIME_LOGINLIMIT,
		COM_ACNT_BANTIME_COUPONSFROZEN,
		COM_ACNT_BANTIME_COINFROZEN,
		COM_ACNT_BANTIME_PVPCOINFROZEN,
		COM_ACNT_BANTIME_ARENACOINFROZEN,
		COM_ACNT_BANTIME_BURNINGCOINFROZEN,
		COM_ACNT_BANTIME_GUILDCOINFROZEN,
		COM_ACNT_BANTIME_SKINCOINFROZEN,
		COM_ACNT_BANTIME_DENYCHAT,
		COM_ACNT_BANTIME_BANPLAYPVP,
		COM_ACNT_BANTIME_BANPLAYPVE,
		COM_ACNT_BANTIME_BANPLAYZHONGSHILIAN,
		COM_ACNT_BANTIME_BANPLAYBURNING,
		COM_ACNT_BANTIME_BANPLAYMENGJING,
		COM_ACNT_BANTIME_BANPLAYAREAN,
		COM_ACNT_BANTIME_SYMBOLCOINFROZEN,
		COM_ACNT_BANTIME_DIAMONDFROZEN,
		COM_ACNT_BANTIME_BANTRANK,
		COM_ACNT_BANTIME_ZEROPROFIT,
		COM_ACNT_BANTIME_SCOREFROZEN,
		COM_ACNT_BANTIME_ADDFRIEND,
		COM_ACNT_BANTIME_LADDER,
		COM_ACNT_BANTIME_FIVEVSFIVE,
		COM_ACNT_BANTIME_THREEVSTHREE,
		COM_ACNT_BANTIME_ONEVSONE,
		COM_ACNT_BANTIME_ENTERTAINMENT,
		COM_ACNT_BANTIME_MAX
	}
}
