using System;

namespace CSProtocol
{
	public enum COM_APPOINT_POSITION_TRANS_TYPE
	{
		COM_APPOINT_POSITION_TRANS_TYPE_APPOINT,
		COM_APPOINT_POSITION_TRANS_TYPE_DEAL_SELF_RECOMMEND,
		COM_APPOINT_POSITION_TRANS_TYPE_SELF_RECOMMEND_TIMEOUT,
		COM_APPOINT_POSITION_TRANS_TYPE_IMPEACH_CHAIRMAN,
		COM_APPOINT_POSITION_TRANS_TYPE_IDIPCHG_CHAIRMAN
	}
}
