using System;

namespace CSProtocol
{
	public enum COM_IDIP_ACNTATTR_TYPE
	{
		COM_IDIP_ACNTATTR_LEVEL,
		COM_IDIP_ACNTATTR_PVPLEVEL,
		COM_IDIP_ACNTATTR_EXP,
		COM_IDIP_ACNTATTR_PVPEXP,
		COM_IDIP_ACNTATTR_COIN,
		COM_IDIP_ACNTATTR_ACTIONPT,
		COM_IDIP_ACNTATTR_PVPCOIN,
		COM_IDIP_ACNTATTR_ARENACOIN,
		COM_IDIP_ACNTATTR_BURNINGCOIN,
		COM_IDIP_ACNTATTR_SKINCOIN,
		COM_IDIP_ACNTATTR_SYMBOLCOIN,
		COM_IDIP_ACNTATTR_DIAMOND,
		COM_IDIP_ACNTATTR_COPUS,
		COM_IDIP_ACNTATTR_VIPSOCRE,
		COM_IDIP_ACNTATTR_DIAMONDLUCKYPOINT,
		COM_IDIP_ACNTATTR_COUPONSLUCKYPOINT,
		COM_IDIP_ACNTATTR_PASSWORD,
		COM_IDIP_ACNTATTR_MAX
	}
}
