using System;

namespace CSProtocol
{
	public enum COM_BATTLE_MAP_TYPE
	{
		COM_BATTLE_MAP_TYPE_VERSUS = 1,
		COM_BATTLE_MAP_TYPE_COUNTERPART,
		COM_BATTLE_MAP_TYPE_RANK,
		COM_BATTLE_MAP_TYPE_ENTERTAINMENT,
		COM_BATTLE_MAP_TYPE_REWARDMATCH,
		COM_BATTLE_MAP_TYPE_GUILDMATCH,
		COM_BATTLE_MAP_TYPE_NUM
	}
}
