using System;

namespace CSProtocol
{
	public enum COM_APOLLO_TRANK_USERBUFFER_EXTRA_TYPE
	{
		COM_APOLLO_TRANK_USERBUFFER_EXTRA_TYPE_NULL,
		COM_APOLLO_TRANK_USERBUFFER_EXTRA_TYPE_SEARCH_GUILD,
		COM_APOLLO_TRANK_USERBUFFER_EXTRA_TYPE_TOPN
	}
}
