using System;

namespace CSProtocol
{
	public enum COM_USER_PRIVACY_MASK
	{
		COM_USER_PRIVACY_MASK_FIGHT_HISTORY,
		COM_USER_PRIVACY_MASK_VIDEO,
		COM_USER_PRIVACY_MASK_VIP_LEVEL,
		COM_USER_PRIVACY_MASK_FRIEND_CARD,
		COM_USER_PRIVACY_MASK_MAX
	}
}
