using System;

namespace CSProtocol
{
	public enum COM_ANTI_CHEAT_LOGIC_TYPE
	{
		COM_ANTI_CHEAT_LOGIC_TYPE_NULL,
		COM_ANTI_CHEAT_LOGIC_TYPE_GAMETIME,
		COM_ANTI_CHEAT_LOGIC_TYPE_HURT,
		COM_ANTI_CHEAT_LOGIC_TYPE_FORMULA,
		COM_ANTI_CHEAT_LOGIC_TYPE_MOVE_SPEED,
		COM_ANTI_CHEAT_LOGIC_TYPE_SKILL_INFO,
		COM_ANTI_CHEAT_LOGIC_TYPE_TALENT_INFO,
		COM_ANTI_CHEAT_LOGIC_TYPE_INGAME,
		COM_ANTI_CHEAT_LOGIC_TYPE_SOULEXP,
		COM_ANTI_CHEAT_LOGIC_TYPE_SOLDIERCNT,
		COM_ANTI_CHEAT_LOGIC_TYPE_TOWER_ATTACK_DISTANCE,
		COM_ANTI_CHEAT_LOGIC_TYPE_POWER,
		COM_ANTI_CHEAT_LOGIC_TYPE_MAX
	}
}
