using System;

namespace CSProtocol
{
	public enum COM_PLAYER_GUILD_STATE
	{
		COM_PLAYER_GUILD_STATE_NULL,
		COM_PLAYER_GUILD_STATE_PREPARE_CREATE,
		COM_PLAYER_GUILD_STATE_PREPARE_JOIN,
		COM_PLAYER_GUILD_STATE_CHAIRMAN,
		COM_PLAYER_GUILD_STATE_VICE_CHAIRMAN,
		COM_PLAYER_GUILD_STATE_ELDER,
		COM_PLAYER_GUILD_STATE_MEMBER,
		COM_PLAYER_GUILD_STATE_WAIT_RESULT
	}
}
