using System;

namespace CSProtocol
{
	public enum COM_NORMAL_MMR_GAME_TYPE
	{
		COM_NORMAL_MMR_GAME_TYPE_NULL,
		COM_NORMAL_MMR_GAME_TYPE_1V1,
		COM_NORMAL_MMR_GAME_TYPE_3V3,
		COM_NORMAL_MMR_GAME_TYPE_5V5,
		COM_NORMAL_MMR_GAME_TYPE_CHAOS,
		COM_NORMAL_MMR_GAME_TYPE_ENTERTAINMENT,
		COM_NORMAL_MMR_GAME_TYPE_GUILDMATCH,
		COM_NORMAL_MMR_GAME_TYPE_MAX
	}
}
