using System;

namespace CSProtocol
{
	public enum COM_REWARDS_TYPE
	{
		COM_REWARDS_TYPE_COIN,
		COM_REWARDS_TYPE_ITEM,
		COM_REWARDS_TYPE_EXP,
		COM_REWARDS_TYPE_COUPONS,
		COM_REWARDS_TYPE_EQUIP,
		COM_REWARDS_TYPE_HERO,
		COM_REWARDS_TYPE_SYMBOL,
		COM_REWARDS_TYPE_BURNING_COIN,
		COM_REWARDS_TYPE_ARENA_COIN,
		COM_REWARDS_TYPE_AP,
		COM_REWARDS_TYPE_SKIN,
		COM_REWARDS_TYPE_HONOUR,
		COM_REWARDS_TYPE_HEROPOOLEXP,
		COM_REWARDS_TYPE_SKINCOIN,
		COM_REWARDS_TYPE_SYMBOLCOIN,
		COM_REWARDS_TYPE_PVPEXP,
		COM_REWARDS_TYPE_DIAMOND,
		COM_REWARDS_TYPE_HUOYUEDU,
		COM_REWARDS_TYPE_MATCH_POINT_PERSON,
		COM_REWARDS_TYPE_MATCH_POINT_GUILD,
		COM_REWARDS_TYPE_HEADIMAGE,
		COM_REWARDS_TYPE_ACHIEVE,
		COM_REWARDS_TYPE_MASTERPOINT,
		COM_REWARDS_TYPE_MAX
	}
}
