using System;

namespace CSProtocol
{
	public enum COM_REWARD_MULTIPLE_FROM_TYPE
	{
		COM_REWARD_MULTIPLE_FROM_NULL,
		COM_REWARD_MULTIPLE_FROM_WEAL,
		COM_REWARD_MULTIPLE_FROM_QQVIP,
		COM_REWARD_MULTIPLE_FROM_PROP,
		COM_REWARD_MULTIPLE_FROM_PVPDAILY,
		COM_REWARD_MULTIPLE_FROM_WXGAMECENTERLOGIN,
		COM_REWARD_MULTIPLE_FROM_GUILD,
		COM_REWARD_MULTIPLE_FROM_FIRSTWIN,
		COM_REWARD_MULTIPLE_FROM_GAMEVIP,
		COM_REWARD_MULTIPLE_FROM_QQGAMECENTERLOGIN,
		COM_REWARD_MULTIPLE_FROM_IOSVISITORLOGIN,
		COM_REWARD_MULTIPLE_FROM_HANGUP,
		COM_REWARD_MULTIPLE_FROM_CREDIT,
		COM_REWARD_MULTIPLE_FROM_RECRUITMENT,
		COM_REWARD_MULTIPLE_FROM_MASTER,
		COM_REWARD_MULTIPLE_FROM_MAX
	}
}
