using System;

namespace CSProtocol
{
	public enum COM_ITEM_FROM_TYPE
	{
		COM_ITEM_FROM_NULL,
		COM_ITEM_FROM_BUY,
		COM_ITEM_FROM_WEAL,
		COM_ITEM_FROM_LUCKYDRAW,
		COM_ITEM_FROM_EXCHANGE,
		COM_ITEM_FROM_EXPCARD,
		COM_ITEM_FROM_GIFT,
		COM_ITEM_FROM_LADDER
	}
}
