using System;

namespace CSProtocol
{
	public enum COM_FRIEND_TYPE
	{
		COM_FRIEND_TYPE_GAME = 1,
		COM_FRIEND_TYPE_SNS,
		COM_FRIEND_TYPE_LBS,
		COM_FRIEND_TYPE_GUILD,
		COM_FRIEND_TYPE_STUDENT,
		COM_FRIEND_TYPE_MASTER
	}
}
