using System;

namespace CSProtocol
{
	public enum COM_ACNT_OLD_TYPE
	{
		COM_ACNT_OLD_TYPE_TBD,
		COM_ACNT_OLD_TYPE_LEVEL_LIMIT,
		COM_ACNT_OLD_TYPE_TO_BE_SELECTED,
		COM_ACNT_OLD_TYPE_SELECT_YES,
		COM_ACNT_OLD_TYPE_SELECT_NO,
		COM_ACNT_OLD_TYPE_OLD_VERSION
	}
}
