using System;

namespace CSProtocol
{
	public enum CS_ADDHERO_ERRCODE
	{
		CS_ADDHERO_ACNTOWNED = 1,
		CS_ADDHERO_BUYFAIL,
		CS_ADDHERO_HEROINVALID,
		CS_ADDHERO_TIME_ERROR,
		CS_ADDHERO_PROMOTION,
		CS_ADDHERO_COINLIMIT,
		CS_ADDHERO_PKGFULL,
		CS_ADDHERO_INITHERO,
		CS_ADDHERO_OTHER
	}
}
