using System;

namespace CSProtocol
{
	public enum CS_COINDRAW_ERRCODE
	{
		CS_COINDRAW_ERR_LIMIT_RESOURCE = 1,
		CS_COINDRAW_ERR_PACKAGEFULL,
		CS_COINDRAW_ERR_MAXSTEP,
		CS_COINDRAW_ERR_OTHERS
	}
}
