using System;

namespace CSProtocol
{
	public enum CS_FRAPBOOT_ACNTSTATECHG
	{
		CS_FRAPBOOT_ACNTSTATE_NULL,
		CS_FRAPBOOT_ACNTSTATE_DISCONN,
		CS_FRAPBOOT_ACNTSTATE_RECONN,
		CS_FRAPBOOT_ACNTSTATE_RUNAWAY
	}
}
