using System;

namespace CSProtocol
{
	public enum CS_GAMEVIP_NTF_TYPE
	{
		CS_GAMEVIP_NTF_NORMAL,
		CS_GAMEVIP_NTF_OPEN,
		CS_GAMEVIP_NTF_LOSE,
		CS_GAMEVIP_NTF_REGAIN,
		CS_GAMEVIP_NTF_UPGRADE,
		CS_GAMEVIP_NTF_DEGRADE
	}
}
