using System;

namespace CSProtocol
{
	public enum CS_HEROINFO_UPD_TYPE
	{
		CS_HEROINFO_UPD_LEVEL = 1,
		CS_HEROINFO_UPD_EXP,
		CS_HEROINFO_UPD_STAR,
		CS_HEROINFO_UPD_QUALITY,
		CS_HEROINFO_UPD_SUBQUALITY,
		CS_HEROINFO_UPD_UNLOCKSKILLSLOT,
		CS_HEROINFO_UPD_PROFICIENCY,
		CS_HEROINFO_UPD_MASKBITS,
		CS_HEROINFO_UPD_LIMITTIME,
		CS_HEROINFO_UPD_MASTERGAMECNT
	}
}
