using System;

namespace CSProtocol
{
	public enum CS_LICENSEGET_ERRCODE
	{
		CS_LICENSEGET_ERR_SYS = 1,
		CS_LICENSEGET_ERR_ID,
		CS_LICENSEGET_ERR_ALREADY,
		CS_LICENSEGET_ERR_CONDLACK,
		CS_LICENSEGET_ERR_FULL
	}
}
