using System;

namespace CSProtocol
{
	public enum CS_PRESENTHEROSKIN_ERRCODE
	{
		CS_PRESENTHEROSKIN_SYS = 1,
		CS_PRESENTHEROSKIN_LOCK,
		CS_PRESENTHEROSKIN_NOALLOW,
		CS_PRESENTHEROSKIN_UNFRIEND,
		CS_PRESENTHEROSKIN_COINLIMIT,
		CS_PRESENTHEROSKIN_MAILFAIL,
		CS_PRESENTHEROSKIN_PROMOTION,
		CS_PRESENTHEROSKIN_HEROINVALID,
		CS_PRESENTHEROSKIN_SKININVALID,
		CS_PRESENTHEROSKIN_LIMITMAX,
		CS_PRESENTHEROSKIN_FRIENDTIME,
		CS_PRESENTHEROSKIN_INVALID_PLAT,
		CS_PRESENTHEROSKIN_SELF,
		CS_PRESENTHEROSKIN_PSWDCHK,
		CS_PRESENTHEROSKIN_MSGDIRTY,
		CS_PRESENTHEROSKIN_HASHERO,
		CS_PRESENTHEROSKIN_HASSKIN
	}
}
