using System;

namespace CSProtocol
{
	public enum CS_RECRUITMENTWARD_ERR
	{
		CS_RECRUITMENTWARD_SUCC,
		CS_RECRUITMENTWARD_NOTINTABLE,
		CS_RECRUITMENTWARD_LEVEL_NOTENOUGH,
		CS_RECRUITMENTWARD_NOTRECRUITMENT,
		CS_RECRUITMENTWARD_GETED,
		CS_RECRUITMENTWARD_OTHER,
		CS_RECRUITMENTWARD_SUPER
	}
}
