using System;

namespace CSProtocol
{
	public enum CS_SYMBOLOPT_ERRCODE
	{
		CS_SYMBOLOPT_STATEERR = 1,
		CS_SYMBOLOPT_IDINVALID,
		CS_SYMBOLOPT_CONSUMELIMIT,
		CS_SYMBOLOPT_MAKELIMIT,
		CS_SYMBOLOPT_MAKEERR,
		CS_SYMBOLOPT_BELONGHERO
	}
}
