using System;

namespace CSProtocol
{
	public enum CS_SYMBOLRCMD_WEAR_ERR
	{
		CS_SYMBOLRCMD_WEAR_STATE = 1,
		CS_SYMBOLRCMD_WEAR_UNSEL,
		CS_SYMBOLRCMD_WEAR_PAGEIDX,
		CS_SYMBOLRCMD_WEAR_INVALID
	}
}
