using System;

namespace CSProtocol
{
	public enum CS_TALENTBUY_ERRCODE
	{
		CS_TALENTBUY_DATAERR = 1,
		CS_TALENTBUY_CONSUMELIMIT,
		CS_TALENTBUY_ORDERERR,
		CS_TALENTBUY_DUPBUY,
		CS_TALENTBUY_FINISH
	}
}
