using System;

namespace CSProtocol
{
	public enum RECONN_RELAY_STATE_TYPE
	{
		RECONN_RELAY_STATE_BAN = 1,
		RECONN_RELAY_STATE_PICK,
		RECONN_RELAY_STATE_ADJUST,
		RECONN_RELAY_STATE_LOADING,
		RECONN_RELAY_STATE_GAMEING,
		RECONN_RELAY_STATE_GAMEOVER
	}
}
