using System;

namespace CSProtocol
{
	public enum SC_FRAME_CMD_ID_DEF
	{

		SC_FRAME_CMD_INVALID,
		SC_FRAME_CMD_PLAYERRUNAWAY = 192,
		SC_FRAME_CMD_PLAYERDISCONNECT,
		SC_FRAME_CMD_PLAYERRECONNECT,
		SC_FRAME_CMD_ASSISTSTATECHG,
		SC_FRAME_CMD_CHGAUTOAI,
		SC_FRAME_CMD_SVRNTF_GAMEOVER,
		SC_FRAME_CMD_PAUSE_RESUME_GAME
	}
}
