using System;

namespace Assets.Scripts.GameLogic
{
	public enum ENUM_EQUIP_ACTIVESKILL_STATUS
	{
		ENM_EQUIP_ACTIVESKILL_STATUS_WHITHOUTACTIVESKILL,
		ENM_EQUIP_ACTIVESKILL_STATUS_NOTSHOW,
		ENM_EQUIP_ACTIVESKILL_STATUS_ISSHOWING,
		ENM_EQUIP_ACTIVESKILL_STATUS_WHITHOUTACTIVESKILL_REMOVECURSKILL
	}
}
