using System;

namespace Assets.Scripts.GameLogic
{
	public enum SKILL_USE_FROM_TYPE
	{
		SKILL_USE_FROM_TYPE_SKILL,
		SKILL_USE_FROM_TYPE_EQUIP,
		SKILL_USE_FROM_TYPE_AREATRIGGER,
		SKILL_USE_FROM_TYPE_PASSIVESKILL,
		SKILL_USE_FROM_TYPE_MAX
	}
}
