using System;

namespace Assets.Scripts.GameSystem
{
	public enum enBattleFormWidget
	{
		None = -1,
		Reserve,
		TopRightUI,
		Container_InOutEquipShop,
		Container_MinimapPointer_Hero,
		Container_MinimapPointer_Alies,
		Container_MinimapPointer_Enemy,
		Minimap,
		Button_Signal_1 = 12,
		Button_Signal_2,
		Button_Signal_3,
		Button_Signal_4,
		Text_Skill_1_CD,
		Text_Skill_2_CD,
		Text_Skill_3_CD,
		Text_Skill_4_CD,
		Panel_EnemySoliderHud,
		Panel_EnemyHeroHud,
		Panel_SelfSoliderHud,
		Panel_SelfHeroHud,
		Container_TextHud,
		SkillJoystick,
		Text_Skill_5_CD = 27,
		Container_MinimapPointer_Organ,
		CancelSkill = 31,
		FpsAndLag,
		Container_MinimapPointer_Signal,
		MiniMapEffectRoot,
		WifiIcon,
		WifiPing,
		WifiInfo,
		JoyStick,
		Button_Pause,
		Button_Resume,
		Input_Mask,
		WifiTimer = 44,
		Panel_Equip,
		Text_GoldCoinInBattle,
		Recommend_Equip_0,
		Recommend_Equip_1,
		Panel_Surrender,
		Effect_QuicklyBuy_0,
		Effect_QuicklyBuy_1,
		Effect_QuicklyBuy_Get_0,
		Effect_QuicklyBuy_Get_1,
		Button_Voice,
		Effect_QuicklyBuy_Type2_0,
		Effect_QuicklyBuy_Type2_1,
		Button_EquipShop = 58,
		Panel_QuicklyBuyEquip,
		Container_BigMapPointer_Dragon,
		Container_BigMapPointer_Organ,
		Container_BigMapPointer_Alies,
		Container_BigMapPointer_Hero,
		Container_BigMapPointer_Enemy,
		Container_BigMapPointer_Signal,
		BigMapEffectRoot,
		Bigmap,
		MenuBtn = 69,
		SkillButton4FixedPosition,
		Button_OpenBigMap,
		Panel_AllHeroInfo,
		Joystick_Camera,
		TouchPad_Camera,
		ReplayKit,
		SkillJoystick_SelectTarget,
		Text_Skill_Ornament_CD = 78,
		Text_Skill_1_Bean,
		Text_Skill_2_Bean,
		Text_Skill_3_Bean,
		Text_Skill_4_Bean,
		Text_Skill_5_Bean,
		Text_Skill_6_Bean,
		Text_Skill_7_Bean,
		LastHitBtn
	}
}
