using System;

namespace Assets.Scripts.GameSystem
{
	public enum enNewbieAchieve
	{
		COM_ACNT_CLIENT_BITS_TYPE_KILL_SOLDIER,
		COM_ACNT_CLIENT_BITS_TYPE_DESTORY_ARROWTOWER,
		COM_ACNT_CLIENT_BITS_TYPE_DESTORY_BASETOWER,
		COM_ACNT_CLIENT_BITS_TYPE_DESTORY_MONSTERHOME,
		COM_ACNT_CLIENT_BITS_TYPE_KILL_LITTLEDRAGON,
		COM_ACNT_CLIENT_BITS_TYPE_LEARN_TALENT,
		COM_ACNT_CLIENT_BITS_TYPE_UPGRADE_EQUIP,
		COM_ACNT_CLIENT_BITS_TYPE_GET_HERO,
		COM_ACNT_CLIENT_BITS_TYPE_KILL_HERO,
		COM_ACNT_CLIENT_BITS_TYPE_COMBAT_3V3_ENTER,
		COM_ACNT_CLIENT_BITS_TYPE_COMBAT_3V3_LOADOK,
		COM_ACNT_CLIENT_BITS_TYPE_SINGLE_3V3_LOADOK,
		COM_ACNT_CLIENT_BITS_TYPE_1_1_1_ENTER,
		COM_ACNT_CLIENT_BITS_TYPE_1_1_1_LOADOK,
		COM_ACNT_CLIENT_BITS_TYPE_SYMBOL_ENTER,
		COM_ACNT_CLIENT_BITS_TYPE_ARENA_ENTER,
		COM_ACNT_CLIENT_BITS_TYPE_BURNING_ENTER,
		COM_ACNT_CLIENT_BITS_TYPE_OLDPLAYERGUILDED,
		Androiod_Diamond_0 = 20,
		Androiod_Diamond_1,
		Androiod_Diamond_2,
		Androiod_Diamond_3,
		Androiod_Diamond_4,
		Androiod_Diamond_5,
		Androiod_Diamond_6,
		Androiod_Diamond_7,
		Androiod_Diamond_8,
		Androiod_Diamond_9,
		Androiod_Diamond_10,
		Androiod_Diamond_11,
		Androiod_Diamond_12,
		Androiod_Diamond_13,
		Androiod_Diamond_14,
		Androiod_Diamond_15,
		IOS_Diamond_0 = 40,
		IOS_Diamond_1,
		IOS_Diamond_2,
		IOS_Diamond_3,
		IOS_Diamond_4,
		IOS_Diamond_5,
		IOS_Diamond_6,
		IOS_Diamond_7,
		IOS_Diamond_8,
		IOS_Diamond_9,
		IOS_Diamond_10,
		IOS_Diamond_11,
		IOS_Diamond_12,
		IOS_Diamond_13,
		IOS_Diamond_14,
		IOS_Diamond_15,
		clickEnterTrain55Yes = 61,
		clickEnterTrain55No,
		clickEnterTain55YesAndComplete,
		cameraMoveGuide1,
		cameraMoveGuide2,
		cameraMoveGuide3,
		OldPlayerGrow = 72,
		OldPlayerSelectMode = 75,
		BigMapSignGuideFirstTime,
		BigMapSignGuideSecondTime,
		SelectLockTargetMode = 81,
		SelectFreeTargetMode = 79,
		GuideEnterHall = 84,
		MapSignGuide = 94,
		CompleteLunPan = 101,
		CompleteLunPanInV8AndLater = 118,
		INVALID
	}
}
