using System;

namespace behaviac
{
	public static class bt_WrapperAI_Monster_BTMonsterBaozou
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("WrapperAI/Monster/BTMonsterBaozou");
			bt.AddPar("uint", "p_targetID", "0", string.Empty);
			bt.AddPar("int", "p_srchRange", "0", string.Empty);
			bt.AddPar("uint", "p_selfID", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_targetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("int", "p_randomIndex", "0", string.Empty);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			bt.AddChild(sequence);
			Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node4 assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node4();
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node.SetId(4);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node98 assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node2 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node98();
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node2.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node2.SetId(98);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node2);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node2.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node48 assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node3 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node48();
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node3.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node3.SetId(48);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node3);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node3.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node11 assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node4 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node11();
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node4.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node4.SetId(11);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node4);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node4.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node14 decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node14();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node.SetId(14);
			sequence.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node);
			SelectorLoop selectorLoop = new SelectorLoop();
			selectorLoop.SetClassNameString("SelectorLoop");
			selectorLoop.SetId(1);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node.AddChild(selectorLoop);
			WithPrecondition withPrecondition = new WithPrecondition();
			withPrecondition.SetClassNameString("WithPrecondition");
			withPrecondition.SetId(60);
			selectorLoop.AddChild(withPrecondition);
			Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node61 condition_bt_WrapperAI_Monster_BTMonsterBaozou_node = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node61();
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node.SetId(61);
			withPrecondition.AddChild(condition_bt_WrapperAI_Monster_BTMonsterBaozou_node);
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterBaozou_node.HasEvents());
			IfElse ifElse = new IfElse();
			ifElse.SetClassNameString("IfElse");
			ifElse.SetId(16);
			withPrecondition.AddChild(ifElse);
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node7 action_bt_WrapperAI_Monster_BTMonsterBaozou_node = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node7();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node.SetId(7);
			ifElse.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node);
			ifElse.SetHasEvents(ifElse.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node3 action_bt_WrapperAI_Monster_BTMonsterBaozou_node2 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node3();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node2.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node2.SetId(3);
			ifElse.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node2);
			ifElse.SetHasEvents(ifElse.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node2.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(10);
			ifElse.AddChild(sequence2);
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node17 action_bt_WrapperAI_Monster_BTMonsterBaozou_node3 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node17();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node3.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node3.SetId(17);
			sequence2.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node3.HasEvents());
			IfElse ifElse2 = new IfElse();
			ifElse2.SetClassNameString("IfElse");
			ifElse2.SetId(18);
			sequence2.AddChild(ifElse2);
			Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node19 condition_bt_WrapperAI_Monster_BTMonsterBaozou_node2 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node19();
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node2.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node2.SetId(19);
			ifElse2.AddChild(condition_bt_WrapperAI_Monster_BTMonsterBaozou_node2);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterBaozou_node2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(20);
			ifElse2.AddChild(sequence3);
			Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node21 assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node5 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node21();
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node5.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node5.SetId(21);
			sequence3.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node5.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node22 assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node6 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node22();
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node6.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node6.SetId(22);
			sequence3.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node6.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | sequence3.HasEvents());
			Noop noop = new Noop();
			noop.SetClassNameString("Noop");
			noop.SetId(23);
			ifElse2.AddChild(noop);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | noop.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | ifElse2.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node26 action_bt_WrapperAI_Monster_BTMonsterBaozou_node4 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node26();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node4.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node4.SetId(26);
			sequence2.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node4.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node27 action_bt_WrapperAI_Monster_BTMonsterBaozou_node5 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node27();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node5.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node5.SetId(27);
			sequence2.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node5.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | sequence2.HasEvents());
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | ifElse.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition.HasEvents());
			WithPrecondition withPrecondition2 = new WithPrecondition();
			withPrecondition2.SetClassNameString("WithPrecondition");
			withPrecondition2.SetId(70);
			selectorLoop.AddChild(withPrecondition2);
			Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node71 condition_bt_WrapperAI_Monster_BTMonsterBaozou_node3 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node71();
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node3.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node3.SetId(71);
			withPrecondition2.AddChild(condition_bt_WrapperAI_Monster_BTMonsterBaozou_node3);
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterBaozou_node3.HasEvents());
			IfElse ifElse3 = new IfElse();
			ifElse3.SetClassNameString("IfElse");
			ifElse3.SetId(28);
			withPrecondition2.AddChild(ifElse3);
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node5 action_bt_WrapperAI_Monster_BTMonsterBaozou_node6 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node5();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node6.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node6.SetId(5);
			ifElse3.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node6);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node6.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(29);
			ifElse3.AddChild(sequence4);
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node30 action_bt_WrapperAI_Monster_BTMonsterBaozou_node7 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node30();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node7.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node7.SetId(30);
			sequence4.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node7.HasEvents());
			IfElse ifElse4 = new IfElse();
			ifElse4.SetClassNameString("IfElse");
			ifElse4.SetId(31);
			sequence4.AddChild(ifElse4);
			Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node32 condition_bt_WrapperAI_Monster_BTMonsterBaozou_node4 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node32();
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node4.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node4.SetId(32);
			ifElse4.AddChild(condition_bt_WrapperAI_Monster_BTMonsterBaozou_node4);
			ifElse4.SetHasEvents(ifElse4.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterBaozou_node4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(33);
			ifElse4.AddChild(sequence5);
			Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node35 assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node7 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node35();
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node7.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node7.SetId(35);
			sequence5.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node7.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node36 assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node8 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node36();
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node8.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node8.SetId(36);
			sequence5.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node8);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node8.HasEvents());
			ifElse4.SetHasEvents(ifElse4.HasEvents() | sequence5.HasEvents());
			Noop noop2 = new Noop();
			noop2.SetClassNameString("Noop");
			noop2.SetId(37);
			ifElse4.AddChild(noop2);
			ifElse4.SetHasEvents(ifElse4.HasEvents() | noop2.HasEvents());
			sequence4.SetHasEvents(sequence4.HasEvents() | ifElse4.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node38 action_bt_WrapperAI_Monster_BTMonsterBaozou_node8 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node38();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node8.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node8.SetId(38);
			sequence4.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node8.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node39 action_bt_WrapperAI_Monster_BTMonsterBaozou_node9 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node39();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node9.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node9.SetId(39);
			sequence4.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node9);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node9.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence4.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node6 action_bt_WrapperAI_Monster_BTMonsterBaozou_node10 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node6();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node10.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node10.SetId(6);
			ifElse3.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node10);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node10.HasEvents());
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | ifElse3.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition2.HasEvents());
			WithPrecondition withPrecondition3 = new WithPrecondition();
			withPrecondition3.SetClassNameString("WithPrecondition");
			withPrecondition3.SetId(515);
			selectorLoop.AddChild(withPrecondition3);
			Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node516 condition_bt_WrapperAI_Monster_BTMonsterBaozou_node5 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node516();
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node5.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node5.SetId(516);
			withPrecondition3.AddChild(condition_bt_WrapperAI_Monster_BTMonsterBaozou_node5);
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterBaozou_node5.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node9 action_bt_WrapperAI_Monster_BTMonsterBaozou_node11 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node9();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node11.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node11.SetId(9);
			withPrecondition3.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node11);
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node11.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition3.HasEvents());
			WithPrecondition withPrecondition4 = new WithPrecondition();
			withPrecondition4.SetClassNameString("WithPrecondition");
			withPrecondition4.SetId(24);
			selectorLoop.AddChild(withPrecondition4);
			Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node25 condition_bt_WrapperAI_Monster_BTMonsterBaozou_node6 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node25();
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node6.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node6.SetId(25);
			withPrecondition4.AddChild(condition_bt_WrapperAI_Monster_BTMonsterBaozou_node6);
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterBaozou_node6.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(165);
			withPrecondition4.AddChild(sequence6);
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(487);
			sequence6.AddChild(selector);
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node488 action_bt_WrapperAI_Monster_BTMonsterBaozou_node12 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node488();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node12.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node12.SetId(488);
			selector.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node12);
			selector.SetHasEvents(selector.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node12.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node166 action_bt_WrapperAI_Monster_BTMonsterBaozou_node13 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node166();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node13.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node13.SetId(166);
			selector.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node13);
			selector.SetHasEvents(selector.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node13.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | selector.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node167 decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node2 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node167();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node2.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node2.SetId(167);
			sequence6.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node2);
			Noop noop3 = new Noop();
			noop3.SetClassNameString("Noop");
			noop3.SetId(168);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node2.AddChild(noop3);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node2.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node2.HasEvents() | noop3.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node2.HasEvents());
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | sequence6.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition4.HasEvents());
			WithPrecondition withPrecondition5 = new WithPrecondition();
			withPrecondition5.SetClassNameString("WithPrecondition");
			withPrecondition5.SetId(34);
			selectorLoop.AddChild(withPrecondition5);
			Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node40 condition_bt_WrapperAI_Monster_BTMonsterBaozou_node7 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node40();
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node7.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node7.SetId(40);
			withPrecondition5.AddChild(condition_bt_WrapperAI_Monster_BTMonsterBaozou_node7);
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterBaozou_node7.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(41);
			withPrecondition5.AddChild(sequence7);
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node42 action_bt_WrapperAI_Monster_BTMonsterBaozou_node14 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node42();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node14.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node14.SetId(42);
			sequence7.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node14);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node14.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node43 decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node3 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node43();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node3.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node3.SetId(43);
			sequence7.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node3);
			Noop noop4 = new Noop();
			noop4.SetClassNameString("Noop");
			noop4.SetId(458);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node3.AddChild(noop4);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node3.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node3.HasEvents() | noop4.HasEvents());
			sequence7.SetHasEvents(sequence7.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node3.HasEvents());
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | sequence7.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition5.HasEvents());
			WithPrecondition withPrecondition6 = new WithPrecondition();
			withPrecondition6.SetClassNameString("WithPrecondition");
			withPrecondition6.SetId(450);
			selectorLoop.AddChild(withPrecondition6);
			Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node454 condition_bt_WrapperAI_Monster_BTMonsterBaozou_node8 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node454();
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node8.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterBaozou_node8.SetId(454);
			withPrecondition6.AddChild(condition_bt_WrapperAI_Monster_BTMonsterBaozou_node8);
			withPrecondition6.SetHasEvents(withPrecondition6.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterBaozou_node8.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(455);
			withPrecondition6.AddChild(sequence8);
			Action_bt_WrapperAI_Monster_BTMonsterBaozou_node456 action_bt_WrapperAI_Monster_BTMonsterBaozou_node15 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node456();
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node15.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterBaozou_node15.SetId(456);
			sequence8.AddChild(action_bt_WrapperAI_Monster_BTMonsterBaozou_node15);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterBaozou_node15.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node457 decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node4 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node457();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node4.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node4.SetId(457);
			sequence8.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node4);
			Noop noop5 = new Noop();
			noop5.SetClassNameString("Noop");
			noop5.SetId(2);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node4.AddChild(noop5);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node4.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node4.HasEvents() | noop5.HasEvents());
			sequence8.SetHasEvents(sequence8.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node4.HasEvents());
			withPrecondition6.SetHasEvents(withPrecondition6.HasEvents() | sequence8.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition6.HasEvents());
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node.HasEvents() | selectorLoop.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | sequence.HasEvents());
			return true;
		}
	}
}
