using System;

namespace behaviac
{
	public static class bt_WrapperAI_Organ_CrystalWithAttack
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("WrapperAI/Organ/CrystalWithAttack");
			bt.AddPar("uint", "p_targetID", "0", string.Empty);
			bt.AddPar("int", "p_srchRange", "0", string.Empty);
			bt.AddPar("uint", "p_CmdID", "0", string.Empty);
			bt.AddPar("uint", "p_commandTarget", "0", string.Empty);
			bt.AddPar("int", "p_waitFrame", "0", string.Empty);
			bt.AddPar("CSProtocol.COM_PLAYERCAMP", "p_camp", "COM_PLAYERCAMP_1", string.Empty);
			bt.AddPar("int", "p_pathIndex", "0", string.Empty);
			bt.AddPar("int", "p_attackTowerWaitFrame", "0", string.Empty);
			bt.AddPar("uint", "p_nearCommanTarget", "0", string.Empty);
			bt.AddPar("int", "p_organType", "0", string.Empty);
			bt.AddPar("int", "p_bornWaitFrame", "0", string.Empty);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			bt.AddChild(sequence);
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node82 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node82();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node.SetId(82);
			sequence.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents());
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node41 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node2 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node41();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetId(41);
			sequence.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node2);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node2.HasEvents());
			WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node52 waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node52();
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node.SetId(52);
			sequence.AddChild(waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node);
			sequence.SetHasEvents(sequence.HasEvents() | waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents());
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(28);
			sequence.AddChild(selector);
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node33 action_bt_WrapperAI_Organ_CrystalWithAttack_node = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node33();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node.SetId(33);
			selector.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node);
			selector.SetHasEvents(selector.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents());
			True @true = new True();
			@true.SetClassNameString("True");
			@true.SetId(34);
			selector.AddChild(@true);
			selector.SetHasEvents(selector.HasEvents() | @true.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | selector.HasEvents());
			DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node27 decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node = new DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node27();
			decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node.SetId(27);
			sequence.AddChild(decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node);
			Parallel_bt_WrapperAI_Organ_CrystalWithAttack_node14 parallel_bt_WrapperAI_Organ_CrystalWithAttack_node = new Parallel_bt_WrapperAI_Organ_CrystalWithAttack_node14();
			parallel_bt_WrapperAI_Organ_CrystalWithAttack_node.SetClassNameString("Parallel");
			parallel_bt_WrapperAI_Organ_CrystalWithAttack_node.SetId(14);
			decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node.AddChild(parallel_bt_WrapperAI_Organ_CrystalWithAttack_node);
			SelectorLoop selectorLoop = new SelectorLoop();
			selectorLoop.SetClassNameString("SelectorLoop");
			selectorLoop.SetId(1);
			parallel_bt_WrapperAI_Organ_CrystalWithAttack_node.AddChild(selectorLoop);
			WithPrecondition withPrecondition = new WithPrecondition();
			withPrecondition.SetClassNameString("WithPrecondition");
			withPrecondition.SetId(26);
			selectorLoop.AddChild(withPrecondition);
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(254);
			withPrecondition.AddChild(sequence2);
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node255 condition_bt_WrapperAI_Organ_CrystalWithAttack_node = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node255();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node.SetId(255);
			sequence2.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents());
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node256 action_bt_WrapperAI_Organ_CrystalWithAttack_node2 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node256();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetId(256);
			sequence2.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node2.HasEvents());
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node260 action_bt_WrapperAI_Organ_CrystalWithAttack_node3 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node260();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetId(260);
			sequence2.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node3.HasEvents());
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | sequence2.HasEvents());
			False @false = new False();
			@false.SetClassNameString("False");
			@false.SetId(252);
			withPrecondition.AddChild(@false);
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | @false.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition.HasEvents());
			WithPrecondition withPrecondition2 = new WithPrecondition();
			withPrecondition2.SetClassNameString("WithPrecondition");
			withPrecondition2.SetId(11);
			selectorLoop.AddChild(withPrecondition2);
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node12 condition_bt_WrapperAI_Organ_CrystalWithAttack_node2 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node12();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetId(12);
			withPrecondition2.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node2);
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(13);
			withPrecondition2.AddChild(sequence3);
			IfElse ifElse = new IfElse();
			ifElse.SetClassNameString("IfElse");
			ifElse.SetId(9);
			sequence3.AddChild(ifElse);
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node15 condition_bt_WrapperAI_Organ_CrystalWithAttack_node3 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node15();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetId(15);
			ifElse.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node3);
			ifElse.SetHasEvents(ifElse.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(17);
			ifElse.AddChild(sequence4);
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node16 action_bt_WrapperAI_Organ_CrystalWithAttack_node4 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node16();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node4.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node4.SetId(16);
			sequence4.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node4.HasEvents());
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node18 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node3 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node18();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetId(18);
			sequence4.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node3);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node3.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | sequence4.HasEvents());
			Noop noop = new Noop();
			noop.SetClassNameString("Noop");
			noop.SetId(19);
			ifElse.AddChild(noop);
			ifElse.SetHasEvents(ifElse.HasEvents() | noop.HasEvents());
			sequence3.SetHasEvents(sequence3.HasEvents() | ifElse.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(81);
			sequence3.AddChild(sequence5);
			IfElse ifElse2 = new IfElse();
			ifElse2.SetClassNameString("IfElse");
			ifElse2.SetId(10);
			sequence5.AddChild(ifElse2);
			And and = new And();
			and.SetClassNameString("And");
			and.SetId(21);
			ifElse2.AddChild(and);
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node20 condition_bt_WrapperAI_Organ_CrystalWithAttack_node4 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node20();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node4.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node4.SetId(20);
			and.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node4);
			and.SetHasEvents(and.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node4.HasEvents());
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node22 condition_bt_WrapperAI_Organ_CrystalWithAttack_node5 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node22();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node5.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node5.SetId(22);
			and.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node5);
			and.SetHasEvents(and.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node5.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | and.HasEvents());
			Noop noop2 = new Noop();
			noop2.SetClassNameString("Noop");
			noop2.SetId(23);
			ifElse2.AddChild(noop2);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | noop2.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(24);
			ifElse2.AddChild(sequence6);
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node25 action_bt_WrapperAI_Organ_CrystalWithAttack_node5 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node25();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node5.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node5.SetId(25);
			sequence6.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node5);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node5.HasEvents());
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node83 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node4 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node83();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node4.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node4.SetId(83);
			sequence6.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node4);
			sequence6.SetHasEvents(sequence6.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node4.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | sequence6.HasEvents());
			sequence5.SetHasEvents(sequence5.HasEvents() | ifElse2.HasEvents());
			IfElse ifElse3 = new IfElse();
			ifElse3.SetClassNameString("IfElse");
			ifElse3.SetId(84);
			sequence5.AddChild(ifElse3);
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node85 condition_bt_WrapperAI_Organ_CrystalWithAttack_node6 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node85();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node6.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node6.SetId(85);
			ifElse3.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node6);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(86);
			ifElse3.AddChild(sequence7);
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node140 action_bt_WrapperAI_Organ_CrystalWithAttack_node6 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node140();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node6.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node6.SetId(140);
			sequence7.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node6);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node6.HasEvents());
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node87 action_bt_WrapperAI_Organ_CrystalWithAttack_node7 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node87();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node7.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node7.SetId(87);
			sequence7.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node7.HasEvents());
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node88 action_bt_WrapperAI_Organ_CrystalWithAttack_node8 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node88();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node8.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node8.SetId(88);
			sequence7.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node8);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node8.HasEvents());
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node91 action_bt_WrapperAI_Organ_CrystalWithAttack_node9 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node91();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node9.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node9.SetId(91);
			sequence7.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node9);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node9.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node92 decoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node = new DecoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node92();
			decoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node.SetId(92);
			sequence7.AddChild(decoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node);
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node93 condition_bt_WrapperAI_Organ_CrystalWithAttack_node7 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node93();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node7.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node7.SetId(93);
			decoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node7);
			decoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node7.HasEvents());
			sequence7.SetHasEvents(sequence7.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence7.HasEvents());
			WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node5 waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node2 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node5();
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetId(5);
			ifElse3.AddChild(waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node2);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node2.HasEvents());
			sequence5.SetHasEvents(sequence5.HasEvents() | ifElse3.HasEvents());
			sequence3.SetHasEvents(sequence3.HasEvents() | sequence5.HasEvents());
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | sequence3.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition2.HasEvents());
			WithPrecondition withPrecondition3 = new WithPrecondition();
			withPrecondition3.SetClassNameString("WithPrecondition");
			withPrecondition3.SetId(2);
			selectorLoop.AddChild(withPrecondition3);
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node3 condition_bt_WrapperAI_Organ_CrystalWithAttack_node8 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node3();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node8.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node8.SetId(3);
			withPrecondition3.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node8);
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node8.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(6);
			withPrecondition3.AddChild(sequence8);
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node4 action_bt_WrapperAI_Organ_CrystalWithAttack_node10 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node4();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node10.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node10.SetId(4);
			sequence8.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node10);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node10.HasEvents());
			DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node7 decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node2 = new DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node7();
			decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetId(7);
			sequence8.AddChild(decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node2);
			Noop noop3 = new Noop();
			noop3.SetClassNameString("Noop");
			noop3.SetId(8);
			decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node2.AddChild(noop3);
			decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetHasEvents(decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node2.HasEvents() | noop3.HasEvents());
			sequence8.SetHasEvents(sequence8.HasEvents() | decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node2.HasEvents());
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | sequence8.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition3.HasEvents());
			parallel_bt_WrapperAI_Organ_CrystalWithAttack_node.SetHasEvents(parallel_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents() | selectorLoop.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(75);
			parallel_bt_WrapperAI_Organ_CrystalWithAttack_node.AddChild(sequence9);
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node30 action_bt_WrapperAI_Organ_CrystalWithAttack_node11 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node30();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node11.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node11.SetId(30);
			sequence9.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node11);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node11.HasEvents());
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node97 condition_bt_WrapperAI_Organ_CrystalWithAttack_node9 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node97();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node9.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node9.SetId(97);
			sequence9.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node9);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node9.HasEvents());
			SelectorLoop selectorLoop2 = new SelectorLoop();
			selectorLoop2.SetClassNameString("SelectorLoop");
			selectorLoop2.SetId(80);
			sequence9.AddChild(selectorLoop2);
			WithPrecondition withPrecondition4 = new WithPrecondition();
			withPrecondition4.SetClassNameString("WithPrecondition");
			withPrecondition4.SetId(89);
			selectorLoop2.AddChild(withPrecondition4);
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(90);
			withPrecondition4.AddChild(sequence10);
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node76 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node5 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node76();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node5.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node5.SetId(76);
			sequence10.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node5);
			sequence10.SetHasEvents(sequence10.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node5.HasEvents());
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node77 condition_bt_WrapperAI_Organ_CrystalWithAttack_node10 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node77();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node10.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node10.SetId(77);
			sequence10.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node10);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node10.HasEvents());
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(94);
			withPrecondition4.AddChild(sequence11);
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node78 action_bt_WrapperAI_Organ_CrystalWithAttack_node12 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node78();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node12.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node12.SetId(78);
			sequence11.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node12);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node12.HasEvents());
			Compute_bt_WrapperAI_Organ_CrystalWithAttack_node31 compute_bt_WrapperAI_Organ_CrystalWithAttack_node = new Compute_bt_WrapperAI_Organ_CrystalWithAttack_node31();
			compute_bt_WrapperAI_Organ_CrystalWithAttack_node.SetClassNameString("Compute");
			compute_bt_WrapperAI_Organ_CrystalWithAttack_node.SetId(31);
			sequence11.AddChild(compute_bt_WrapperAI_Organ_CrystalWithAttack_node);
			sequence11.SetHasEvents(sequence11.HasEvents() | compute_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents());
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node39 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node6 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node39();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node6.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node6.SetId(39);
			sequence11.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node6);
			sequence11.SetHasEvents(sequence11.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node6.HasEvents());
			WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node79 waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node3 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node79();
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetId(79);
			sequence11.AddChild(waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node3);
			sequence11.SetHasEvents(sequence11.HasEvents() | waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node3.HasEvents());
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | sequence11.HasEvents());
			selectorLoop2.SetHasEvents(selectorLoop2.HasEvents() | withPrecondition4.HasEvents());
			WithPrecondition withPrecondition5 = new WithPrecondition();
			withPrecondition5.SetClassNameString("WithPrecondition");
			withPrecondition5.SetId(40);
			selectorLoop2.AddChild(withPrecondition5);
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node29 action_bt_WrapperAI_Organ_CrystalWithAttack_node13 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node29();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node13.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node13.SetId(29);
			withPrecondition5.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node13);
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node13.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(74);
			withPrecondition5.AddChild(sequence12);
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node98 condition_bt_WrapperAI_Organ_CrystalWithAttack_node11 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node98();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node11.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node11.SetId(98);
			sequence12.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node11);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node11.HasEvents());
			Compute_bt_WrapperAI_Organ_CrystalWithAttack_node99 compute_bt_WrapperAI_Organ_CrystalWithAttack_node2 = new Compute_bt_WrapperAI_Organ_CrystalWithAttack_node99();
			compute_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetClassNameString("Compute");
			compute_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetId(99);
			sequence12.AddChild(compute_bt_WrapperAI_Organ_CrystalWithAttack_node2);
			sequence12.SetHasEvents(sequence12.HasEvents() | compute_bt_WrapperAI_Organ_CrystalWithAttack_node2.HasEvents());
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node100 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node7 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node100();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node7.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node7.SetId(100);
			sequence12.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node7);
			sequence12.SetHasEvents(sequence12.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node7.HasEvents());
			SelectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node101 selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node = new SelectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node101();
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.SetClassNameString("SelectorProbability");
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.SetId(101);
			sequence12.AddChild(selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node);
			DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node102 decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node = new DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node102();
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node.SetId(102);
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.AddChild(decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node);
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(103);
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node.AddChild(sequence13);
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node104 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node8 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node104();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node8.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node8.SetId(104);
			sequence13.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node8);
			sequence13.SetHasEvents(sequence13.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node8.HasEvents());
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node105 condition_bt_WrapperAI_Organ_CrystalWithAttack_node12 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node105();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node12.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node12.SetId(105);
			sequence13.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node12);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node12.HasEvents());
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node106 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node9 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node106();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node9.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node9.SetId(106);
			sequence13.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node9);
			sequence13.SetHasEvents(sequence13.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node9.HasEvents());
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node107 condition_bt_WrapperAI_Organ_CrystalWithAttack_node13 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node107();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node13.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node13.SetId(107);
			sequence13.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node13);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node13.HasEvents());
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node108 action_bt_WrapperAI_Organ_CrystalWithAttack_node14 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node108();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node14.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node14.SetId(108);
			sequence13.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node14);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node14.HasEvents());
			WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node109 waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node4 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node109();
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node4.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node4.SetId(109);
			sequence13.AddChild(waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node4);
			sequence13.SetHasEvents(sequence13.HasEvents() | waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node4.HasEvents());
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node.SetHasEvents(decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents() | sequence13.HasEvents());
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.SetHasEvents(selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents() | decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents());
			DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node110 decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node2 = new DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node110();
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetId(110);
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.AddChild(decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node2);
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(111);
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node2.AddChild(sequence14);
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node32 condition_bt_WrapperAI_Organ_CrystalWithAttack_node14 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node32();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node14.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node14.SetId(32);
			sequence14.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node14);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node14.HasEvents());
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node112 condition_bt_WrapperAI_Organ_CrystalWithAttack_node15 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node112();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node15.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node15.SetId(112);
			sequence14.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node15);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node15.HasEvents());
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node113 condition_bt_WrapperAI_Organ_CrystalWithAttack_node16 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node113();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node16.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node16.SetId(113);
			sequence14.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node16);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node16.HasEvents());
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node114 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node10 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node114();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node10.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node10.SetId(114);
			sequence14.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node10);
			sequence14.SetHasEvents(sequence14.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node10.HasEvents());
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node115 condition_bt_WrapperAI_Organ_CrystalWithAttack_node17 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node115();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node17.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node17.SetId(115);
			sequence14.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node17);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node17.HasEvents());
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node116 action_bt_WrapperAI_Organ_CrystalWithAttack_node15 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node116();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node15.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node15.SetId(116);
			sequence14.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node15);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node15.HasEvents());
			WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node117 waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node5 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node117();
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node5.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node5.SetId(117);
			sequence14.AddChild(waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node5);
			sequence14.SetHasEvents(sequence14.HasEvents() | waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node5.HasEvents());
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node2.SetHasEvents(decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node2.HasEvents() | sequence14.HasEvents());
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.SetHasEvents(selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents() | decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node2.HasEvents());
			DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node118 decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node3 = new DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node118();
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetId(118);
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.AddChild(decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node3);
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(119);
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node3.AddChild(sequence15);
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node120 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node11 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node120();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node11.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node11.SetId(120);
			sequence15.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node11);
			sequence15.SetHasEvents(sequence15.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node11.HasEvents());
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node121 condition_bt_WrapperAI_Organ_CrystalWithAttack_node18 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node121();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node18.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node18.SetId(121);
			sequence15.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node18);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node18.HasEvents());
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node122 action_bt_WrapperAI_Organ_CrystalWithAttack_node16 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node122();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node16.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node16.SetId(122);
			sequence15.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node16);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node16.HasEvents());
			WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node123 waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node6 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node123();
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node6.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node6.SetId(123);
			sequence15.AddChild(waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node6);
			sequence15.SetHasEvents(sequence15.HasEvents() | waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node6.HasEvents());
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetHasEvents(decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node3.HasEvents() | sequence15.HasEvents());
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.SetHasEvents(selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents() | decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node3.HasEvents());
			DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node124 decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node4 = new DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node124();
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node4.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node4.SetId(124);
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.AddChild(decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node4);
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(125);
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node4.AddChild(sequence16);
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node126 condition_bt_WrapperAI_Organ_CrystalWithAttack_node19 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node126();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node19.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node19.SetId(126);
			sequence16.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node19);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node19.HasEvents());
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node127 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node12 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node127();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node12.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node12.SetId(127);
			sequence16.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node12);
			sequence16.SetHasEvents(sequence16.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node12.HasEvents());
			Condition_bt_WrapperAI_Organ_CrystalWithAttack_node128 condition_bt_WrapperAI_Organ_CrystalWithAttack_node20 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node128();
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node20.SetClassNameString("Condition");
			condition_bt_WrapperAI_Organ_CrystalWithAttack_node20.SetId(128);
			sequence16.AddChild(condition_bt_WrapperAI_Organ_CrystalWithAttack_node20);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_WrapperAI_Organ_CrystalWithAttack_node20.HasEvents());
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node129 action_bt_WrapperAI_Organ_CrystalWithAttack_node17 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node129();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node17.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node17.SetId(129);
			sequence16.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node17);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node17.HasEvents());
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node130 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node13 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node130();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node13.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node13.SetId(130);
			sequence16.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node13);
			sequence16.SetHasEvents(sequence16.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node13.HasEvents());
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node131 action_bt_WrapperAI_Organ_CrystalWithAttack_node18 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node131();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node18.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node18.SetId(131);
			sequence16.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node18);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node18.HasEvents());
			Compute_bt_WrapperAI_Organ_CrystalWithAttack_node132 compute_bt_WrapperAI_Organ_CrystalWithAttack_node3 = new Compute_bt_WrapperAI_Organ_CrystalWithAttack_node132();
			compute_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetClassNameString("Compute");
			compute_bt_WrapperAI_Organ_CrystalWithAttack_node3.SetId(132);
			sequence16.AddChild(compute_bt_WrapperAI_Organ_CrystalWithAttack_node3);
			sequence16.SetHasEvents(sequence16.HasEvents() | compute_bt_WrapperAI_Organ_CrystalWithAttack_node3.HasEvents());
			Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node133 assignment_bt_WrapperAI_Organ_CrystalWithAttack_node14 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node133();
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node14.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Organ_CrystalWithAttack_node14.SetId(133);
			sequence16.AddChild(assignment_bt_WrapperAI_Organ_CrystalWithAttack_node14);
			sequence16.SetHasEvents(sequence16.HasEvents() | assignment_bt_WrapperAI_Organ_CrystalWithAttack_node14.HasEvents());
			WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node134 waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node7 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node134();
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node7.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node7.SetId(134);
			sequence16.AddChild(waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node7);
			sequence16.SetHasEvents(sequence16.HasEvents() | waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node7.HasEvents());
			Action_bt_WrapperAI_Organ_CrystalWithAttack_node135 action_bt_WrapperAI_Organ_CrystalWithAttack_node19 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node135();
			action_bt_WrapperAI_Organ_CrystalWithAttack_node19.SetClassNameString("Action");
			action_bt_WrapperAI_Organ_CrystalWithAttack_node19.SetId(135);
			sequence16.AddChild(action_bt_WrapperAI_Organ_CrystalWithAttack_node19);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_WrapperAI_Organ_CrystalWithAttack_node19.HasEvents());
			WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node136 waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node8 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node136();
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node8.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node8.SetId(136);
			sequence16.AddChild(waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node8);
			sequence16.SetHasEvents(sequence16.HasEvents() | waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node8.HasEvents());
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node4.SetHasEvents(decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node4.HasEvents() | sequence16.HasEvents());
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.SetHasEvents(selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents() | decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node4.HasEvents());
			DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node137 decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node5 = new DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node137();
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node5.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node5.SetId(137);
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.AddChild(decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node5);
			Noop noop4 = new Noop();
			noop4.SetClassNameString("Noop");
			noop4.SetId(138);
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node5.AddChild(noop4);
			decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node5.SetHasEvents(decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node5.HasEvents() | noop4.HasEvents());
			selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.SetHasEvents(selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents() | decoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node5.HasEvents());
			sequence12.SetHasEvents(sequence12.HasEvents() | selectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents());
			WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node139 waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node9 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node139();
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node9.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node9.SetId(139);
			sequence12.AddChild(waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node9);
			sequence12.SetHasEvents(sequence12.HasEvents() | waitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node9.HasEvents());
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | sequence12.HasEvents());
			selectorLoop2.SetHasEvents(selectorLoop2.HasEvents() | withPrecondition5.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | selectorLoop2.HasEvents());
			parallel_bt_WrapperAI_Organ_CrystalWithAttack_node.SetHasEvents(parallel_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents() | sequence9.HasEvents());
			decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node.SetHasEvents(decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents() | parallel_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | sequence.HasEvents());
			return true;
		}
	}
}
