using System;

namespace CSProtocol
{
	public enum ACCOUNTSTATUS_MACRO
	{
		LR_LOGINPLAYERFULL = -19,
		LR_AREAREGISTER_CONTROL,
		LR_CLIENT_FAKE,
		LR_SERVER_REFUSE,
		LR_SERVER_BUSY,
		LR_SERVER_REDIRECT,
		LR_SERVER_COLSE,
		LR_REGISTER_CLOSE,
		LR_REGISTER_CONTROL,
		LR_PAYTOKEN_INVALID,
		LR_SERVERVERSION_INVALID,
		LR_CLIENTVERSION_INVALID,
		LR_CLIENTVERSION_TOOOLD,
		LR_TOKENEXPIRE,
		LR_OPENPFVERIFYFAIL,
		LR_DBERROR,
		LR_PREVILEGE,
		LR_IDIP,
		LR_CHEAT,
		LR_NOLOCK
	}
}
