using System;

namespace CSProtocol
{
	public enum COM_ITEM_TYPE
	{
		COM_OBJTYPE_NULL,
		COM_OBJTYPE_ACCOUNT,
		COM_OBJTYPE_ITEMPROP,
		COM_OBJTYPE_ITEMEQUIP,
		COM_OBJTYPE_HERO,
		COM_OBJTYPE_ITEMSYMBOL,
		COM_OBJTYPE_ITEMGEAR,
		COM_OBJTYPE_HEROSKIN,
		COM_OBJTYPE_HEADIMG,
		COM_OBJTYPE_MAX
	}
}
