using System;

namespace CSProtocol
{
	public enum COM_APOLLO_TRANK_USERBUFFER_TYPE
	{
		COM_APOLLO_TRANK_USERBUFFER_TYPE_UPLOAD_SCORE = 1,
		COM_APOLLO_TRANK_USERBUFFER_TYPE_GET_TOPN,
		COM_APOLLO_TRANK_USERBUFFER_TYPE_GET_USER_INFO,
		COM_APOLLO_TRANK_USERBUFFER_TYPE_CLEAR_SPECIAL_TOPN,
		COM_APOLLO_TRANK_USERBUFFER_TYPE_GET_SPECIAL_SCORE,
		COM_APOLLO_TRANK_USERBUFFER_TYPE_GET_TOPN_LUCKY,
		COM_APOLLO_TRANK_USERBUFFER_TYPE_MAX
	}
}
