using System;

namespace CSProtocol
{
	public enum COM_CHAT_MSG_TYPE
	{
		COM_CHAT_MSG_TYPE_LOGIC_WORLD = 1,
		COM_CHAT_MSG_TYPE_PRIVATE,
		COM_CHAT_MSG_TYPE_ROOM,
		COM_CHAT_MSG_TYPE_GUILD,
		COM_CHAT_MSG_TYPE_BATTLE,
		COM_CHAT_MSG_TYPE_TEAM,
		COM_CHAT_MSG_TYPE_INBATTLE,
		COM_CHAT_MSG_TYPE_SETTLE,
		COM_CHAT_MSG_TYPE_SMALL_HORN,
		COM_CHAT_MSG_TYPE_BIG_HORN,
		COM_CHAT_MSG_TYPE_GUILD_TEAM
	}
}
