using System;

namespace CSProtocol
{
	public enum COM_GAME_TYPE
	{
		COM_SINGLE_GAME_OF_ADVENTURE,
		COM_SINGLE_GAME_OF_COMBAT,
		COM_SINGLE_GAME_OF_GUIDE,
		COM_SINGLE_GAME_OF_ACTIVITY,
		COM_MULTI_GAME_OF_LADDER,
		COM_MULTI_GAME_OF_PVP_MATCH,
		COM_MULTI_GAME_OF_PVP_ROOM,
		COM_SINGLE_GAME_OF_BURNING,
		COM_SINGLE_GAME_OF_ARENA,
		COM_MULTI_GAME_OF_ENTERTAINMENT,
		COM_MULTI_GAME_OF_REWARDMATCH,
		COM_MULTI_GAME_OF_GUILDMATCH,
		COM_GAME_TYPE_MAX
	}
}
