using System;

namespace CSProtocol
{
	public enum COM_HERO_WAKESTATE_TYPE
	{
		COM_HERO_WAKESTATE_INVALID,
		COM_HERO_WAKESTATE_WAIT,
		COM_HERO_WATESTATE_PROC,
		COM_HERO_WATESTATE_FINISH,
		COM_HERO_WATESTATE_MAX
	}
}
