using System;

namespace CSProtocol
{
	public enum COM_ACNT_OPER_LIMIT
	{
		COM_ACNT_OPER_LIMIT_GETARENAFIGHTHISTORY,
		COM_ACNT_OPER_LIMIT_GETFRIENDSTATE,
		COM_ACNT_OPER_LIMIT_GETSTUDENTLIST,
		COM_ACNT_OPER_LIMIT_MAX
	}
}
