using System;

namespace CSProtocol
{
	public enum COM_ROLLINGMSG_DISPLAY_POS
	{
		COM_ROLLINGMSG_DISPLAY_NONE,
		COM_ROLLINGMSG_DISPLAY_CHAT,
		COM_ROLLINGMSG_DISPLAY_HORN,
		COM_ROLLINGMSG_DISPLAY_BOTH
	}
}
