using System;

namespace CSProtocol
{
	public enum COM_PRIVILEGE_TYPE
	{
		COM_PRIVILEGE_TYPE_NONE,
		COM_PRIVILEGE_TYPE_WXGAMECENTER_LOGIN,
		COM_PRIVILEGE_TYPE_QQGAMECENTER_LOGIN,
		COM_PRIVILEGE_TYPE_IOSVISITOR_LOGIN
	}
}
