using System;

namespace CSProtocol
{
	public enum COM_INGAME_CHEAT_TYPE
	{
		COM_INGAME_CHEAT_TYPE_NULL,
		COM_INGAME_CHEAT_TYPE_SKILLCD,
		COM_INGAME_CHEAT_TYPE_HASHNE,
		COM_INGAME_CHEAT_TYPE_MAX
	}
}
