using System;

namespace CSProtocol
{
	public enum COM_AI_LEVEL
	{
		COM_AI_LEVEL_EASY_OF_NORMALBATTLE = 1,
		COM_AI_LEVEL_MIDDLE_OF_NORMALBATTLE,
		COM_AI_LEVEL_HARD_OF_NORMALBATTLE,
		COM_AI_LEVEL_PROFESSIONAL_OF_NORMALBATTLE,
		COM_AI_LEVEL_EASY_OF_WARMBATTLE,
		COM_AI_LEVEL_HARD_OF_WARMBATTLE,
		COM_AI_LEVEL_MAX
	}
}
