using System;

namespace CSProtocol
{
	public enum COM_WORLDRANK_ERRCODE
	{
		COM_WORLDRANK_ERRCODE_LOGICWORLDID = 1,
		COM_WORLDRANK_ERRCODE_NOTPREPARED,
		COM_WORLDRANK_ERRCODE_RANKTYPE,
		COM_WORLDRANK_ERRCODE_OTHER
	}
}
