using System;

namespace CSProtocol
{
	public enum COM_INBATTLE_CHAT_TYPE
	{
		COM_INBATTLE_CHATTYPE_SIGNAL = 1,
		COM_INBATTLE_CHATTYPE_BUBBLE,
		COM_INBATTLE_CHATTYPE_SELFINPUT,
		COM_INBATTLE_CHATTYPE_SELFDEFINEINPUT
	}
}
