using System;

namespace CSProtocol
{
	public enum COM_CHGCREDIT_TYPE
	{
		COM_CHGCREDIT_NONE,
		COM_CHGCREDIT_COMPLAINT_GUAJI,
		COM_CHGCREDIT_COMPLAINT_SONG,
		COM_CHGCREDIT_COMPLAINT_XIAOJI,
		COM_CHGCREDIT_COMPLAINT_MAREN,
		COM_CHGCREDIT_COMPLAINT_YANYUAN,
		COM_CHGCREDIT_COMPLAINT_GUA,
		COM_CHGCREDIT_HANGUP,
		COM_CHGCREDIT_NOTLOGIN,
		COM_CHGCREDIT_UNCONFIRM,
		COM_CHGCREDIT_SETTLE_DEL,
		COM_CHGCREDIT_SETTLE_ADD,
		COM_CHGCREDIT_OUTGAME,
		COM_CHGCREDIT_MAX
	}
}
