using System;

namespace CSProtocol
{
	public enum COM_COIN_TYPE
	{
		COM_COINTYPE_COIN,
		COM_COINTYPE_PVPCOIN,
		COM_COINTYPE_BURNING_COIN,
		COM_COINTYPE_ARENA_COIN,
		COM_COINTYPE_SKINCOIN,
		COM_COINTYPE_SYMBOLCOIN,
		COM_COINTYPE_DIAMOND,
		COM_COINTYPE_SCORE,
		COM_COINTYPE_MAX,
		COM_COINTYPE_COUPONS,
		COM_COINTYPE_MIXPAY
	}
}
