using System;

namespace CSProtocol
{
	public enum COM_PLATFORM_STATISTIC_TYPE
	{
		COM_PLATFORM_STATISTIC_TYPE_NULL,
		COM_PLATFORM_STATISTIC_TYPE_GODLIKE,
		COM_PLATFORM_STATISTIC_TYPE_DEAD,
		COM_PLATFORM_STATISTIC_TYPE_KILL,
		COM_PLATFORM_STATISTIC_TYPE_ASSIST,
		COM_PLATFORM_STATISTIC_TYPE_MVP,
		COM_PLATFORM_STATISTIC_TYPE_TRIPLE_KILL,
		COM_PLATFORM_STATISTIC_TYPE_QUATARY_KILL,
		COM_PLATFORM_STATISTIC_TYPE_PENTA_KILL,
		COM_PLATFORM_STATISTIC_TYPE_MAX
	}
}
