using System;

namespace CSProtocol
{
	public enum COM_GUILDMATCH_INVITECARD_STATE
	{
		COM_GUILDMATCH_INVITECARD_STATE_NULL,
		COM_GUILDMATCH_INVITECARD_STATE_ACCEPT,
		COM_GUILDMATCH_INVITECARD_STATE_REFUSE
	}
}
