using System;

namespace CSProtocol
{
	public enum COM_HYPERLINK_TYPE
	{
		COM_HYPERLINK_TYPE_GUILD_INVITE = 1,
		COM_HYPERLINK_TYPE_PREGUILD_INVITE,
		COM_HYPERLINK_TYPE_FORM_JUMP,
		COM_HYPERLINK_TYPE_URL
	}
}
