using System;

namespace CSProtocol
{
	public enum COM_SHOP_DRAW_SUBTYPE
	{
		COM_SHOPDRAW_SUB_FREE = 1,
		COM_SHOPDRAW_SUB_ONE,
		COM_SHOPDRAW_SUB_FIVE,
		COM_SHOPDRAW_SUB_TEN,
		COM_SHOPDRAW_SUB_MAX
	}
}
