using System;

namespace CSProtocol
{
	public enum COM_TRANSACTION_CONTEXT_TYPE
	{
		COM_TRANSACTION_CONTEXT_RANK = 1,
		COM_TRANSACTION_CONTEXT_ONLINECHK,
		COM_TRANSACTION_CONTEXT_JOIN_GUILD,
		COM_TRANSACTION_CONTEXT_APPROVE_JOIN_GUILD,
		COM_TRANSACTION_CONTEXT_QUIT_GUILD,
		COM_TRANSACTION_CONTEXT_GUILD_INVITE,
		COM_TRANSACTION_CONTEXT_SEARCH_GUILD,
		COM_TRANSACTION_CONTEXT_DEAL_GUILD_INVITE,
		COM_TRANSACTION_CONTEXT_GUILD_RECOMMEND,
		COM_TRANSACTION_CONTEXT_GUILD_GETNAME,
		COM_TRANSACTION_CONTEXT_GETARENA_TARGETDATA,
		COM_TRANSACTION_CONTEXT_APPOINT_POSITION,
		COM_TRANSACTION_CONTEXT_FIRE_MEMBER,
		COM_TRANSACTION_CONTEXT_ADD_ARENAFIGHT_HISTORY,
		COM_TRANSACTION_CONTEXT_DELETEBURNINGENEMY,
		COM_TRANSACTION_CONTEXT_TRANS_BASE_INFO,
		COM_TRANSACTION_CONTEXT_ADD_RANKCURSEASONDATA,
		COM_TRANSACTION_CONTEXT_ADD_RANKPASTSEASONDATA,
		COM_TRANSACTION_CONTEXT_LUCKYDRAW,
		COM_TRANSACTION_CONTEXT_CHANGE_PLAYER_NAME,
		COM_TRANSACTION_CONTEXT_CHANGE_GUILD_NAME,
		COM_TRANSACTION_CONTEXT_ADD_FIGHTHISTORY,
		COM_TRANSACTION_CONTEXT_TRANS_REGISTER_INFO,
		COM_TRANSACTION_CONTEXT_GETACNTMOBAINFO,
		COM_TRANSACTION_CONTEXT_APPLYMASTERREQ,
		COM_TRANSACTION_CONTEXT_CONFIRMMASTERREQ,
		COM_TRANSACTION_CONTEXT_APPLYSTUDENTREQ,
		COM_TRANSACTION_CONTEXT_CONFIRMSTUDENTREQ,
		COM_TRANSACTION_CONTEXT_REMOVEMASTERREQ,
		COM_TRANSACTION_CONTEXT_GETPROCESS_STUDENTINFO,
		COM_TRANSACTION_CONTEXT_GETGRADUATE_STUDENTINFO,
		COM_TRANSACTION_CONTEXT_GRADUATE_FROM_MASTER,
		COM_TRANSACTION_CONTEXT_GET_FIGHT_HISTORY,
		COM_TRANSACTION_CONTEXT_ADD_FRIEND_CONFIRM,
		COM_TRANSACTION_CONTEXT_DEL_FRIEND,
		COM_TRANSACTION_CONTEXT_SEARCH_PALYER,
		COM_TRANSACTION_CONTEXT_ADD_FRIEND,
		COM_TRANSACTION_CONTEXT_ADD_FRIEND_DENY,
		COM_TRANSACTION_CONTEXT_GIFTUSE
	}
}
