using System;

namespace CSProtocol
{
	public enum COM_MAILSOURCE_TYPE
	{
		COM_MAILSOURCE_GM = 1,
		COM_MAILSOURCE_GLOABALREWARD,
		COM_MAILSOURCE_GUILD,
		COM_MAILSOURCE_IDIP,
		COM_MAILSOURCE_TASK,
		COM_MAILSOURCE_AREAN,
		COM_MAILSOURCE_ACTIVITY,
		COM_MAILSOURCE_PAY,
		COM_MAILSOURCE_ITEM,
		COM_MAILSOURCE_SWEEP,
		COM_MAILSOURCE_PVP,
		COM_MAILSOURCE_PVE,
		COM_MAILSOURCE_GAMEVIP,
		COM_MAILSOURCE_RANK,
		COM_MAILSOURCE_HERO,
		COM_MAILSOURCE_ACHIEVEMENT,
		COM_MAILSOURCE_LUCKYDRAW,
		COM_MAILSOURCE_EXPCARD,
		COM_MAILSOURCE_RANDDRAW,
		COM_MAILSOURCE_MONTHWEEK,
		COM_MAILSOURCE_GAINCHEST,
		COM_MAILSOURCE_REWARDMATCH,
		COM_MAILSOURCE_FRIENDDONATE,
		COM_MAILSOURCE_LUCKYREWARD,
		COM_MAILSOURCE_CREDITREWARD,
		COM_MAILSOURCE_GAMECENTER,
		COM_MAILSOURCE_TROPHY,
		COM_MAILSOURCE_RECRUITMENT,
		COM_MAILSOURCE_LBS,
		COM_MAILSOURCE_XUNYOUCHK,
		COM_MAILSOURCE_ASKFORREQ
	}
}
