using System;

namespace CSProtocol
{
	public enum COM_REDDOTLABEL_TYPE
	{
		COM_REDDOTLABEL_REDDOT = 1,
		COM_REDDOTLABEL_SAISHI,
		COM_REDDOTLABEL_LOWZHEKOU,
		COM_REDDOTLABEL_HIGHZHEKOU,
		COM_REDDOTLABEL_NEWPRODUCT,
		COM_REDDOTLABEL_SALE,
		COM_REDDOTLABEL_XIANDING
	}
}
