using System;

namespace CSProtocol
{
	public enum CS_ACNT_UPDATE_FROMTYPE
	{
		CS_ACNT_UPDATE_FROMTYPE_NULL,
		CS_ACNT_UPDATE_FROMTYPE_PROP,
		CS_ACNT_UPDATE_FROMTYPE_SWEEP,
		CS_ACNT_UPDATE_FROMTYPE_TASK,
		CS_ACNT_UPDATE_FROMTYPE_MAIL,
		CS_ACNT_UPDATE_FROMTYPE_HUOYUEDU,
		CS_ACNT_UPDATE_FROMTYPE_IDIP
	}
}
