using System;

namespace CSProtocol
{
	public enum CS_ACNTINFO_UPD_TYPE
	{
		CS_ACNTINFO_UPD_NULL,
		CS_ACNTINFO_UPD_LEVEL,
		CS_ACNTINFO_UPD_EXP,
		CS_ACNTINFO_UPD_MAXAP,
		CS_ACNTINFO_UPD_CURAP,
		CS_ACNTINFO_UPD_COIN,
		CS_ACNTINFO_UPD_DIAMOND,
		CS_ACNTINFO_UPD_LEVEL_INFO,
		CS_ACNTINFO_UPD_SKILLPOINT,
		CS_ACNTINFO_UPD_ENCHANTPT,
		CS_ACNTINFO_UPD_PVP_LEVEL,
		CS_ACNTINFO_UPD_PVP_EXP,
		CS_ACNTINFO_UPD_PVP_COIN,
		CS_ACNTINFO_UPD_BURNING_COIN,
		CS_ACNTINFO_UPD_ARENA_COIN,
		CS_ACNTINFO_UPD_HEROPOOLEXP,
		CS_ACNTINFO_UPD_SKIN_COIN,
		CS_ACNTINFO_UPD_SYMBOL_COIN,
		CS_ACNTINFO_UPD_HUOYUEDU,
		CS_ACNTINFO_UPD_TEAMMATELIKE,
		CS_ACNTINFO_UPD_OPPONENTLIKE,
		CS_ACNTINFO_UPD_SCORE
	}
}
