using System;

namespace CSProtocol
{
	public enum CS_EXPCARD_ERRCODE
	{
		CS_EXPCARD_HEROOWN = 2,
		CS_EXPCARD_INSERTHERO,
		CS_EXPCARD_SKINOWN,
		CS_EXPCARD_INSERTSKIN,
		CS_EXPCARD_NOUSEHERO,
		CS_EXPCARD_OTHER
	}
}
