using System;

namespace CSProtocol
{
	public enum CS_HEROOPER_ERROR_CODE_DEF
	{
		CS_HEROOPER_ERROR_CODE_OTHER = 1,
		CS_HEROOPER_ERROR_CODE_INVALID_POS,
		CS_HEROOPER_ERROR_CODE_INVALID_HEROID,
		CS_HEROOPER_ERROR_CODE_DUP,
		CS_HEROOPER_ERROR_CODE_UNEFFECT
	}
}
