using System;

namespace CSProtocol
{
	public enum CS_LUCKYDRAW_EXTERN_ERRCODE
	{
		CS_LUCKYDRAW_EXTERN_MONEYTYPE = 1,
		CS_LUCKYDRAW_EXTERN_PERIODINDEX,
		CS_LUCKYDRAW_EXTERN_NOREACH,
		CS_LUCKYDRAW_EXTERN_DRAWED,
		CS_LUCKYDRAW_EXTERN_REWARDID,
		CS_LUCKYDRAW_EXTERN_OTHER
	}
}
