using System;

namespace CSProtocol
{
	public enum CS_RAREEXCHANGE_ERRCODE
	{
		CS_RAREEXCHANGE_ERR_SYS = 1,
		CS_RAREEXCHANGE_ERR_ID,
		CS_RAREEXCHANGE_ERR_OUTDATE,
		CS_RAREEXCHANGE_ERR_DUP,
		CS_RAREEXCHANGE_ERR_LIMIT,
		CS_RAREEXCHANGE_ERR_EXCHANGE,
		CS_RAREEXCHANGE_ERR_STATE
	}
}
