using System;

namespace CSProtocol
{
	public enum CS_RES_DATA_TYPE
	{
		CS_RES_DATA_NULL,
		CS_RES_DATA_WEAL_CHECKIN,
		CS_RES_DATA_WEAL_FILLINPRICE,
		CS_RES_DATA_WEAL_FIXEDTIME,
		CS_RES_DATA_WEAL_MULTIPLE,
		CS_RES_DATA_WEAL_CONDITION,
		CS_RES_DATA_WEAL_TEXT,
		CS_RES_DATA_RANDOM_REWARD,
		CS_RES_DATA_PVP_DAILY_RATIO,
		CS_RES_DATA_SPEC_SALE,
		CS_RES_DATA_HERO_PROMOTION,
		CS_RES_DATA_SKIN_PROMOTION,
		CS_RES_DATA_LUCKYDRAW_PRICE,
		CS_RES_DATA_LUCKYDRAW_REWARD,
		CS_RES_DATA_LUCKYDRAW_EXTERNREWARD,
		CS_RES_DATA_SALE_RECOMMEND = 17,
		CS_RES_DATA_RAND_DRAW,
		CS_RES_DATA_REWARDPOOL,
		CS_RES_DATA_REDDOTTIPINFO,
		CS_RES_DATA_HEROSHOP,
		CS_RES_DATA_HEROSKINSHOP,
		CS_RES_DATA_WEAL_EXCHANGE,
		CS_RES_DATA_PVP_SPECITEM,
		CS_RES_DATA_REWARDMATCH_TIME,
		CS_RES_DATA_HUOYUEDU_REWARD,
		CS_RES_DATA_BOUTIQUE,
		CS_RES_DATA_HEADIMAGE,
		CS_RES_DATA_SRV2CLT_GLOBAL_CONF,
		CS_RES_DATA_BANNERIMAGE,
		CS_RES_DATA_REWARDMATCH,
		CS_RES_DATA_SHOPPROMOTION,
		CS_RES_DATA_PROP,
		CS_RES_DATA_WEAL_PTEXCHANGE,
		CS_RES_DATA_RANK_SEASON,
		CS_RES_DATA_RAREEXCHANGE,
		CS_RES_DATA_WEAL_PARAM,
		CS_RES_DATA_MAX
	}
}
