using System;

namespace CSProtocol
{
	public enum CS_SKILLUPDATE_ERR
	{
		CS_SKILLUPDATE_SUCC,
		CS_SKILLUPDATE_INVALIDSLOT,
		CS_SKILLUPDATE_UNLOCK,
		CS_SKILLUPDATE_LVLFULL,
		CS_SKILLUPDATE_NOGOLD,
		CS_SKILLUPDATE_NOPOINT,
		CS_SKILLUPDATE_OTHER
	}
}
