using System;

namespace CSProtocol
{
	public enum LIST_FRIEND_RSP_PACKET_TYPE
	{
		LIST_FRIEND_RSP_PACKET_TYPE_NORMAL = 1,
		LIST_FRIEND_RSP_PACKET_TYPE_LAST,
		LIST_FRIEND_RSP_PACKET_TYPE_CLT_ASK
	}
}
