using System;

public enum NewbieGuideTriggerTimeType
{
	enterHall = 1,
	enterBattle,
	preNewbieGuideComplete,
	battleFin,
	equipSuccess,
	shoppingSuccess,
	lotterySuccess,
	enterBattleHeroSel,
	newbieTalent,
	newbiePvPTalent,
	enterPvpEntry,
	enterPveEntry,
	newbiePvPDragonBuff,
	pvpFin,
	timeForOpSetting,
	heroSelectedForBattle,
	getSymbolReward,
	newbieTalentSecondTime = 20,
	timeForNewbieSwitchingCaptain,
	onTalentLevelChange,
	onEnterTaskForm,
	onEnterExploreForm,
	onEnterSymbolForm,
	preNewBieWeakGuideStepComplete,
	preNewBieWeakGuideComleteAll,
	PvPShareFin,
	PvPShowKDA,
	onBuyFirstEquip,
	onHasEnoughMoneyButEquip,
	onMiniMapSignGuide,
	onJungleEquipGuide,
	onClick3v3AI,
	onClick55Team,
	onClick33Team,
	onEntryTrainLevelEntry,
	onEuipShopGuide,
	onOpenMatchingConfirmBox,
	onEnterCustomRecommendEquip,
	onClickFireMatch,
	onSetLockOrFreeTargetType,
	onBattleStart,
	onHostFirstDead,
	onEnterMishu,
	onClickGloryPoints,
	onEntryMallSymbolMake,
	onHostPlayerLowHp,
	onHostPlayerHitByTower,
	onClickBattleInfoBtn,
	onEnterArena,
	onEnterBurn
}
