using System;

public enum NewbieGuideScriptType
{
	clickAnyWhereScreen = 12,
	clickWaiting = 31,
	openForm,
	clickTrialBtn = 52,
	clickZhuangziBtn,
	clickBurningBtn,
	clickEliteBtn,
	clickGuildBtn,
	clickNewbieDragonIcon = 65,
	clickBuyEquip = 71,
	clickFocus,
	clickAttack,
	clickDefense,
	clickGather,
	clickVoice,
	clickMap,
	clickEquipBuyBtn,
	clickEquipPanel,
	clickJungleSword,
	clickJungleEquipPanel,
	clickEuipPanelClose,
	autoCloseEquipForm,
	bigMapSignGuide,
	selectModeGuide,
	prefabeTextGuide,
	cameraMoveGuide,
	eyeGuide,
	clickBattleInfoBtn,
	clickPvpEntry = 1001,
	clickPveEntry,
	clickExploring,
	clickHallMall = 1100,
	clickBuyOne,
	clickHeroPackage,
	clickMallMenu,
	highLightHeroListArea,
	clickHallNewbie = 1200,
	clickMainTask,
	clickConfirmReward = 1203,
	clickRewardToHall,
	HighlightLevelList,
	HighlightUnlockNode,
	clickGetRewardBtn,
	HighlightLevelTaskNode,
	oldPlayerGrowGuide = 1210,
	clickOneLevel = 1400,
	clickChangeTeam,
	clickBackToHall,
	clickBattleHero,
	clickBattleHeroConfirm,
	clickFullStarAward,
	clickFullStartAwardConfirm,
	clickPvpBackToHall,
	clickChallenge,
	clickChallengeNext,
	clickMoreHero,
	clickTaskFinish,
	clickTournamentDefense,
	closeMoreHeroFolder,
	clickPvPEntryToHall,
	clickAdvSelectToHall,
	clickPvPProfit,
	clickPvpHumanAi = 1500,
	clickPvpHumanAiSingle33,
	clickPvpHuman,
	clickPvpHumanSingle33,
	clickMatching,
	clickPvpHumanAiSingle33Difficulty,
	guide5v5Confirm,
	clickPvpHuman11,
	clickTrain = 1510,
	clickTrain55,
	clickTrainWheelDisc,
	guide3v3Confirm,
	clickTrain33,
	oldPlayerGuide5v5Confirm,
	clickTrainLevelBack,
	clickPvpHuman55,
	clickMatchingConfirm,
	introfireMatch,
	clickHonorMall = 1600,
	clickMsgBox = 1900,
	clickTournament = 2000,
	clickChallenging,
	clickHallSymbolBtn = 2100,
	clickSymbolSlot,
	clickSymbol,
	clickPvEBackToHall,
	clickGetSymbol,
	clickSymbolRewardBack,
	clickCloseSymbolIntro,
	clickSymbolManufacture,
	clickSymbolEquip,
	clickSymbolSpecific,
	clickHeroSymbolPage,
	pickSymbolManufacture,
	clickSymbolManufactureConfirm,
	clickSymbolLottery,
	clickSymbolLotteryBack,
	clickBattleHeroAddedSkillSwitch,
	clickAddedSkillForBattle,
	clickAddedSkillArrow,
	clickAddedSkillConfirm,
	clickHeroSkill,
	clickCombat3v3 = 2200,
	clickSymbolmenu,
	clickSymbolBuy,
	SymbolBagClickSymbol,
	clickSymbolBuyClose,
	clickSettingMenu = 3000,
	clickSettingOp,
	clickAutoCasting,
	clickCadCasting,
	clickAttackNearest,
	clickAttackWeakest,
	clickCloseSettingMenu,
	clickCaptainButton,
	clickCommonAttackType1,
	clickCommonAttackType2,
	clickPlayerSkillBtn = 4000,
	introGloryPoints = 4101,
	showImageGuide = 4201
}
