using System;

public enum NewbieGuideSkipConditionType
{
	Invalid,
	hasCompleteDungeon,
	hasCompleteNewbieGuide,
	hasCompleteEquipping,
	hasRewardTaskPvp,
	hasCompleteHeroAdv,
	hasSummonedHero,
	hasOverThreeHeroes,
	hasCompleteHeroStar,
	hasHeroSkillUpgraded,
	hasBoughtHero = 11,
	hasBoughtItem,
	hasGotChapterReward,
	hasMopup,
	hasEnteredPvP,
	hasEnteredTrial,
	hasEnteredZhuangzi,
	hasEnteredBurning,
	hasEnteredElitePvE,
	hasEnteredGuild,
	hasUsedSymbol,
	hasEnteredMysteryShop,
	hasAdvancedEquip,
	hasCompleteBaseGuide,
	hasCompleteNewbieArchive = 30,
	hasCompleteHumanAi33Match,
	hasCompleteHuman33Match,
	hasComplete33Guide,
	hasCompleteLottery,
	hasIncreaseEquip,
	hasRewardTaskPve,
	hasCompleteHeroUp,
	hasEnteredTournament,
	hasCompleteHumanAi33 = 40,
	hasManufacuredSymbol,
	hasEnoughSymbolOf,
	hasCoinDrawFive,
	hasCompleteWeakNewbieArchive,
	hasCompleteTrainLevel55,
	hasComplete11Match,
	hasCompleteTrainLevel33,
	hasDiamondDraw,
	hasCompleteFirst55Warm,
	hasCompleteCoronaGuide = 51
}
