using System;

namespace ResData
{
	public enum RES_PERREQUISITE_TYPE
	{
		RES_PERREQUISITE_NULL,
		RES_PERREQUISITE_STAGECLEARPVP,
		RES_PERREQUISITE_STAGECLEARPVE,
		RES_PERREQUISITE_ACNTLVL,
		RES_PERREQUISITE_HEROOPT,
		RES_PERREQUISITE_GRADEOFRANKTO,
		RES_PERREQUISITE_FRIENDCNT,
		RES_PERREQUISITE_SKILLLVLUP,
		RES_PERREQUISITE_OPENBOXCNT,
		RES_PERREQUISITE_BUYGOLD,
		RES_PERREQUISITE_ACTIVITY,
		RES_PERREQUISITE_ARENA,
		RES_PERREQUISITE_SYMBOLCOMP,
		RES_PERREQUISITE_PVPLVL,
		RES_PERREQUISITE_GEARLVLUP,
		RES_PERREQUISITE_GEARADVANCE,
		RES_PERREQUISITE_PVPKILLCNT,
		RES_PERREQUISITE_GUILDOPT,
		RES_PERREQUISITE_BUYOPT,
		RES_PERREQUISITE_CLIENTREPORT,
		RES_PERREQUISITE_ARENAOPT,
		RES_PERREQUISITE_LASTSTAGECLRPVP,
		RES_PERREQUISITE_LASTSTAGECLRPVE,
		RES_PERREQUISITE_PVPSOMECONDITION,
		RES_PERREQUISITE_PVESOMECONDITION,
		RES_PERREQUISITE_LOGIN,
		RES_PERREQUISITE_DUOBAO,
		RES_PERREQUISITE_RECALLFRIEND,
		RES_PERREQUISITE_MONTHWEEKCARD,
		RES_PERREQUISITE_COINCOST,
		RES_PERREQUISITE_MAX
	}
}
