using System;

namespace ResData
{
	public enum RES_FRIENDOPT_TYPE
	{
		RES_FRIENDOPT_HAVENUM = 1,
		RES_FRIENDOPT_SENDADDREQ,
		RES_FRIENDOPT_REALADD = 4,
		RES_FRIENDOPT_BAISHI = 8,
		RES_FRIENDOPT_SHOUTU = 16
	}
}
