using System;

namespace ResData
{
	public enum RES_WEAL_CONTENTSHARE_TYPE
	{
		RES_WEAL_CONTENTSHARE_SHAREBATTLERET = 1,
		RES_WEAL_CONTENTSHARE_SHAREWEAL,
		RES_WEAL_CONTENTSHARE_SHAREGETHEROORSKIN
	}
}
