using System;

namespace ResData
{
	public enum RES_SYMBOL_TYPE
	{
		RES_SYMBOL_TYPE_ATTACK = 1,
		RES_SYMBOL_TYPE_HP,
		RES_SYMBOL_TYPE_DEFENSE,
		RES_SYMBOL_TYPE_FUNCTION,
		RES_SYMBOL_TYPE_SUCKBLOOD,
		RES_SYMBOL_TYPE_ATKSPEED,
		RES_SYMBOL_TYPE_CRIT,
		RES_SYMBOL_TYPE_PENETRATE
	}
}
