using System;

namespace ResData
{
	public enum RES_WEAL_GAME_TYPE
	{
		RES_WEAL_GAME_NULL,
		RES_WEAL_GAME_ADVENTURE,
		RES_WEAL_GAME_COMBAT,
		RES_WEAL_GAME_GUIDE,
		RES_WEAL_GAME_ACTIVITY,
		RES_WEAL_GAME_LADDER,
		RES_WEAL_GAME_PVP_MATCH,
		RES_WEAL_GAME_PVP_ROOM,
		RES_WEAL_GAME_BURNING,
		RES_WEAL_GAME_ARENA,
		RES_WEAL_GAME_ENTERTAINMENT,
		RES_WEAL_GAME_REWARDMATCH,
		RES_WEAL_GAME_MAX
	}
}
