using System;

namespace ResData
{
	public enum RES_RANDOM_REWARD_INIT_HERO_LIMIT
	{
		RES_RANDOM_REWARD_INIT_HERO_LIMIT_NULL,
		RES_RANDOM_REWARD_INIT_HERO_LIMIT_LIANPO = 105,
		RES_RANDOM_REWARD_INIT_HERO_LIMIT_XIAOQIAO,
		RES_RANDOM_REWARD_INIT_HERO_LIMIT_ZHAOYUN
	}
}
