using System;

namespace ResData
{
	public enum RES_STATISTIC_TYPE
	{
		RES_STATISTIC_TYPE_NULL,
		RES_STATISTIC_TYPE_KILL,
		RES_STATISTIC_TYPE_ATTR,
		RES_STATISTIC_TYPE_SPECIAL,
		RES_STATISTIC_TYPE_SETTLE,
		RES_STATISTIC_TYPE_MAX
	}
}
