using System;

namespace ResData
{
	public enum RES_ACHIEVE_TYPE
	{
		RES_ACHIEVE_GROWING = 1,
		RES_ACHIEVE_HERO,
		RES_ACHIEVE_PVP,
		RES_ACHIEVE_PVE,
		RES_ACHIEVE_SOCIALLY,
		RES_ACHIEVE_RANK,
		RES_ACHIEVE_TYPE_MAX
	}
}
