using System;

namespace ResData
{
	public enum RES_BATTLE_MAP_TYPE
	{
		RES_BATTLE_MAP_TYPE_VERSUS = 1,
		RES_BATTLE_MAP_TYPE_COUNTERPART,
		RES_BATTLE_MAP_TYPE_RANK,
		RES_BATTLE_MAP_TYPE_ENTERTAINMENT,
		RES_BATTLE_MAP_TYPE_REWARDMATCH,
		RES_BATTLE_MAP_TYPE_GUILDMATCH,
		RES_BATTLE_MAP_TYPE_NUM
	}
}
