using System;

namespace ResData
{
	public enum RES_BUYRES_RULETYPE
	{
		RES_BUYRES_RULE_NORMAL,
		RES_BUYRES_RULE_ATTRORDER,
		RES_BUYRES_RULE_TOTALORDER,
		RES_BUYRES_RULE_CYCLE,
		RES_BUYRES_RULE_MAX
	}
}
