using System;

namespace ResData
{
	public enum RES_PROP_TYPE_TYPE
	{
		RES_PROP_TYPE_COMMON,
		RES_PROP_TYPE_VALCHG,
		RES_PROP_TYPE_EQUIPCOMP,
		RES_PROP_TYPE_HEROCOMP,
		RES_PROP_TYPE_GIFTS,
		RES_PROP_TYPE_HEROSTAR,
		RES_PROP_TYPE_SWEEP,
		RES_PROP_TYPE_MONTHWEEK_CARD,
		RES_PROP_TYPE_TICKET,
		RES_PROP_TYPE_HORN,
		RES_PROP_TYPE_EXPCARD,
		RES_PROP_TYPE_BATTLERECORD_CARD,
		RES_PROP_TYPE_POPUP,
		RES_PROP_TYPE_MAX
	}
}
