using System;

namespace ResData
{
	public enum RES_SHOPBUY_TYPE
	{
		RES_BUYTYPE_COINDRAW = 1,
		RES_BUYTYPE_DRAWHERO,
		RES_BUYTYPE_DRAWSKIN,
		RES_BUYTYPE_APBUY,
		RES_BUYTYPE_SPBUY,
		RES_BUYTYPE_LVLCHALLENGE,
		RES_BUYTYPE_SYMBOLPAGE,
		RES_BUYTYPE_OPENBOXBYCOUPONS,
		RES_BUYTYPE_ARENACHALLENGECNT,
		RES_BUYTYPE_DRAWSYMBOLCOMMON,
		RES_BUYTYPE_DRAWSYMBOLSENIOR,
		RES_BUYTYPE_SYMBOLPAGEPOS,
		RES_BUYTYPE_ENTERTAINMENTRANDHERO,
		RES_BUYTYPE_MAX
	}
}
