using System;

namespace ResData
{
	public enum RES_SOLDIER_TYPE
	{
		RES_SOLDIER_TYPE_OTHERS,
		RES_SOLDIER_TYPE_MELEE,
		RES_SOLDIER_TYPE_REMOTE,
		RES_SOLDIER_TYPE_SUPER,
		RES_SOLDIER_TYPE_ANYINGDAJIANG,
		RES_SOLDIER_TYPE_HEIANXIANFENG,
		RES_SOLDIER_TYPE_BAOZOUJIANGSHI,
		RES_SOLDIER_TYPE_BAOJUN,
		RES_SOLDIER_TYPE_BARON,
		RES_SOLDIER_TYPE_BIGDRAGON,
		RES_SOLDIER_TYPE_BLUEBA,
		RES_SOLDIER_TYPE_REDBA,
		RES_SOLDIER_TYPE_JIANGSHICHANGMAOSHOU,
		RES_SOLDIER_TYPE_FireHole,
		RES_SOLDIER_TYPE_MONEYBA,
		RES_SOLDIER_TYPE_RUNAWAYCAT,
		RES_SOLDIER_TYPE_DOMINATE_VANGUARD
	}
}
