using System;

namespace ResData
{
	public enum RES_SHOPBUY_COINTYPE
	{
		RES_SHOPBUY_TYPE_NULL,
		RES_SHOPBUY_TYPE_COUPONS = 2,
		RES_SHOPBUY_TYPE_ENCHANTPT,
		RES_SHOPBUY_TYPE_PVPCOIN,
		RES_SHOPBUY_TYPE_BURNINGCOIN,
		RES_SHOPBUY_TYPE_ARENACOIN,
		RES_SHOPBUY_TYPE_SKINCOIN,
		RES_SHOPBUY_TYPE_GUILDCOIN,
		RES_SHOPBUY_TYPE_SYMBOLCOIN,
		RES_SHOPBUY_TYPE_DIAMOND,
		RES_SHOPBUY_TYPE_MIXPAY,
		RES_SHOPBUY_TYPE_SCORE,
		RES_SHOPBUY_TYPE_MAX
	}
}
