using System;

namespace ResData
{
	public enum RES_SKILL_SRC_TYPE
	{
		RES_SKILL_SRC_DRAGON_ONE = 1,
		RES_SKILL_SRC_DRAGON_TWO,
		RES_SKILL_SRC_DRAGON_THREE,
		RES_SKILL_SRC_BIG_DRAGON,
		RES_SKILL_SRC_DRAGON_MAX
	}
}
