using System;

namespace ResData
{
	public enum RES_CHGCREDIT_CONFIG
	{
		RES_CHGCREDIT_CHECKWAR_COMPLAINT = 1,
		RES_GHGCREDIT_CHECKWAR_SETTLE,
		RES_CHGCREDIT_CHECKGROW_COMPLAINT,
		RES_CHGCREDIT_CHECKGROW_SETTLE,
		RES_CHGCREDIT_CHECKKDA_COMPLAINT,
		RES_CHGCREDIT_CHECKKDA_SETTLE,
		RES_CHGCREDIT_CHECKDAMAGE_COMPLAINT,
		RES_CHGCREDIT_CHECKDAMAGE_SETTLE,
		RES_CHGCREDIT_COMPLAINT,
		RES_CHGCREDIT_SETTLE_DEL,
		RES_CHGCREDIT_SETTLE_ADD,
		RES_CHGCREDIT_CHECKNOPASS,
		RES_CHGCREDIT_UNCONFIRM,
		RES_CHGCREDIT_HANGUPRATIO,
		RES_CHGCREDIT_OUTGAME,
		RES_CHGCREDIT_NOAI,
		RES_CHGCREDIT_SAFETIME
	}
}
