using System;

namespace ResData
{
	public enum RES_RECRUIMENT_BITS
	{
		RES_RECRUIMENT_BITS_NONE,
		RES_RECRUIMENT_BITS_ONE,
		RES_RECRUIMENT_BITS_TWO,
		RES_RECRUIMENT_BITS_THREE,
		RES_RECRUIMENT_BITS_FOUR,
		RES_RECRUIMENT_BITS_SUPER
	}
}
