using System;

namespace ResData
{
	public enum RES_SHOP_TYPE
	{
		RES_SHOPTYPE_NULL,
		RES_SHOPTYPE_FIXED,
		RES_SHOPTYPE_MYSTERY,
		RES_SHOPTYPE_PVPSYMBOL,
		RES_SHOPTYPE_BURNING,
		RES_SHOPTYPE_ARENA,
		RES_SHOPTYPE_GUILD,
		RES_SHOPTYPE_GUILD_HEAD_IMAGE,
		RES_SHOPTYPE_MAX
	}
}
