using System;

namespace ResData
{
	public enum RES_GUILD_BUILDING_TYPE
	{
		RES_GUILD_BUILDING_TYPE_HALL = 1,
		RES_GUILD_BUILDING_TYPE_BARRACK,
		RES_GUILD_BUILDING_TYPE_FACTORY,
		RES_GUILD_BUILDING_TYPE_STATUE,
		RES_GUILD_BUILDING_TYPE_SHOP
	}
}
