using System;

namespace TMPro
{
	public enum FontStyles
	{
		Normal,
		Bold,
		Italic,
		Underline = 4,
		LowerCase = 8,
		UpperCase = 16,
		SmallCaps = 32,
		Strikethrough = 64,
		BoldItalic = 3,
		BoldUnderline = 5,
		BoldItalicUnderline = 7,
		BoldStrikethrough = 65,
		BoldItalicStrikethrough = 67,
		BoldUnderlineStrikethrough = 69,
		BoldItalicUnderlineStrikethrough = 71,
		ItalicUnderline = 6,
		ItalicStrikethrough = 66,
		ItalicUnderlineStrikethrough = 70,
		LowerCaseBold = 9,
		LowerCaseItalic,
		LowerCaseUnderline = 12,
		LowerCaseStrikethrough = 72,
		LowerCaseBoldItalic = 11,
		LowerCaseBoldUnderline = 13,
		LowerCaseBoldStrikethrough = 73,
		LowerCaseItalicStrikethrough,
		LowerCaseBoldItalicStrikethrough,
		LowerCaseBoldUnderlineStrikethrough = 77,
		LowerCaseBoldItalicUnderline = 15,
		LowerCaseBoldItalicUnderlineStrikethrough = 79,
		UpperCaseBold = 17,
		UpperCaseItalic,
		UpperCaseUnderline = 20,
		UpperCaseStrikethrough = 80,
		UpperCaseBoldItalic = 19,
		UpperCaseBoldUnderline = 21,
		UpperCaseBoldStrikethrough = 81,
		UpperCaseItalicStrikethrough,
		UpperCaseBoldItalicStrikethrough,
		UpperCaseBoldUnderlineStrikethrough = 85,
		UpperCaseBoltItalicUnderline = 23,
		UpperCaseBoldItalicUnderlineStrikethrough = 87,
		SmallCapsBold = 33,
		SmallCapsItalic,
		SmallCapsUnderline = 36,
		SmallCapsStrikethrough = 96,
		SmallCapsBoldItalic = 35,
		SmallCapsBoldUnderline = 37,
		SmallCapsBoldStrikethrough = 97,
		SmallCapsItalicStrikethrough,
		SmallCapsBoldItalicStrikethrough,
		SmallCapsBoldUnderlineStrikethrough = 101,
		SmallCapsBoldItalicUnderline = 39,
		SmallCapsBoldItalicUnderlineStrikethrough = 103
	}
}
