using System;

namespace ResData
{
	public enum RES_DAMAGE_EFFECT_CONDITION_TYPE
	{
		RES_DAMAGE_EFFECT_CONDITION_NONE,
		RES_DAMAGE_EFFECT_CONDITION_REVIVE_HPRATE,
		RES_DAMAGE_EFFECT_CONDITION_ADD_DAMAGE_DISTANCE
	}
}
