using System;

namespace ResData
{
	public enum RES_WEAL_TIME_TYPE
	{
		RES_WEAL_TIME_TYPE_LIMIT,
		RES_WEAL_TIME_TYPE_FOREVER,
		RES_WEAL_TIME_TYPE_REGISTER_LIMIT,
		RES_WEAL_TIME_TYPE_REGISTER_DAYS,
		RES_WEAL_TIME_TYPE_MAX
	}
}
