using System;

namespace ResData
{
	public enum RES_PROP_CLASS_TYPE
	{
		RES_PROP_CLASS_NULL,
		RES_PROP_CLASS_COMSUME,
		RES_PROP_CLASS_FRAGMENT,
		RES_PROP_CLASS_SOULSTONE,
		RES_PROP_CLASS_OTHER
	}
}
