using System;

namespace ResData
{
	public enum RES_LUCKYDRAW_ITEMTAG
	{
		RES_LUCKYDRAW_ITEMTAG_NONE,
		RES_LUCKYDRAW_ITEMTAG_UNUSUAL,
		RES_LUCKYDRAW_ITEMTAG_NEW,
		RES_LUCKYDRAW_ITEMTAG_HOT,
		RES_LUCKYDRAW_ITEMTAG_DISCOUNT
	}
}
