using System;

namespace ResData
{
	public enum RES_MAINTASK_SUBTYPE
	{
		RES_MAINTASK_SUBTYPE_LEVEL,
		RES_MAINTASK_SUBTYPE_PVE,
		RES_MAINTASK_SUBTYPE_PVP,
		RES_MAINTASK_SUBTYPE_SHIFU,
		RES_MAINTASK_SUBTYPE_TUDI
	}
}
