using System;

namespace ResData
{
	public enum RES_LEVEL_HEROAITYPE
	{
		RES_LEVEL_HEROAITYPE_NULL,
		RES_LEVEL_HEROAITYPE_CAPTAIN,
		RES_LEVEL_HEROAITYPE_FREEDOM,
		RES_LEVEL_HEROAITYPE_DEFEND,
		RES_LEVEL_HEROAITYPE_3V3,
		RES_LEVEL_HEROAITYPE_MELEE,
		RES_LEVEL_HEROAITYPE_FIREPIT
	}
}
