using System;

namespace ResData
{
	public enum RES_PVP_ACHIEVEMENT_MULTI_KILL_TYPE
	{
		RES_STAR_CONDITION_ACHIEVEMENT_ASSIST,
		RES_STAR_CONDITION_ACHIEVEMENT_FIRST_KILL,
		RES_STAR_CONDITION_ACHIEVEMENT_KILL,
		RES_STAR_CONDITION_ACHIEVEMENT_DOUBLE_KILL,
		RES_STAR_CONDITION_ACHIEVEMENT_TRIPLE_KILL,
		RES_STAR_CONDITION_ACHIEVEMENT_QUATARY_KILL,
		RES_STAR_CONDITION_ACHIEVEMENT_PENTA_KILL,
		RES_STAR_CONDITION_ACHIEVEMENT_MONSTER_KILL = 11,
		RES_STAR_CONDITION_ACHIEVEMENT_DOMINATE_BATTLE,
		RES_STAR_CONDITION_ACHIEVEMENT_LEGENDARY,
		RES_STAR_CONDITION_ACHIEVEMENT_TOTAL_ANNIHILAT,
		RES_STAR_CONDITION_ACHIEVEMENT_ODYSSEY
	}
}
