using System;

namespace ResData
{
	public enum RES_PROP_VALFUNC_TYPE
	{
		RES_PROP_VALFUNC_EXP = 1,
		RES_PROP_VALFUNC_MULTIPLE_EXP,
		RES_PROP_VALFUNC_MULTIPLE_COIN,
		RES_PROP_VALFUNC_HERO_EXPERIENCE,
		RES_PROP_VALFUNC_SKIN_EXPERIENCE,
		RES_PROP_VALFUNC_PLAYER_NAMECHANGE,
		RES_PROP_VALFUNC_GUILD_NAMECHANGE,
		RES_PROP_VALFUNC_MONTH_CARD,
		RES_PROP_VALFUNC_WEEK_CARD
	}
}
