using System;

namespace ResData
{
	public enum RES_SPECIALFUNCUNLOCK_TYPE
	{
		RES_SPECIALFUNCUNLOCKTYPE_NONE,
		RES_SPECIALFUNCUNLOCKTYPE_SKILLLEVELUP,
		RES_SPECIALFUNCUNLOCKTYPE_SINGLEBATACTIVITY,
		RES_SPECIALFUNCUNLOCKTYPE_ZONGSHILIAN,
		RES_SPECIALFUNCUNLOCKTYPE_LIUGUOYUANZHENG,
		RES_SPECIALFUNCUNLOCKTYPE_ZHUANGZIHUANMENG,
		RES_SPECIALFUNCUNLOCKTYPE_ELITELEVEL,
		RES_SPECIALFUNCUNLOCKTYPE_SAODANG,
		RES_SPECIALFUNCUNLOCKTYPE_SYMBOL,
		RES_SPECIALFUNCUNLOCKTYPE_ARENA,
		RES_SPECIALFUNCUNLOCKTYPE_PVPMODE,
		RES_SPECIALFUNCUNLOCKTYPE_BLACKSHOP,
		RES_SPECIALFUNCUNLOCKTYPE_SHOP,
		RES_SPECIALFUNCUNLOCKTYPE_UNION,
		RES_SPECIALFUNCUNLOCKTYPE_SYMBOLSHOP,
		RES_SPECIALFUNCUNLOCKTYPE_PVPCOINSHOP,
		RES_SPECIALFUNCUNLOCKTYPE_TASK,
		RES_SPECIALFUNCUNLOCKTYPE_GUILDSHOP,
		RES_SPECIALFUNCUNLOCKTYPE_HERO,
		RES_SPECIALFUNCUNLOCKTYPE_BAG,
		RES_SPECIALFUNCUNLOCKTYPE_FRIEND,
		RES_SPECIALFUNCUNLOCKTYPE_PVPRANK,
		RES_SPECIALFUNCUNLOCKTYPE_ADDEDSKILL,
		RES_SPECIALFUNCUNLOCKTYPE_CHAT,
		RES_SPECIALFUNCUNLOCKTYPE_TRIANING_JUNGLE,
		RES_SPECIALFUNCUNLOCKTYPE_ENTERTAINMENT,
		RES_SPECIALFUNCUNLOCKTYPE_PRESENTHERO,
		RES_SPECIALFUNCUNLOCKTYPE_REWARDMATCH,
		RES_SPECIALFUNCUNLOCKTYPE_ACHIEVEMENT,
		RES_SPECIALFUNCUNLOCKTYPE_MAX
	}
}
