using System;

namespace ResData
{
	public enum RES_VOICE_INTERFACTION_TRIGGER_TYPE
	{
		RES_VOICE_INTERFACTION_TRIGGER_TYPE_KILL_HERO,
		RES_VOICE_INTERFACTION_TRIGGER_TYPE_BE_KILLED,
		RES_VOICE_INTERFACTION_TRIGGER_TYPE_ENCOUNTER_ALLIES,
		RES_VOICE_INTERFACTION_TRIGGER_TYPE_ENCOUNTER_ENEMY,
		RES_VOICE_INTERFACTION_TRIGGER_TYPE_ACHIEVEMENT
	}
}
