using System;

namespace ResData
{
	public enum RES_MATCH_WEEKDAY
	{
		RES_MATCH_WEEK_SUNDAY = 1,
		RES_MATCH_WEEK_MON,
		RES_MATCH_WEEK_TUES,
		RES_MATCH_WEEK_WED,
		RES_MATCH_WEEK_THURS,
		RES_MATCH_WEEK_FRI,
		RES_MATCH_WEEK_SATUR
	}
}
