using System;

namespace ResData
{
	public enum RES_HERO_RECOMMEND_POSITION
	{
		RES_HERO_RECOMMEND_POSITION_T_FRONT,
		RES_HERO_RECOMMEND_POSITION_T_CENTER,
		RES_HERO_RECOMMEND_POSITION_T_TAIL
	}
}
