using System;

namespace ResData
{
	public enum RES_SHOW_ACHIEVEMENT_TYPE
	{
		RES_SHOW_ACHIEVEMENT_FIFTEENVICTORY,
		RES_SHOW_ACHIEVEMENT_PENTAKILL,
		RES_SHOW_ACHIEVEMENT_TENVICTORY,
		RES_SHOW_ACHIEVEMENT_QUATARYKILL,
		RES_SHOW_ACHIEVEMENT_FIVEVICTORY,
		RES_SHOW_ACHIEVEMENT_LEGENDARY,
		RES_SHOW_ACHIEVEMENT_TRIPLEKILL,
		RES_SHOW_ACHIEVEMENT_MVP,
		RES_SHOW_ACHIEVEMENT_COUNT
	}
}
