using System;

namespace ResData
{
	public enum RES_RANK_BIG_GRADE
	{
		RES_RANK_BIG_GRADE_OF_QINGTONG = 1,
		RES_RANK_BIG_GRADE_OF_BAIYIN,
		RES_RANK_BIG_GRADE_OF_HUANGJIN,
		RES_RANK_BIG_GRADE_OF_BOJIN,
		RES_RANK_BIG_GRADE_OF_ZUANSHI,
		RES_RANK_BIG_GRADE_OF_WANGZHE
	}
}
