using System;

namespace ResData
{
	public enum RES_LEVEL_DIFFICULTY_TYPE
	{
		RES_LEVEL_DIFFICULTY_TYPE_NULL,
		RES_LEVEL_DIFFICULTY_TYPE_NORMAL,
		RES_LEVEL_DIFFICULTY_TYPE_NIGHTMARE,
		RES_LEVEL_DIFFICULTY_TYPE_MASTER,
		RES_LEVEL_DIFFICULTY_TYPE_ABYSS,
		RES_LEVEL_DIFFICULTY_TYPE_MAX
	}
}
