using System;

namespace ResData
{
	public enum RES_INTIMACY_TYPE
	{
		RES_INTIMACY_NONE,
		RES_INTIMACY_PVP,
		RES_INTIMACY_LADDER,
		RES_INTIMACY_HEROANDSKIN,
		RES_INTIMACY_DONATE,
		RES_RECRUITMENT,
		RES_INTIMACY_MAX
	}
}
