using System;

namespace ResData
{
	public enum RES_INCOME_ATTACKER_TYPE
	{
		RES_INCOME_ATTACKER_ALL = 1,
		RES_INCOME_ATTACKER_ORGAN,
		RES_INCOME_ATTACKER_SOLDIER,
		RES_INCOME_ATTACKER_HERO,
		RES_INCOME_ATTACKER_MONSTER
	}
}
