using System;

namespace ResData
{
	public enum RES_UNLOCKCONDITION_TYPE
	{
		RES_UNLOCKCONDITIONTYPE_NONE,
		RES_UNLOCKCONDITIONTYPE_ABOVELEVEL,
		RES_UNLOCKCONDITIONTYPE_PASSSOMELEVEL,
		RES_UNLOCKCONDITIONTYPE_FIRSTLOGIN,
		RES_UNLOCKCONDITIONTYPE_PVPPROGRESS,
		RES_UNLOCKCONDITIONTYPE_MAX
	}
}
