using System;

namespace ResData
{
	public enum RES_FUNCEFT_TYPE
	{
		RES_FUNCEFT_NONE,
		RES_FUNCEFT_PHYATKPT,
		RES_FUNCEFT_MGCATKPT,
		RES_FUNCEFT_PHYDEFPT,
		RES_FUNCEFT_MGCDEFPT,
		RES_FUNCEFT_MAXHP,
		RES_FUNCEFT_CRITRATE,
		RES_FUNCEFT_PHYARMORHURT,
		RES_FUNCEFT_MGCARMORHURT,
		RES_FUNCEFT_PHYVAMP,
		RES_FUNCEFT_MGCVAMP,
		RES_FUNCEFT_ANTICRIT,
		RES_FUNCEFT_CRITEFT,
		RES_FUNCEFT_REALHURT,
		RES_FUNCEFT_REALHURTLESS,
		RES_FUNCEFT_MOVESPD,
		RES_FUNCEFT_HPRECOVER,
		RES_FUNCEFT_CTRLREDUCE,
		RES_FUNCEFT_ATKSPDADD,
		RES_FUNCEFT_BASEHURTADD,
		RES_FUNCEFT_CDREDUCE,
		RES_FUNCEFT_SightArea,
		RES_FUNCEFT_HitRate,
		RES_FUNCEFT_HitRateAvoid,
		RES_PROPERTY_CRITICAL,
		RES_PROPERTY_REDUCECRITICAL,
		RES_PROPERTY_PHYSICSHEM,
		RES_PROPERTY_MAGICHEM,
		RES_PROPERTY_ATTACKSPEED,
		RES_PROPERTY_TENACITY,
		RES_PROPERTY_HURTREDUCERATE,
		RES_PROPERTY_HURTOUTPUTRATE,
		RES_PROPERTY_MAXEP,
		RES_PROPERTY_EPRECOVER,
		RES_PROPERTY_PHYARMORHURT_RATE,
		RES_PROPERTY_MGCARMORHURT_RATE,
		RES_PROPERTY_RECOVERYGAINEFFECT,
		RES_FUNCEFT_VALUE_MAX
	}
}
