using System;

namespace ResData
{
	public enum RES_MULTI_GAME_PICK_RULE
	{
		RES_MULTI_GAME_PICK_RULE_NORMAL,
		RES_MULTI_GAME_PICK_RULE_RANDOM,
		RES_MULTI_GAME_PICK_RULE_CLONE,
		RES_MULTI_GAME_PICK_RULE_BANPICK,
		RES_MULTI_GAME_PICK_RULE_MULTI
	}
}
