using System;

namespace ResData
{
	public enum RES_STAR_CONDITION_EXT_TYPE
	{
		RES_STAR_CONDITION_CLEAR_STAT = 1,
		RES_STAR_CONDITION_HEALTH_STAT,
		RES_STAR_CONDITION_DEATH_STAT,
		RES_STAR_CONDITION_RESTRICT_HERO,
		RES_STAR_CONDITION_PVP_KILL_ALL_ENEMY = 6,
		RES_STAR_CONDITION_DATA_STAT,
		RES_STAR_CONDITION_TIME_LIMIT_STAT,
		RES_STAR_CONDITION_CLEARANCE_RESTRICT_CAREER_TYPE,
		RES_STAR_CONDITION_CLEARANCE_TEAM_COUNT,
		RES_STAR_CONDITION_CLEARANCE_TIME_LIMIT,
		RES_STAR_CONDITION_TEAM_EXTINCTION,
		RES_STAR_CONDITION_PVP_ACHIEVEMENT,
		RES_STAR_CONDITION_CLEARANCE_APPOINT_TIME,
		RES_STAR_CONDITION_MONSTER_TRIGGER,
		RES_STAR_CONDITION_DATA_STAT_TIMER
	}
}
