using System;

namespace ResData
{
	public enum RES_SKILLFUNC_PROTECT_TYPE
	{
		RES_SKILLFUNC_PROTECT_PHYSHURT = 1,
		RES_SKILLFUNC_PROTECT_MAGICHURT,
		RES_SKILLFUNC_PROTECT_ALL,
		RES_SKILLFUNC_PROTECT_ALL_INCLUDE_REALHURT
	}
}
