using System;

namespace ResData
{
	public enum RES_REWARDS_MATCH_TYPE
	{
		RES_REWARD_MATCH_COIN_LOW,
		RES_REWARD_MATCH_COIN_MID,
		RES_REWARD_MATCH_COIN_HIGH,
		RES_REWARD_MATCH_DIAMOND_LOW,
		RES_REWARD_MATCH_DIAMOND_MID,
		RES_REWARD_MATCH_DIAMOND_HIGH,
		RES_REWARD_MATCH_COUPONS_LOW,
		RES_REWARD_MATCH_COUPONS_MID,
		RES_REWARD_MATCH_COUPONS_HIGH
	}
}
