using System;

namespace ResData
{
	public enum RES_SHOPSUBSTORE_TYPE
	{
		RES_SHOPSUBSTORE_EXPITEM = 1,
		RES_SHOPSUBSTORE_HEROFRAG,
		RES_SHOPSUBSTORE_EQUIP,
		RES_SHOPSUBSTORE_EUIPFRAG,
		RES_SHOPSUBSTORE_SYMBOL,
		RES_SHOPSUBSTORE_EQUIPSTUFF,
		RES_SHOPSUBSTORE_HEROSTUFF,
		RES_SHOPSUBSTORE_MAX
	}
}
