using System;

namespace ResData
{
	public enum RES_WEAL_COLORBAR_TYPE
	{
		RES_WEAL_COLORBAR_TYPE_NULL,
		RES_WEAL_COLORBAR_TYPE_HOT,
		RES_WEAL_COLORBAR_TYPE_NOTICE,
		RES_WEAL_COLORBAR_TYPE_NEW,
		RES_WEAL_COLORBAR_TYPE_LIMIT,
		RES_WEAL_COLORBAR_TYPE_DISCOUNT,
		RES_WEAL_COLORBAR_TYPE_PROBABILITY_DOUBLED
	}
}
