using System;

namespace ResData
{
	public enum RES_ITEM_GRADE_TYPE
	{
		RES_ITEM_GRADE_POOR,
		RES_ITEM_GRADE_COMM,
		RES_ITEM_GRADE_FINE,
		RES_ITEM_GRADE_EXCELLENT,
		RES_ITEM_GRADE_EPIC,
		RES_ITEM_GRADE_LEGEND
	}
}
