using System;

namespace behaviac
{
	public static class bt_WrapperAI_Monster_BTMonsterFairy
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("WrapperAI/Monster/BTMonsterFairy");
			bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
			bt.AddPar("uint", "p_targetID", "0", string.Empty);
			bt.AddPar("int", "p_srchRange", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
			bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
			bt.AddPar("uint", "p_CmdID", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("int", "p_skillAttackRange", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_orignalPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("int", "p_pursuitRange", "0", string.Empty);
			bt.AddPar("uint", "p_selfID", "0", string.Empty);
			bt.AddPar("uint", "p_teamTarget", "0", string.Empty);
			bt.AddPar("uint", "p_captainID", "0", string.Empty);
			bt.AddPar("uint", "p_nearstMember", "0", string.Empty);
			bt.AddPar("bool", "p_forceToApproachHero", "false", string.Empty);
			bt.AddPar("uint", "p_terrorMeActor", "0", string.Empty);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			bt.AddChild(sequence);
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node98 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node98();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node.SetId(98);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node31 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node2 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node31();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetId(31);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node2);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node2.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node48 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node3 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node48();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetId(48);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node3);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node3.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node11 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node4 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node11();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node4.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node4.SetId(11);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node4);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node4.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node14 decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node14();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node.SetId(14);
			sequence.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node);
			SelectorLoop selectorLoop = new SelectorLoop();
			selectorLoop.SetClassNameString("SelectorLoop");
			selectorLoop.SetId(1);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node.AddChild(selectorLoop);
			WithPrecondition withPrecondition = new WithPrecondition();
			withPrecondition.SetClassNameString("WithPrecondition");
			withPrecondition.SetId(70);
			selectorLoop.AddChild(withPrecondition);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node71 condition_bt_WrapperAI_Monster_BTMonsterFairy_node = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node71();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node.SetId(71);
			withPrecondition.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node);
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node.HasEvents());
			SelectorLoop selectorLoop2 = new SelectorLoop();
			selectorLoop2.SetClassNameString("SelectorLoop");
			selectorLoop2.SetId(65);
			withPrecondition.AddChild(selectorLoop2);
			WithPrecondition withPrecondition2 = new WithPrecondition();
			withPrecondition2.SetClassNameString("WithPrecondition");
			withPrecondition2.SetId(359);
			selectorLoop2.AddChild(withPrecondition2);
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(363);
			withPrecondition2.AddChild(sequence2);
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node364 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node5 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node364();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node5.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node5.SetId(364);
			sequence2.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node5.HasEvents());
			IfElse ifElse = new IfElse();
			ifElse.SetClassNameString("IfElse");
			ifElse.SetId(365);
			sequence2.AddChild(ifElse);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node361 condition_bt_WrapperAI_Monster_BTMonsterFairy_node2 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node361();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetId(361);
			ifElse.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node2);
			ifElse.SetHasEvents(ifElse.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node2.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node366 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node6 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node366();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node6.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node6.SetId(366);
			ifElse.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node6);
			ifElse.SetHasEvents(ifElse.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node6.HasEvents());
			Noop noop = new Noop();
			noop.SetClassNameString("Noop");
			noop.SetId(367);
			ifElse.AddChild(noop);
			ifElse.SetHasEvents(ifElse.HasEvents() | noop.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | ifElse.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node360 condition_bt_WrapperAI_Monster_BTMonsterFairy_node3 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node360();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetId(360);
			sequence2.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node3.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node557 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node7 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node557();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node7.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node7.SetId(557);
			sequence2.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node7);
			sequence2.SetHasEvents(sequence2.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node7.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node561 action_bt_WrapperAI_Monster_BTMonsterFairy_node = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node561();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node.SetId(561);
			sequence2.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node.HasEvents());
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | sequence2.HasEvents());
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(370);
			withPrecondition2.AddChild(selector);
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(371);
			selector.AddChild(sequence3);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node16 action_bt_WrapperAI_Monster_BTMonsterFairy_node2 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node16();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetId(16);
			sequence3.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node2.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node223 condition_bt_WrapperAI_Monster_BTMonsterFairy_node4 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node223();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node4.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node4.SetId(223);
			sequence3.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node4.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(225);
			sequence3.AddChild(sequence4);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node118 action_bt_WrapperAI_Monster_BTMonsterFairy_node3 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node118();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetId(118);
			sequence4.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node3);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node3.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node227 action_bt_WrapperAI_Monster_BTMonsterFairy_node4 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node227();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node4.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node4.SetId(227);
			sequence4.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node4.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node334 action_bt_WrapperAI_Monster_BTMonsterFairy_node5 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node334();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node5.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node5.SetId(334);
			sequence4.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node5);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node5.HasEvents());
			sequence3.SetHasEvents(sequence3.HasEvents() | sequence4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(386);
			selector.AddChild(sequence5);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node387 condition_bt_WrapperAI_Monster_BTMonsterFairy_node5 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node387();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node5.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node5.SetId(387);
			sequence5.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(388);
			sequence5.AddChild(sequence6);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node389 action_bt_WrapperAI_Monster_BTMonsterFairy_node6 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node389();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node6.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node6.SetId(389);
			sequence6.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node6.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node390 action_bt_WrapperAI_Monster_BTMonsterFairy_node7 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node390();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node7.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node7.SetId(390);
			sequence6.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node7);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node7.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node394 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node8 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node394();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node8.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node8.SetId(394);
			sequence6.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node8);
			sequence6.SetHasEvents(sequence6.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node8.HasEvents());
			sequence5.SetHasEvents(sequence5.HasEvents() | sequence6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(391);
			selector.AddChild(sequence7);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node392 condition_bt_WrapperAI_Monster_BTMonsterFairy_node6 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node392();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node6.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node6.SetId(392);
			sequence7.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node6);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node6.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node393 action_bt_WrapperAI_Monster_BTMonsterFairy_node8 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node393();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node8.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node8.SetId(393);
			sequence7.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node8);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node8.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node395 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node9 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node395();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node9.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node9.SetId(395);
			sequence7.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node9);
			sequence7.SetHasEvents(sequence7.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node9.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | selector.HasEvents());
			selectorLoop2.SetHasEvents(selectorLoop2.HasEvents() | withPrecondition2.HasEvents());
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | selectorLoop2.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition.HasEvents());
			WithPrecondition withPrecondition3 = new WithPrecondition();
			withPrecondition3.SetClassNameString("WithPrecondition");
			withPrecondition3.SetId(143);
			selectorLoop.AddChild(withPrecondition3);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node131 condition_bt_WrapperAI_Monster_BTMonsterFairy_node7 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node131();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node7.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node7.SetId(131);
			withPrecondition3.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node7);
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(144);
			withPrecondition3.AddChild(sequence8);
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node145 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node10 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node145();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node10.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node10.SetId(145);
			sequence8.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node10);
			sequence8.SetHasEvents(sequence8.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node10.HasEvents());
			IfElse ifElse2 = new IfElse();
			ifElse2.SetClassNameString("IfElse");
			ifElse2.SetId(146);
			sequence8.AddChild(ifElse2);
			And and = new And();
			and.SetClassNameString("And");
			and.SetId(147);
			ifElse2.AddChild(and);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node189 condition_bt_WrapperAI_Monster_BTMonsterFairy_node8 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node189();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node8.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node8.SetId(189);
			and.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node8);
			and.SetHasEvents(and.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node8.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node190 condition_bt_WrapperAI_Monster_BTMonsterFairy_node9 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node190();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node9.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node9.SetId(190);
			and.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node9);
			and.SetHasEvents(and.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node9.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | and.HasEvents());
			Noop noop2 = new Noop();
			noop2.SetClassNameString("Noop");
			noop2.SetId(150);
			ifElse2.AddChild(noop2);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | noop2.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node151 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node11 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node151();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node11.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node11.SetId(151);
			ifElse2.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node11);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node11.HasEvents());
			sequence8.SetHasEvents(sequence8.HasEvents() | ifElse2.HasEvents());
			IfElse ifElse3 = new IfElse();
			ifElse3.SetClassNameString("IfElse");
			ifElse3.SetId(155);
			sequence8.AddChild(ifElse3);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node157 condition_bt_WrapperAI_Monster_BTMonsterFairy_node10 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node157();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node10.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node10.SetId(157);
			ifElse3.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node10);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node10.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(158);
			ifElse3.AddChild(sequence9);
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(169);
			sequence9.AddChild(selector2);
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(288);
			selector2.AddChild(sequence10);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node289 action_bt_WrapperAI_Monster_BTMonsterFairy_node9 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node289();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node9.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node9.SetId(289);
			sequence10.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node9);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node9.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node290 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node12 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node290();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node12.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node12.SetId(290);
			sequence10.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node12);
			sequence10.SetHasEvents(sequence10.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node12.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node291 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node13 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node291();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node13.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node13.SetId(291);
			sequence10.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node13);
			sequence10.SetHasEvents(sequence10.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node13.HasEvents());
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(292);
			sequence10.AddChild(selector3);
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(7);
			selector3.AddChild(sequence11);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node712 action_bt_WrapperAI_Monster_BTMonsterFairy_node10 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node712();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node10.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node10.SetId(712);
			sequence11.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node10);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node10.HasEvents());
			Selector selector4 = new Selector();
			selector4.SetClassNameString("Selector");
			selector4.SetId(3);
			sequence11.AddChild(selector4);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node2 condition_bt_WrapperAI_Monster_BTMonsterFairy_node11 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node2();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node11.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node11.SetId(2);
			selector4.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node11);
			selector4.SetHasEvents(selector4.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node11.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node4 condition_bt_WrapperAI_Monster_BTMonsterFairy_node12 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node4();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node12.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node12.SetId(4);
			selector4.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node12);
			selector4.SetHasEvents(selector4.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node12.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node5 condition_bt_WrapperAI_Monster_BTMonsterFairy_node13 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node5();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node13.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node13.SetId(5);
			selector4.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node13);
			selector4.SetHasEvents(selector4.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node13.HasEvents());
			sequence11.SetHasEvents(sequence11.HasEvents() | selector4.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node6 condition_bt_WrapperAI_Monster_BTMonsterFairy_node14 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node6();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node14.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node14.SetId(6);
			sequence11.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node14);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node14.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node8 action_bt_WrapperAI_Monster_BTMonsterFairy_node11 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node8();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node11.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node11.SetId(8);
			sequence11.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node11);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node11.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(13);
			selector3.AddChild(sequence12);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node9 condition_bt_WrapperAI_Monster_BTMonsterFairy_node15 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node9();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node15.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node15.SetId(9);
			sequence12.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node15);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node15.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node10 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node14 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node10();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node14.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node14.SetId(10);
			sequence12.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node14);
			sequence12.SetHasEvents(sequence12.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node14.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node12 condition_bt_WrapperAI_Monster_BTMonsterFairy_node16 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node12();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node16.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node16.SetId(12);
			sequence12.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node16);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node16.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node15 action_bt_WrapperAI_Monster_BTMonsterFairy_node12 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node15();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node12.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node12.SetId(15);
			sequence12.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node12);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node12.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence12.HasEvents());
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(17);
			selector3.AddChild(sequence13);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node18 condition_bt_WrapperAI_Monster_BTMonsterFairy_node17 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node18();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node17.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node17.SetId(18);
			sequence13.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node17);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node17.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node19 condition_bt_WrapperAI_Monster_BTMonsterFairy_node18 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node19();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node18.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node18.SetId(19);
			sequence13.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node18);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node18.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node20 action_bt_WrapperAI_Monster_BTMonsterFairy_node13 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node20();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node13.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node13.SetId(20);
			sequence13.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node13);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node13.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence13.HasEvents());
			IfElse ifElse4 = new IfElse();
			ifElse4.SetClassNameString("IfElse");
			ifElse4.SetId(30);
			selector3.AddChild(ifElse4);
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(33);
			ifElse4.AddChild(sequence14);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node32 condition_bt_WrapperAI_Monster_BTMonsterFairy_node19 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node32();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node19.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node19.SetId(32);
			sequence14.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node19);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node19.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node34 action_bt_WrapperAI_Monster_BTMonsterFairy_node14 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node34();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node14.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node14.SetId(34);
			sequence14.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node14);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node14.HasEvents());
			ifElse4.SetHasEvents(ifElse4.HasEvents() | sequence14.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(36);
			ifElse4.AddChild(sequence15);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node38 action_bt_WrapperAI_Monster_BTMonsterFairy_node15 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node38();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node15.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node15.SetId(38);
			sequence15.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node15);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node15.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node39 action_bt_WrapperAI_Monster_BTMonsterFairy_node16 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node39();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node16.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node16.SetId(39);
			sequence15.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node16);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node16.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node42 action_bt_WrapperAI_Monster_BTMonsterFairy_node17 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node42();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node17.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node17.SetId(42);
			sequence15.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node17);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node17.HasEvents());
			ifElse4.SetHasEvents(ifElse4.HasEvents() | sequence15.HasEvents());
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(37);
			ifElse4.AddChild(sequence16);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node44 action_bt_WrapperAI_Monster_BTMonsterFairy_node18 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node44();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node18.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node18.SetId(44);
			sequence16.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node18);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node18.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node45 action_bt_WrapperAI_Monster_BTMonsterFairy_node19 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node45();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node19.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node19.SetId(45);
			sequence16.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node19);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node19.HasEvents());
			ifElse4.SetHasEvents(ifElse4.HasEvents() | sequence16.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | ifElse4.HasEvents());
			sequence10.SetHasEvents(sequence10.HasEvents() | selector3.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence10.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | selector2.HasEvents());
			Sequence sequence17 = new Sequence();
			sequence17.SetClassNameString("Sequence");
			sequence17.SetId(311);
			sequence9.AddChild(sequence17);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node312 action_bt_WrapperAI_Monster_BTMonsterFairy_node20 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node312();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node20.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node20.SetId(312);
			sequence17.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node20);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node20.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node46 action_bt_WrapperAI_Monster_BTMonsterFairy_node21 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node46();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node21.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node21.SetId(46);
			sequence17.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node21);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node21.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node313 action_bt_WrapperAI_Monster_BTMonsterFairy_node22 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node313();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node22.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node22.SetId(313);
			sequence17.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node22);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node22.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node314 decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node314();
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node.SetId(314);
			sequence17.AddChild(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node29 condition_bt_WrapperAI_Monster_BTMonsterFairy_node20 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node29();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node20.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node20.SetId(29);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node20);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node20.HasEvents());
			sequence17.SetHasEvents(sequence17.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node132 action_bt_WrapperAI_Monster_BTMonsterFairy_node23 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node132();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node23.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node23.SetId(132);
			sequence17.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node23);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node23.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | sequence17.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence9.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node133 action_bt_WrapperAI_Monster_BTMonsterFairy_node24 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node133();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node24.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node24.SetId(133);
			ifElse3.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node24);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node24.HasEvents());
			sequence8.SetHasEvents(sequence8.HasEvents() | ifElse3.HasEvents());
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | sequence8.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition3.HasEvents());
			WithPrecondition withPrecondition4 = new WithPrecondition();
			withPrecondition4.SetClassNameString("WithPrecondition");
			withPrecondition4.SetId(47);
			selectorLoop.AddChild(withPrecondition4);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node51 condition_bt_WrapperAI_Monster_BTMonsterFairy_node21 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node51();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node21.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node21.SetId(51);
			withPrecondition4.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node21);
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node21.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node54 decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node2 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node54();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetId(54);
			withPrecondition4.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node2);
			Noop noop3 = new Noop();
			noop3.SetClassNameString("Noop");
			noop3.SetId(55);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node2.AddChild(noop3);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node2.HasEvents() | noop3.HasEvents());
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node2.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition4.HasEvents());
			WithPrecondition withPrecondition5 = new WithPrecondition();
			withPrecondition5.SetClassNameString("WithPrecondition");
			withPrecondition5.SetId(49);
			selectorLoop.AddChild(withPrecondition5);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node52 condition_bt_WrapperAI_Monster_BTMonsterFairy_node22 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node52();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node22.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node22.SetId(52);
			withPrecondition5.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node22);
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node22.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node56 decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node3 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node56();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetId(56);
			withPrecondition5.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node3);
			Noop noop4 = new Noop();
			noop4.SetClassNameString("Noop");
			noop4.SetId(58);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node3.AddChild(noop4);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node3.HasEvents() | noop4.HasEvents());
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node3.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition5.HasEvents());
			WithPrecondition withPrecondition6 = new WithPrecondition();
			withPrecondition6.SetClassNameString("WithPrecondition");
			withPrecondition6.SetId(50);
			selectorLoop.AddChild(withPrecondition6);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node53 condition_bt_WrapperAI_Monster_BTMonsterFairy_node23 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node53();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node23.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node23.SetId(53);
			withPrecondition6.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node23);
			withPrecondition6.SetHasEvents(withPrecondition6.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node23.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node57 decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node4 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node57();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node4.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node4.SetId(57);
			withPrecondition6.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node4);
			Noop noop5 = new Noop();
			noop5.SetClassNameString("Noop");
			noop5.SetId(59);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node4.AddChild(noop5);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node4.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node4.HasEvents() | noop5.HasEvents());
			withPrecondition6.SetHasEvents(withPrecondition6.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node4.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition6.HasEvents());
			WithPrecondition withPrecondition7 = new WithPrecondition();
			withPrecondition7.SetClassNameString("WithPrecondition");
			withPrecondition7.SetId(60);
			selectorLoop.AddChild(withPrecondition7);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node61 condition_bt_WrapperAI_Monster_BTMonsterFairy_node24 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node61();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node24.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node24.SetId(61);
			withPrecondition7.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node24);
			withPrecondition7.SetHasEvents(withPrecondition7.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node24.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node62 decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node5 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node62();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node5.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node5.SetId(62);
			withPrecondition7.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node5);
			Noop noop6 = new Noop();
			noop6.SetClassNameString("Noop");
			noop6.SetId(63);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node5.AddChild(noop6);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node5.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node5.HasEvents() | noop6.HasEvents());
			withPrecondition7.SetHasEvents(withPrecondition7.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node5.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition7.HasEvents());
			WithPrecondition withPrecondition8 = new WithPrecondition();
			withPrecondition8.SetClassNameString("WithPrecondition");
			withPrecondition8.SetId(515);
			selectorLoop.AddChild(withPrecondition8);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node516 condition_bt_WrapperAI_Monster_BTMonsterFairy_node25 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node516();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node25.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node25.SetId(516);
			withPrecondition8.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node25);
			withPrecondition8.SetHasEvents(withPrecondition8.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node25.HasEvents());
			Selector selector5 = new Selector();
			selector5.SetClassNameString("Selector");
			selector5.SetId(91);
			withPrecondition8.AddChild(selector5);
			Sequence sequence18 = new Sequence();
			sequence18.SetClassNameString("Sequence");
			sequence18.SetId(92);
			selector5.AddChild(sequence18);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node21 condition_bt_WrapperAI_Monster_BTMonsterFairy_node26 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node21();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node26.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node26.SetId(21);
			sequence18.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node26);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node26.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node22 assignment_bt_WrapperAI_Monster_BTMonsterFairy_node15 = new Assignment_bt_WrapperAI_Monster_BTMonsterFairy_node22();
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node15.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterFairy_node15.SetId(22);
			sequence18.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterFairy_node15);
			sequence18.SetHasEvents(sequence18.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterFairy_node15.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node23 action_bt_WrapperAI_Monster_BTMonsterFairy_node25 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node23();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node25.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node25.SetId(23);
			sequence18.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node25);
			sequence18.SetHasEvents(sequence18.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node25.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node24 action_bt_WrapperAI_Monster_BTMonsterFairy_node26 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node24();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node26.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node26.SetId(24);
			sequence18.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node26);
			sequence18.SetHasEvents(sequence18.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node26.HasEvents());
			selector5.SetHasEvents(selector5.HasEvents() | sequence18.HasEvents());
			Sequence sequence19 = new Sequence();
			sequence19.SetClassNameString("Sequence");
			sequence19.SetId(517);
			selector5.AddChild(sequence19);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node25 condition_bt_WrapperAI_Monster_BTMonsterFairy_node27 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node25();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node27.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node27.SetId(25);
			sequence19.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node27);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node27.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node518 action_bt_WrapperAI_Monster_BTMonsterFairy_node27 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node518();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node27.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node27.SetId(518);
			sequence19.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node27);
			sequence19.SetHasEvents(sequence19.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node27.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node519 action_bt_WrapperAI_Monster_BTMonsterFairy_node28 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node519();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node28.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node28.SetId(519);
			sequence19.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node28);
			sequence19.SetHasEvents(sequence19.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node28.HasEvents());
			IfElse ifElse5 = new IfElse();
			ifElse5.SetClassNameString("IfElse");
			ifElse5.SetId(520);
			sequence19.AddChild(ifElse5);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node521 condition_bt_WrapperAI_Monster_BTMonsterFairy_node28 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node521();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node28.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node28.SetId(521);
			ifElse5.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node28);
			ifElse5.SetHasEvents(ifElse5.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node28.HasEvents());
			Sequence sequence20 = new Sequence();
			sequence20.SetClassNameString("Sequence");
			sequence20.SetId(522);
			ifElse5.AddChild(sequence20);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node523 action_bt_WrapperAI_Monster_BTMonsterFairy_node29 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node523();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node29.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node29.SetId(523);
			sequence20.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node29);
			sequence20.SetHasEvents(sequence20.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node29.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node524 action_bt_WrapperAI_Monster_BTMonsterFairy_node30 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node524();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node30.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node30.SetId(524);
			sequence20.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node30);
			sequence20.SetHasEvents(sequence20.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node30.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node526 action_bt_WrapperAI_Monster_BTMonsterFairy_node31 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node526();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node31.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node31.SetId(526);
			sequence20.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node31);
			sequence20.SetHasEvents(sequence20.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node31.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node26 action_bt_WrapperAI_Monster_BTMonsterFairy_node32 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node26();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node32.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node32.SetId(26);
			sequence20.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node32);
			sequence20.SetHasEvents(sequence20.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node32.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node530 action_bt_WrapperAI_Monster_BTMonsterFairy_node33 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node530();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node33.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node33.SetId(530);
			sequence20.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node33);
			sequence20.SetHasEvents(sequence20.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node33.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node531 decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node2 = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node531();
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetId(531);
			sequence20.AddChild(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node2);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node532 condition_bt_WrapperAI_Monster_BTMonsterFairy_node29 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node532();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node29.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node29.SetId(532);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node2.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node29);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node2.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node2.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node29.HasEvents());
			sequence20.SetHasEvents(sequence20.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node2.HasEvents());
			ifElse5.SetHasEvents(ifElse5.HasEvents() | sequence20.HasEvents());
			Sequence sequence21 = new Sequence();
			sequence21.SetClassNameString("Sequence");
			sequence21.SetId(533);
			ifElse5.AddChild(sequence21);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node27 action_bt_WrapperAI_Monster_BTMonsterFairy_node34 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node27();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node34.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node34.SetId(27);
			sequence21.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node34);
			sequence21.SetHasEvents(sequence21.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node34.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node535 action_bt_WrapperAI_Monster_BTMonsterFairy_node35 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node535();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node35.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node35.SetId(535);
			sequence21.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node35);
			sequence21.SetHasEvents(sequence21.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node35.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node536 decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node3 = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node536();
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetId(536);
			sequence21.AddChild(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node3);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node537 condition_bt_WrapperAI_Monster_BTMonsterFairy_node30 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node537();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node30.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node30.SetId(537);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node3.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node30);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node3.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node3.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node30.HasEvents());
			sequence21.SetHasEvents(sequence21.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterFairy_node3.HasEvents());
			ifElse5.SetHasEvents(ifElse5.HasEvents() | sequence21.HasEvents());
			sequence19.SetHasEvents(sequence19.HasEvents() | ifElse5.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node538 action_bt_WrapperAI_Monster_BTMonsterFairy_node36 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node538();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node36.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node36.SetId(538);
			sequence19.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node36);
			sequence19.SetHasEvents(sequence19.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node36.HasEvents());
			selector5.SetHasEvents(selector5.HasEvents() | sequence19.HasEvents());
			withPrecondition8.SetHasEvents(withPrecondition8.HasEvents() | selector5.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition8.HasEvents());
			WithPrecondition withPrecondition9 = new WithPrecondition();
			withPrecondition9.SetClassNameString("WithPrecondition");
			withPrecondition9.SetId(163);
			selectorLoop.AddChild(withPrecondition9);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node164 condition_bt_WrapperAI_Monster_BTMonsterFairy_node31 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node164();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node31.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node31.SetId(164);
			withPrecondition9.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node31);
			withPrecondition9.SetHasEvents(withPrecondition9.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node31.HasEvents());
			Sequence sequence22 = new Sequence();
			sequence22.SetClassNameString("Sequence");
			sequence22.SetId(165);
			withPrecondition9.AddChild(sequence22);
			Selector selector6 = new Selector();
			selector6.SetClassNameString("Selector");
			selector6.SetId(487);
			sequence22.AddChild(selector6);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node488 action_bt_WrapperAI_Monster_BTMonsterFairy_node37 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node488();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node37.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node37.SetId(488);
			selector6.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node37);
			selector6.SetHasEvents(selector6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node37.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node166 action_bt_WrapperAI_Monster_BTMonsterFairy_node38 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node166();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node38.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node38.SetId(166);
			selector6.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node38);
			selector6.SetHasEvents(selector6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node38.HasEvents());
			sequence22.SetHasEvents(sequence22.HasEvents() | selector6.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node167 decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node6 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node167();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node6.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node6.SetId(167);
			sequence22.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node6);
			Noop noop7 = new Noop();
			noop7.SetClassNameString("Noop");
			noop7.SetId(168);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node6.AddChild(noop7);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node6.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node6.HasEvents() | noop7.HasEvents());
			sequence22.SetHasEvents(sequence22.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node6.HasEvents());
			withPrecondition9.SetHasEvents(withPrecondition9.HasEvents() | sequence22.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition9.HasEvents());
			WithPrecondition withPrecondition10 = new WithPrecondition();
			withPrecondition10.SetClassNameString("WithPrecondition");
			withPrecondition10.SetId(35);
			selectorLoop.AddChild(withPrecondition10);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node40 condition_bt_WrapperAI_Monster_BTMonsterFairy_node32 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node40();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node32.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node32.SetId(40);
			withPrecondition10.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node32);
			withPrecondition10.SetHasEvents(withPrecondition10.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node32.HasEvents());
			Sequence sequence23 = new Sequence();
			sequence23.SetClassNameString("Sequence");
			sequence23.SetId(41);
			withPrecondition10.AddChild(sequence23);
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node43 decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node7 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node43();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node7.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node7.SetId(43);
			sequence23.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node7);
			Noop noop8 = new Noop();
			noop8.SetClassNameString("Noop");
			noop8.SetId(458);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node7.AddChild(noop8);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node7.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node7.HasEvents() | noop8.HasEvents());
			sequence23.SetHasEvents(sequence23.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node7.HasEvents());
			withPrecondition10.SetHasEvents(withPrecondition10.HasEvents() | sequence23.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition10.HasEvents());
			WithPrecondition withPrecondition11 = new WithPrecondition();
			withPrecondition11.SetClassNameString("WithPrecondition");
			withPrecondition11.SetId(450);
			selectorLoop.AddChild(withPrecondition11);
			Condition_bt_WrapperAI_Monster_BTMonsterFairy_node454 condition_bt_WrapperAI_Monster_BTMonsterFairy_node33 = new Condition_bt_WrapperAI_Monster_BTMonsterFairy_node454();
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node33.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterFairy_node33.SetId(454);
			withPrecondition11.AddChild(condition_bt_WrapperAI_Monster_BTMonsterFairy_node33);
			withPrecondition11.SetHasEvents(withPrecondition11.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterFairy_node33.HasEvents());
			Sequence sequence24 = new Sequence();
			sequence24.SetClassNameString("Sequence");
			sequence24.SetId(455);
			withPrecondition11.AddChild(sequence24);
			Action_bt_WrapperAI_Monster_BTMonsterFairy_node456 action_bt_WrapperAI_Monster_BTMonsterFairy_node39 = new Action_bt_WrapperAI_Monster_BTMonsterFairy_node456();
			action_bt_WrapperAI_Monster_BTMonsterFairy_node39.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterFairy_node39.SetId(456);
			sequence24.AddChild(action_bt_WrapperAI_Monster_BTMonsterFairy_node39);
			sequence24.SetHasEvents(sequence24.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterFairy_node39.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node457 decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node8 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node457();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node8.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node8.SetId(457);
			sequence24.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node8);
			Noop noop9 = new Noop();
			noop9.SetClassNameString("Noop");
			noop9.SetId(28);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node8.AddChild(noop9);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node8.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node8.HasEvents() | noop9.HasEvents());
			sequence24.SetHasEvents(sequence24.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node8.HasEvents());
			withPrecondition11.SetHasEvents(withPrecondition11.HasEvents() | sequence24.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition11.HasEvents());
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node.HasEvents() | selectorLoop.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterFairy_node.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | sequence.HasEvents());
			return true;
		}
	}
}
