using System;

namespace behaviac
{
	public static class bt_WrapperAI_Soldier_BTSoldierNormal
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("WrapperAI/Soldier/BTSoldierNormal");
			bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
			bt.AddPar("uint", "p_targetID", "0", string.Empty);
			bt.AddPar("int", "p_srchRange", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
			bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
			bt.AddPar("uint", "p_CmdID", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("int", "p_pursueTime", "0", string.Empty);
			bt.AddPar("uint", "p_abandonTargetID", "0", string.Empty);
			bt.AddPar("uint", "p_tempTargetId", "0", string.Empty);
			bt.AddPar("ushort", "p_chooseTargetCount", "0", string.Empty);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			bt.AddChild(sequence);
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node106 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node106();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetId(106);
			sequence.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents());
			DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node14 decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node14();
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetId(14);
			sequence.AddChild(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node);
			SelectorLoop selectorLoop = new SelectorLoop();
			selectorLoop.SetClassNameString("SelectorLoop");
			selectorLoop.SetId(1);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node.AddChild(selectorLoop);
			WithPrecondition withPrecondition = new WithPrecondition();
			withPrecondition.SetClassNameString("WithPrecondition");
			withPrecondition.SetId(59);
			selectorLoop.AddChild(withPrecondition);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node78 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node78();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetId(78);
			withPrecondition.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node);
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(105);
			withPrecondition.AddChild(sequence2);
			IfElse ifElse = new IfElse();
			ifElse.SetClassNameString("IfElse");
			ifElse.SetId(10);
			sequence2.AddChild(ifElse);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node11 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node2 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node11();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetId(11);
			ifElse.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node2);
			ifElse.SetHasEvents(ifElse.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node2.HasEvents());
			Noop noop = new Noop();
			noop.SetClassNameString("Noop");
			noop.SetId(12);
			ifElse.AddChild(noop);
			ifElse.SetHasEvents(ifElse.HasEvents() | noop.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node107 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node2 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node107();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetId(107);
			ifElse.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node2);
			ifElse.SetHasEvents(ifElse.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node2.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | ifElse.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node26 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node3 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node26();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetId(26);
			sequence2.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node3.HasEvents());
			Parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node2 parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node = new Parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node2();
			parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetClassNameString("Parallel");
			parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetId(2);
			sequence2.AddChild(parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node);
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(3);
			parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node.AddChild(sequence3);
			IfElse ifElse2 = new IfElse();
			ifElse2.SetClassNameString("IfElse");
			ifElse2.SetId(36);
			sequence3.AddChild(ifElse2);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node4 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node3 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node4();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetId(4);
			ifElse2.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node3);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node3.HasEvents());
			True @true = new True();
			@true.SetClassNameString("True");
			@true.SetId(39);
			ifElse2.AddChild(@true);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | @true.HasEvents());
			DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node37 decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node = new DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node37();
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetClassNameString("DecoratorAlwaysFailure");
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetId(37);
			ifElse2.AddChild(decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node);
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(41);
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node.AddChild(sequence4);
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node38 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node4 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node38();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node4.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node4.SetId(38);
			sequence4.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node4.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node42 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node5 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node42();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node5.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node5.SetId(42);
			sequence4.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node5);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node5.HasEvents());
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetHasEvents(decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents() | sequence4.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents());
			sequence3.SetHasEvents(sequence3.HasEvents() | ifElse2.HasEvents());
			Compute_bt_WrapperAI_Soldier_BTSoldierNormal_node20 compute_bt_WrapperAI_Soldier_BTSoldierNormal_node = new Compute_bt_WrapperAI_Soldier_BTSoldierNormal_node20();
			compute_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetClassNameString("Compute");
			compute_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetId(20);
			sequence3.AddChild(compute_bt_WrapperAI_Soldier_BTSoldierNormal_node);
			sequence3.SetHasEvents(sequence3.HasEvents() | compute_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents());
			parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetHasEvents(parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents() | sequence3.HasEvents());
			SelectorLoop selectorLoop2 = new SelectorLoop();
			selectorLoop2.SetClassNameString("SelectorLoop");
			selectorLoop2.SetId(52);
			parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node.AddChild(selectorLoop2);
			WithPrecondition withPrecondition2 = new WithPrecondition();
			withPrecondition2.SetClassNameString("WithPrecondition");
			withPrecondition2.SetId(55);
			selectorLoop2.AddChild(withPrecondition2);
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(56);
			withPrecondition2.AddChild(sequence5);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node63 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node4 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node63();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node4.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node4.SetId(63);
			sequence5.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node4.HasEvents());
			Compute_bt_WrapperAI_Soldier_BTSoldierNormal_node68 compute_bt_WrapperAI_Soldier_BTSoldierNormal_node2 = new Compute_bt_WrapperAI_Soldier_BTSoldierNormal_node68();
			compute_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetClassNameString("Compute");
			compute_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetId(68);
			sequence5.AddChild(compute_bt_WrapperAI_Soldier_BTSoldierNormal_node2);
			sequence5.SetHasEvents(sequence5.HasEvents() | compute_bt_WrapperAI_Soldier_BTSoldierNormal_node2.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node64 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node5 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node64();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node5.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node5.SetId(64);
			sequence5.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node5.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node61 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node6 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node61();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node6.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node6.SetId(61);
			sequence5.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node6);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node6.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node67 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node7 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node67();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node7.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node7.SetId(67);
			sequence5.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node7.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node58 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node6 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node58();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node6.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node6.SetId(58);
			sequence5.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node6);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node6.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node60 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node8 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node60();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node8.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node8.SetId(60);
			sequence5.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node8);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node8.HasEvents());
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | sequence5.HasEvents());
			False @false = new False();
			@false.SetClassNameString("False");
			@false.SetId(57);
			withPrecondition2.AddChild(@false);
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | @false.HasEvents());
			selectorLoop2.SetHasEvents(selectorLoop2.HasEvents() | withPrecondition2.HasEvents());
			WithPrecondition withPrecondition3 = new WithPrecondition();
			withPrecondition3.SetClassNameString("WithPrecondition");
			withPrecondition3.SetId(5);
			selectorLoop2.AddChild(withPrecondition3);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node109 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node7 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node109();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node7.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node7.SetId(109);
			withPrecondition3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node7);
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node7.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(110);
			withPrecondition3.AddChild(sequence6);
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node40 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node9 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node40();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node9.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node9.SetId(40);
			sequence6.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node9);
			sequence6.SetHasEvents(sequence6.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node9.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node111 action_bt_WrapperAI_Soldier_BTSoldierNormal_node = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node111();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetId(111);
			sequence6.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node112 action_bt_WrapperAI_Soldier_BTSoldierNormal_node2 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node112();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetId(112);
			sequence6.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node2);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node2.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node44 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node10 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node44();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node10.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node10.SetId(44);
			sequence6.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node10);
			sequence6.SetHasEvents(sequence6.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node10.HasEvents());
			IfElse ifElse3 = new IfElse();
			ifElse3.SetClassNameString("IfElse");
			ifElse3.SetId(48);
			sequence6.AddChild(ifElse3);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node6 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node8 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node6();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node8.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node8.SetId(6);
			ifElse3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node8);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node8.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(7);
			ifElse3.AddChild(sequence7);
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node23 action_bt_WrapperAI_Soldier_BTSoldierNormal_node3 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node23();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetId(23);
			sequence7.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node3);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node3.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node113 action_bt_WrapperAI_Soldier_BTSoldierNormal_node4 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node113();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node4.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node4.SetId(113);
			sequence7.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node4);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node4.HasEvents());
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(17);
			sequence7.AddChild(selector);
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node114 action_bt_WrapperAI_Soldier_BTSoldierNormal_node5 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node114();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node5.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node5.SetId(114);
			selector.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node5);
			selector.SetHasEvents(selector.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node5.HasEvents());
			DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node19 decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node2 = new DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node19();
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetClassNameString("DecoratorAlwaysFailure");
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetId(19);
			selector.AddChild(decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node2);
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node18 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node11 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node18();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node11.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node11.SetId(18);
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node2.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node11);
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetHasEvents(decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node2.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node11.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node2.HasEvents());
			sequence7.SetHasEvents(sequence7.HasEvents() | selector.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node140 action_bt_WrapperAI_Soldier_BTSoldierNormal_node6 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node140();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node6.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node6.SetId(140);
			sequence7.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node6);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node6.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node116 action_bt_WrapperAI_Soldier_BTSoldierNormal_node7 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node116();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node7.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node7.SetId(116);
			sequence7.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node7.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node117 decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node117();
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetId(117);
			sequence7.AddChild(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node118 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node9 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node118();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node9.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node9.SetId(118);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node9);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node9.HasEvents());
			sequence7.SetHasEvents(sequence7.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(9);
			ifElse3.AddChild(sequence8);
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node8 action_bt_WrapperAI_Soldier_BTSoldierNormal_node8 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node8();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node8.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node8.SetId(8);
			sequence8.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node8.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node13 action_bt_WrapperAI_Soldier_BTSoldierNormal_node9 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node13();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node9.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node9.SetId(13);
			sequence8.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node9);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node9.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node15 decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node2 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node15();
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetId(15);
			sequence8.AddChild(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node2);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node16 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node10 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node16();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node10.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node10.SetId(16);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node2.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node10);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node2.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node10.HasEvents());
			sequence8.SetHasEvents(sequence8.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node2.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence8.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | ifElse3.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node28 action_bt_WrapperAI_Soldier_BTSoldierNormal_node10 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node28();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node10.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node10.SetId(28);
			sequence6.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node10);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node10.HasEvents());
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | sequence6.HasEvents());
			selectorLoop2.SetHasEvents(selectorLoop2.HasEvents() | withPrecondition3.HasEvents());
			WithPrecondition withPrecondition4 = new WithPrecondition();
			withPrecondition4.SetClassNameString("WithPrecondition");
			withPrecondition4.SetId(53);
			selectorLoop2.AddChild(withPrecondition4);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node54 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node11 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node54();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node11.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node11.SetId(54);
			withPrecondition4.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node11);
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node11.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(128);
			withPrecondition4.AddChild(sequence9);
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node129 action_bt_WrapperAI_Soldier_BTSoldierNormal_node11 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node129();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node11.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node11.SetId(129);
			sequence9.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node11);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node11.HasEvents());
			IfElse ifElse4 = new IfElse();
			ifElse4.SetClassNameString("IfElse");
			ifElse4.SetId(119);
			sequence9.AddChild(ifElse4);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node120 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node12 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node120();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node12.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node12.SetId(120);
			ifElse4.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node12);
			ifElse4.SetHasEvents(ifElse4.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node12.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(121);
			ifElse4.AddChild(sequence10);
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node24 action_bt_WrapperAI_Soldier_BTSoldierNormal_node12 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node24();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node12.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node12.SetId(24);
			sequence10.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node12);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node12.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node444 action_bt_WrapperAI_Soldier_BTSoldierNormal_node13 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node444();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node13.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node13.SetId(444);
			sequence10.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node13);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node13.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node122 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node12 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node122();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node12.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node12.SetId(122);
			sequence10.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node12);
			sequence10.SetHasEvents(sequence10.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node12.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node123 action_bt_WrapperAI_Soldier_BTSoldierNormal_node14 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node123();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node14.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node14.SetId(123);
			sequence10.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node14);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node14.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node124 action_bt_WrapperAI_Soldier_BTSoldierNormal_node15 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node124();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node15.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node15.SetId(124);
			sequence10.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node15);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node15.HasEvents());
			ifElse4.SetHasEvents(ifElse4.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(125);
			ifElse4.AddChild(sequence11);
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node126 action_bt_WrapperAI_Soldier_BTSoldierNormal_node16 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node126();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node16.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node16.SetId(126);
			sequence11.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node16);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node16.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node127 action_bt_WrapperAI_Soldier_BTSoldierNormal_node17 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node127();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node17.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node17.SetId(127);
			sequence11.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node17);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node17.HasEvents());
			ifElse4.SetHasEvents(ifElse4.HasEvents() | sequence11.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | ifElse4.HasEvents());
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | sequence9.HasEvents());
			selectorLoop2.SetHasEvents(selectorLoop2.HasEvents() | withPrecondition4.HasEvents());
			parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetHasEvents(parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents() | selectorLoop2.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents());
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | sequence2.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition.HasEvents());
			WithPrecondition withPrecondition5 = new WithPrecondition();
			withPrecondition5.SetClassNameString("WithPrecondition");
			withPrecondition5.SetId(515);
			selectorLoop.AddChild(withPrecondition5);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node516 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node13 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node516();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node13.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node13.SetId(516);
			withPrecondition5.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node13);
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node13.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(34);
			withPrecondition5.AddChild(selector2);
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(43);
			selector2.AddChild(sequence12);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node25 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node14 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node25();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node14.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node14.SetId(25);
			sequence12.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node14);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node14.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node45 assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node13 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node45();
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node13.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node13.SetId(45);
			sequence12.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node13);
			sequence12.SetHasEvents(sequence12.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node13.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node29 action_bt_WrapperAI_Soldier_BTSoldierNormal_node18 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node29();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node18.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node18.SetId(29);
			sequence12.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node18);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node18.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node30 action_bt_WrapperAI_Soldier_BTSoldierNormal_node19 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node30();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node19.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node19.SetId(30);
			sequence12.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node19);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node19.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence12.HasEvents());
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(517);
			selector2.AddChild(sequence13);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node31 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node15 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node31();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node15.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node15.SetId(31);
			sequence13.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node15);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node15.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node518 action_bt_WrapperAI_Soldier_BTSoldierNormal_node20 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node518();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node20.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node20.SetId(518);
			sequence13.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node20);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node20.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node519 action_bt_WrapperAI_Soldier_BTSoldierNormal_node21 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node519();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node21.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node21.SetId(519);
			sequence13.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node21);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node21.HasEvents());
			IfElse ifElse5 = new IfElse();
			ifElse5.SetClassNameString("IfElse");
			ifElse5.SetId(520);
			sequence13.AddChild(ifElse5);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node521 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node16 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node521();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node16.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node16.SetId(521);
			ifElse5.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node16);
			ifElse5.SetHasEvents(ifElse5.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node16.HasEvents());
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(522);
			ifElse5.AddChild(sequence14);
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node523 action_bt_WrapperAI_Soldier_BTSoldierNormal_node22 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node523();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node22.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node22.SetId(523);
			sequence14.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node22);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node22.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node524 action_bt_WrapperAI_Soldier_BTSoldierNormal_node23 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node524();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node23.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node23.SetId(524);
			sequence14.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node23);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node23.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node526 action_bt_WrapperAI_Soldier_BTSoldierNormal_node24 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node526();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node24.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node24.SetId(526);
			sequence14.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node24);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node24.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node32 action_bt_WrapperAI_Soldier_BTSoldierNormal_node25 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node32();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node25.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node25.SetId(32);
			sequence14.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node25);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node25.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node530 action_bt_WrapperAI_Soldier_BTSoldierNormal_node26 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node530();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node26.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node26.SetId(530);
			sequence14.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node26);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node26.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node531 decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node3 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node531();
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetId(531);
			sequence14.AddChild(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node3);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node532 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node17 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node532();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node17.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node17.SetId(532);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node17);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node17.HasEvents());
			sequence14.SetHasEvents(sequence14.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node3.HasEvents());
			ifElse5.SetHasEvents(ifElse5.HasEvents() | sequence14.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(533);
			ifElse5.AddChild(sequence15);
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node33 action_bt_WrapperAI_Soldier_BTSoldierNormal_node27 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node33();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node27.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node27.SetId(33);
			sequence15.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node27);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node27.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node535 action_bt_WrapperAI_Soldier_BTSoldierNormal_node28 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node535();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node28.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node28.SetId(535);
			sequence15.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node28);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node28.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node536 decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node4 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node536();
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node4.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node4.SetId(536);
			sequence15.AddChild(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node4);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node537 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node18 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node537();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node18.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node18.SetId(537);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node4.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node18);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node4.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node4.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node18.HasEvents());
			sequence15.SetHasEvents(sequence15.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node4.HasEvents());
			ifElse5.SetHasEvents(ifElse5.HasEvents() | sequence15.HasEvents());
			sequence13.SetHasEvents(sequence13.HasEvents() | ifElse5.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node538 action_bt_WrapperAI_Soldier_BTSoldierNormal_node29 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node538();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node29.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node29.SetId(538);
			sequence13.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node29);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node29.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence13.HasEvents());
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | selector2.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition5.HasEvents());
			WithPrecondition withPrecondition6 = new WithPrecondition();
			withPrecondition6.SetClassNameString("WithPrecondition");
			withPrecondition6.SetId(21);
			selectorLoop.AddChild(withPrecondition6);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node22 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node19 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node22();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node19.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node19.SetId(22);
			withPrecondition6.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node19);
			withPrecondition6.SetHasEvents(withPrecondition6.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node19.HasEvents());
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(27);
			withPrecondition6.AddChild(sequence16);
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(487);
			sequence16.AddChild(selector3);
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node488 action_bt_WrapperAI_Soldier_BTSoldierNormal_node30 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node488();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node30.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node30.SetId(488);
			selector3.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node30);
			selector3.SetHasEvents(selector3.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node30.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node35 action_bt_WrapperAI_Soldier_BTSoldierNormal_node31 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node35();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node31.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node31.SetId(35);
			selector3.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node31);
			selector3.SetHasEvents(selector3.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node31.HasEvents());
			sequence16.SetHasEvents(sequence16.HasEvents() | selector3.HasEvents());
			DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node65 decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node2 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node65();
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetId(65);
			sequence16.AddChild(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node2);
			Noop noop2 = new Noop();
			noop2.SetClassNameString("Noop");
			noop2.SetId(66);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node2.AddChild(noop2);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node2.SetHasEvents(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node2.HasEvents() | noop2.HasEvents());
			sequence16.SetHasEvents(sequence16.HasEvents() | decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node2.HasEvents());
			withPrecondition6.SetHasEvents(withPrecondition6.HasEvents() | sequence16.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition6.HasEvents());
			WithPrecondition withPrecondition7 = new WithPrecondition();
			withPrecondition7.SetClassNameString("WithPrecondition");
			withPrecondition7.SetId(450);
			selectorLoop.AddChild(withPrecondition7);
			Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node454 condition_bt_WrapperAI_Soldier_BTSoldierNormal_node20 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node454();
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node20.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierNormal_node20.SetId(454);
			withPrecondition7.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierNormal_node20);
			withPrecondition7.SetHasEvents(withPrecondition7.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierNormal_node20.HasEvents());
			Sequence sequence17 = new Sequence();
			sequence17.SetClassNameString("Sequence");
			sequence17.SetId(455);
			withPrecondition7.AddChild(sequence17);
			Action_bt_WrapperAI_Soldier_BTSoldierNormal_node456 action_bt_WrapperAI_Soldier_BTSoldierNormal_node32 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node456();
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node32.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierNormal_node32.SetId(456);
			sequence17.AddChild(action_bt_WrapperAI_Soldier_BTSoldierNormal_node32);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierNormal_node32.HasEvents());
			DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node457 decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node3 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node457();
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetId(457);
			sequence17.AddChild(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node3);
			Noop noop3 = new Noop();
			noop3.SetClassNameString("Noop");
			noop3.SetId(458);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node3.AddChild(noop3);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node3.SetHasEvents(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node3.HasEvents() | noop3.HasEvents());
			sequence17.SetHasEvents(sequence17.HasEvents() | decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node3.HasEvents());
			withPrecondition7.SetHasEvents(withPrecondition7.HasEvents() | sequence17.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition7.HasEvents());
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node.SetHasEvents(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents() | selectorLoop.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | sequence.HasEvents());
			return true;
		}
	}
}
