using System;

namespace behaviac
{
	public static class bt_WrapperAI_Soldier_BTSoldierSiege
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("WrapperAI/Soldier/BTSoldierSiege");
			bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
			bt.AddPar("uint", "p_targetID", "0", string.Empty);
			bt.AddPar("int", "p_srchRange", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
			bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
			bt.AddPar("uint", "p_CmdID", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("uint", "p_tempTargetId", "0", string.Empty);
			bt.AddPar("ushort", "p_chooseTargetCount", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_TargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_TargetPosNew", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			bt.AddChild(sequence);
			Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node106 assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node106();
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetId(106);
			sequence.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node.HasEvents());
			DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node14 decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node14();
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetId(14);
			sequence.AddChild(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node);
			SelectorLoop selectorLoop = new SelectorLoop();
			selectorLoop.SetClassNameString("SelectorLoop");
			selectorLoop.SetId(1);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node.AddChild(selectorLoop);
			WithPrecondition withPrecondition = new WithPrecondition();
			withPrecondition.SetClassNameString("WithPrecondition");
			withPrecondition.SetId(59);
			selectorLoop.AddChild(withPrecondition);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node78 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node78();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetId(78);
			withPrecondition.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node);
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(41);
			withPrecondition.AddChild(sequence2);
			IfElse ifElse = new IfElse();
			ifElse.SetClassNameString("IfElse");
			ifElse.SetId(4);
			sequence2.AddChild(ifElse);
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(31);
			ifElse.AddChild(sequence3);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node33 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node2 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node33();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetId(33);
			sequence3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node2.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node30 assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node2 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node30();
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetId(30);
			sequence3.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node2.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node34 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node3 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node34();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetId(34);
			sequence3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node3.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | sequence3.HasEvents());
			Noop noop = new Noop();
			noop.SetClassNameString("Noop");
			noop.SetId(36);
			ifElse.AddChild(noop);
			ifElse.SetHasEvents(ifElse.HasEvents() | noop.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(37);
			ifElse.AddChild(sequence4);
			Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node29 assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node3 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node29();
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetId(29);
			sequence4.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node3);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node3.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node38 assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node4 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node38();
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node4.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node4.SetId(38);
			sequence4.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node4.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | sequence4.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | ifElse.HasEvents());
			IfElse ifElse2 = new IfElse();
			ifElse2.SetClassNameString("IfElse");
			ifElse2.SetId(108);
			sequence2.AddChild(ifElse2);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node109 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node4 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node109();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node4.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node4.SetId(109);
			ifElse2.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node4);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(110);
			ifElse2.AddChild(sequence5);
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node111 action_bt_WrapperAI_Soldier_BTSoldierSiege_node = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node111();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetId(111);
			sequence5.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node112 action_bt_WrapperAI_Soldier_BTSoldierSiege_node2 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node112();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetId(112);
			sequence5.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node2);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node2.HasEvents());
			IfElse ifElse3 = new IfElse();
			ifElse3.SetClassNameString("IfElse");
			ifElse3.SetId(5);
			sequence5.AddChild(ifElse3);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node6 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node5 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node6();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node5.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node5.SetId(6);
			ifElse3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node5);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(7);
			ifElse3.AddChild(sequence6);
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node23 action_bt_WrapperAI_Soldier_BTSoldierSiege_node3 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node23();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetId(23);
			sequence6.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node3);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node3.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node113 action_bt_WrapperAI_Soldier_BTSoldierSiege_node4 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node113();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node4.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node4.SetId(113);
			sequence6.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node4);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node4.HasEvents());
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(17);
			sequence6.AddChild(selector);
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node114 action_bt_WrapperAI_Soldier_BTSoldierSiege_node5 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node114();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node5.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node5.SetId(114);
			selector.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node5);
			selector.SetHasEvents(selector.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node5.HasEvents());
			DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node19 decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node = new DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node19();
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetClassNameString("DecoratorAlwaysFailure");
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetId(19);
			selector.AddChild(decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node);
			Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node18 assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node5 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node18();
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node5.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node5.SetId(18);
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node5);
			decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetHasEvents(decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | decoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | selector.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node140 action_bt_WrapperAI_Soldier_BTSoldierSiege_node6 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node140();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node6.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node6.SetId(140);
			sequence6.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node6.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node116 action_bt_WrapperAI_Soldier_BTSoldierSiege_node7 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node116();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node7.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node7.SetId(116);
			sequence6.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node7);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node7.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node117 decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node117();
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetId(117);
			sequence6.AddChild(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node118 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node6 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node118();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node6.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node6.SetId(118);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node6);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node6.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(9);
			ifElse3.AddChild(sequence7);
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node32 action_bt_WrapperAI_Soldier_BTSoldierSiege_node8 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node32();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node8.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node8.SetId(32);
			sequence7.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node8);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node8.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node13 action_bt_WrapperAI_Soldier_BTSoldierSiege_node9 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node13();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node9.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node9.SetId(13);
			sequence7.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node9);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node9.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node15 decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node2 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node15();
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetId(15);
			sequence7.AddChild(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node2);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node16 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node7 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node16();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node7.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node7.SetId(16);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node2.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node7);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node2.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node7.HasEvents());
			sequence7.SetHasEvents(sequence7.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node2.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence7.HasEvents());
			sequence5.SetHasEvents(sequence5.HasEvents() | ifElse3.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node28 action_bt_WrapperAI_Soldier_BTSoldierSiege_node10 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node28();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node10.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node10.SetId(28);
			sequence5.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node10);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node10.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | sequence5.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(128);
			ifElse2.AddChild(sequence8);
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node129 action_bt_WrapperAI_Soldier_BTSoldierSiege_node11 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node129();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node11.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node11.SetId(129);
			sequence8.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node11);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node11.HasEvents());
			IfElse ifElse4 = new IfElse();
			ifElse4.SetClassNameString("IfElse");
			ifElse4.SetId(119);
			sequence8.AddChild(ifElse4);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node120 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node8 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node120();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node8.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node8.SetId(120);
			ifElse4.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node8);
			ifElse4.SetHasEvents(ifElse4.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(121);
			ifElse4.AddChild(sequence9);
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node24 action_bt_WrapperAI_Soldier_BTSoldierSiege_node12 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node24();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node12.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node12.SetId(24);
			sequence9.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node12);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node12.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node444 action_bt_WrapperAI_Soldier_BTSoldierSiege_node13 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node444();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node13.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node13.SetId(444);
			sequence9.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node13);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node13.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node122 assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node6 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node122();
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node6.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node6.SetId(122);
			sequence9.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node6);
			sequence9.SetHasEvents(sequence9.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node6.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node123 action_bt_WrapperAI_Soldier_BTSoldierSiege_node14 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node123();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node14.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node14.SetId(123);
			sequence9.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node14);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node14.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node124 action_bt_WrapperAI_Soldier_BTSoldierSiege_node15 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node124();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node15.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node15.SetId(124);
			sequence9.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node15);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node15.HasEvents());
			ifElse4.SetHasEvents(ifElse4.HasEvents() | sequence9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(125);
			ifElse4.AddChild(sequence10);
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node126 action_bt_WrapperAI_Soldier_BTSoldierSiege_node16 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node126();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node16.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node16.SetId(126);
			sequence10.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node16);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node16.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node127 action_bt_WrapperAI_Soldier_BTSoldierSiege_node17 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node127();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node17.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node17.SetId(127);
			sequence10.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node17);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node17.HasEvents());
			ifElse4.SetHasEvents(ifElse4.HasEvents() | sequence10.HasEvents());
			sequence8.SetHasEvents(sequence8.HasEvents() | ifElse4.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | sequence8.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | ifElse2.HasEvents());
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | sequence2.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition.HasEvents());
			WithPrecondition withPrecondition2 = new WithPrecondition();
			withPrecondition2.SetClassNameString("WithPrecondition");
			withPrecondition2.SetId(515);
			selectorLoop.AddChild(withPrecondition2);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node516 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node9 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node516();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node9.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node9.SetId(516);
			withPrecondition2.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node9);
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node9.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(2);
			withPrecondition2.AddChild(selector2);
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(3);
			selector2.AddChild(sequence11);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node10 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node10 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node10();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node10.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node10.SetId(10);
			sequence11.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node10);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node10.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node11 assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node7 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node11();
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node7.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node7.SetId(11);
			sequence11.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node7);
			sequence11.SetHasEvents(sequence11.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node7.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node12 action_bt_WrapperAI_Soldier_BTSoldierSiege_node18 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node12();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node18.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node18.SetId(12);
			sequence11.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node18);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node18.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node8 action_bt_WrapperAI_Soldier_BTSoldierSiege_node19 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node8();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node19.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node19.SetId(8);
			sequence11.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node19);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node19.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(517);
			selector2.AddChild(sequence12);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node20 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node11 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node20();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node11.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node11.SetId(20);
			sequence12.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node11);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node11.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node518 action_bt_WrapperAI_Soldier_BTSoldierSiege_node20 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node518();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node20.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node20.SetId(518);
			sequence12.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node20);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node20.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node519 action_bt_WrapperAI_Soldier_BTSoldierSiege_node21 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node519();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node21.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node21.SetId(519);
			sequence12.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node21);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node21.HasEvents());
			IfElse ifElse5 = new IfElse();
			ifElse5.SetClassNameString("IfElse");
			ifElse5.SetId(520);
			sequence12.AddChild(ifElse5);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node521 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node12 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node521();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node12.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node12.SetId(521);
			ifElse5.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node12);
			ifElse5.SetHasEvents(ifElse5.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node12.HasEvents());
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(522);
			ifElse5.AddChild(sequence13);
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node523 action_bt_WrapperAI_Soldier_BTSoldierSiege_node22 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node523();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node22.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node22.SetId(523);
			sequence13.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node22);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node22.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node524 action_bt_WrapperAI_Soldier_BTSoldierSiege_node23 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node524();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node23.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node23.SetId(524);
			sequence13.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node23);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node23.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node526 action_bt_WrapperAI_Soldier_BTSoldierSiege_node24 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node526();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node24.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node24.SetId(526);
			sequence13.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node24);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node24.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node25 action_bt_WrapperAI_Soldier_BTSoldierSiege_node25 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node25();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node25.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node25.SetId(25);
			sequence13.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node25);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node25.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node530 action_bt_WrapperAI_Soldier_BTSoldierSiege_node26 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node530();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node26.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node26.SetId(530);
			sequence13.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node26);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node26.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node531 decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node3 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node531();
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetId(531);
			sequence13.AddChild(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node3);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node532 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node13 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node532();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node13.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node13.SetId(532);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node13);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node13.HasEvents());
			sequence13.SetHasEvents(sequence13.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node3.HasEvents());
			ifElse5.SetHasEvents(ifElse5.HasEvents() | sequence13.HasEvents());
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(533);
			ifElse5.AddChild(sequence14);
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node26 action_bt_WrapperAI_Soldier_BTSoldierSiege_node27 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node26();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node27.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node27.SetId(26);
			sequence14.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node27);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node27.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node535 action_bt_WrapperAI_Soldier_BTSoldierSiege_node28 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node535();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node28.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node28.SetId(535);
			sequence14.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node28);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node28.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node536 decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node4 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node536();
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node4.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node4.SetId(536);
			sequence14.AddChild(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node4);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node537 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node14 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node537();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node14.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node14.SetId(537);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node4.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node14);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node4.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node4.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node14.HasEvents());
			sequence14.SetHasEvents(sequence14.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node4.HasEvents());
			ifElse5.SetHasEvents(ifElse5.HasEvents() | sequence14.HasEvents());
			sequence12.SetHasEvents(sequence12.HasEvents() | ifElse5.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node538 action_bt_WrapperAI_Soldier_BTSoldierSiege_node29 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node538();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node29.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node29.SetId(538);
			sequence12.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node29);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node29.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence12.HasEvents());
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | selector2.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition2.HasEvents());
			WithPrecondition withPrecondition3 = new WithPrecondition();
			withPrecondition3.SetClassNameString("WithPrecondition");
			withPrecondition3.SetId(21);
			selectorLoop.AddChild(withPrecondition3);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node22 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node15 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node22();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node15.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node15.SetId(22);
			withPrecondition3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node15);
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node15.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(27);
			withPrecondition3.AddChild(sequence15);
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(487);
			sequence15.AddChild(selector3);
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node488 action_bt_WrapperAI_Soldier_BTSoldierSiege_node30 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node488();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node30.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node30.SetId(488);
			selector3.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node30);
			selector3.SetHasEvents(selector3.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node30.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node35 action_bt_WrapperAI_Soldier_BTSoldierSiege_node31 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node35();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node31.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node31.SetId(35);
			selector3.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node31);
			selector3.SetHasEvents(selector3.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node31.HasEvents());
			sequence15.SetHasEvents(sequence15.HasEvents() | selector3.HasEvents());
			DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node65 decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node2 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node65();
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetId(65);
			sequence15.AddChild(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node2);
			Noop noop2 = new Noop();
			noop2.SetClassNameString("Noop");
			noop2.SetId(66);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node2.AddChild(noop2);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node2.SetHasEvents(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node2.HasEvents() | noop2.HasEvents());
			sequence15.SetHasEvents(sequence15.HasEvents() | decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node2.HasEvents());
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | sequence15.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition3.HasEvents());
			WithPrecondition withPrecondition4 = new WithPrecondition();
			withPrecondition4.SetClassNameString("WithPrecondition");
			withPrecondition4.SetId(450);
			selectorLoop.AddChild(withPrecondition4);
			Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node454 condition_bt_WrapperAI_Soldier_BTSoldierSiege_node16 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node454();
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node16.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierSiege_node16.SetId(454);
			withPrecondition4.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierSiege_node16);
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierSiege_node16.HasEvents());
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(455);
			withPrecondition4.AddChild(sequence16);
			Action_bt_WrapperAI_Soldier_BTSoldierSiege_node456 action_bt_WrapperAI_Soldier_BTSoldierSiege_node32 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node456();
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node32.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierSiege_node32.SetId(456);
			sequence16.AddChild(action_bt_WrapperAI_Soldier_BTSoldierSiege_node32);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierSiege_node32.HasEvents());
			DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node457 decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node3 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node457();
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetId(457);
			sequence16.AddChild(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node3);
			Noop noop3 = new Noop();
			noop3.SetClassNameString("Noop");
			noop3.SetId(458);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node3.AddChild(noop3);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node3.SetHasEvents(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node3.HasEvents() | noop3.HasEvents());
			sequence16.SetHasEvents(sequence16.HasEvents() | decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node3.HasEvents());
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | sequence16.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition4.HasEvents());
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node.SetHasEvents(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node.HasEvents() | selectorLoop.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | sequence.HasEvents());
			return true;
		}
	}
}
