using System;

namespace behaviac
{
	public static class bt_WrapperAI_Hero_HeroRoundAI
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("WrapperAI/Hero/HeroRoundAI");
			bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_direction", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("uint", "p_selfID", "0", string.Empty);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(411);
			bt.AddChild(sequence);
			Assignment_bt_WrapperAI_Hero_HeroRoundAI_node658 assignment_bt_WrapperAI_Hero_HeroRoundAI_node = new Assignment_bt_WrapperAI_Hero_HeroRoundAI_node658();
			assignment_bt_WrapperAI_Hero_HeroRoundAI_node.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Hero_HeroRoundAI_node.SetId(658);
			sequence.AddChild(assignment_bt_WrapperAI_Hero_HeroRoundAI_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Hero_HeroRoundAI_node.HasEvents());
			Action_bt_WrapperAI_Hero_HeroRoundAI_node1035 action_bt_WrapperAI_Hero_HeroRoundAI_node = new Action_bt_WrapperAI_Hero_HeroRoundAI_node1035();
			action_bt_WrapperAI_Hero_HeroRoundAI_node.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node.SetId(1035);
			sequence.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node.HasEvents());
			DecoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node14 decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node = new DecoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node14();
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node.SetId(14);
			sequence.AddChild(decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node);
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(69);
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node.AddChild(sequence2);
			IfElse ifElse = new IfElse();
			ifElse.SetClassNameString("IfElse");
			ifElse.SetId(205);
			sequence2.AddChild(ifElse);
			Condition_bt_WrapperAI_Hero_HeroRoundAI_node207 condition_bt_WrapperAI_Hero_HeroRoundAI_node = new Condition_bt_WrapperAI_Hero_HeroRoundAI_node207();
			condition_bt_WrapperAI_Hero_HeroRoundAI_node.SetClassNameString("Condition");
			condition_bt_WrapperAI_Hero_HeroRoundAI_node.SetId(207);
			ifElse.AddChild(condition_bt_WrapperAI_Hero_HeroRoundAI_node);
			ifElse.SetHasEvents(ifElse.HasEvents() | condition_bt_WrapperAI_Hero_HeroRoundAI_node.HasEvents());
			Noop noop = new Noop();
			noop.SetClassNameString("Noop");
			noop.SetId(210);
			ifElse.AddChild(noop);
			ifElse.SetHasEvents(ifElse.HasEvents() | noop.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(211);
			ifElse.AddChild(sequence3);
			Action_bt_WrapperAI_Hero_HeroRoundAI_node597 action_bt_WrapperAI_Hero_HeroRoundAI_node2 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node597();
			action_bt_WrapperAI_Hero_HeroRoundAI_node2.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node2.SetId(597);
			sequence3.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node2.HasEvents());
			Assignment_bt_WrapperAI_Hero_HeroRoundAI_node235 assignment_bt_WrapperAI_Hero_HeroRoundAI_node2 = new Assignment_bt_WrapperAI_Hero_HeroRoundAI_node235();
			assignment_bt_WrapperAI_Hero_HeroRoundAI_node2.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Hero_HeroRoundAI_node2.SetId(235);
			sequence3.AddChild(assignment_bt_WrapperAI_Hero_HeroRoundAI_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | assignment_bt_WrapperAI_Hero_HeroRoundAI_node2.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | sequence3.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | ifElse.HasEvents());
			SelectorLoop selectorLoop = new SelectorLoop();
			selectorLoop.SetClassNameString("SelectorLoop");
			selectorLoop.SetId(1);
			sequence2.AddChild(selectorLoop);
			WithPrecondition withPrecondition = new WithPrecondition();
			withPrecondition.SetClassNameString("WithPrecondition");
			withPrecondition.SetId(107);
			selectorLoop.AddChild(withPrecondition);
			Condition_bt_WrapperAI_Hero_HeroRoundAI_node108 condition_bt_WrapperAI_Hero_HeroRoundAI_node2 = new Condition_bt_WrapperAI_Hero_HeroRoundAI_node108();
			condition_bt_WrapperAI_Hero_HeroRoundAI_node2.SetClassNameString("Condition");
			condition_bt_WrapperAI_Hero_HeroRoundAI_node2.SetId(108);
			withPrecondition.AddChild(condition_bt_WrapperAI_Hero_HeroRoundAI_node2);
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | condition_bt_WrapperAI_Hero_HeroRoundAI_node2.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(135);
			withPrecondition.AddChild(sequence4);
			Assignment_bt_WrapperAI_Hero_HeroRoundAI_node136 assignment_bt_WrapperAI_Hero_HeroRoundAI_node3 = new Assignment_bt_WrapperAI_Hero_HeroRoundAI_node136();
			assignment_bt_WrapperAI_Hero_HeroRoundAI_node3.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Hero_HeroRoundAI_node3.SetId(136);
			sequence4.AddChild(assignment_bt_WrapperAI_Hero_HeroRoundAI_node3);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_WrapperAI_Hero_HeroRoundAI_node3.HasEvents());
			IfElse ifElse2 = new IfElse();
			ifElse2.SetClassNameString("IfElse");
			ifElse2.SetId(327);
			sequence4.AddChild(ifElse2);
			Condition_bt_WrapperAI_Hero_HeroRoundAI_node328 condition_bt_WrapperAI_Hero_HeroRoundAI_node3 = new Condition_bt_WrapperAI_Hero_HeroRoundAI_node328();
			condition_bt_WrapperAI_Hero_HeroRoundAI_node3.SetClassNameString("Condition");
			condition_bt_WrapperAI_Hero_HeroRoundAI_node3.SetId(328);
			ifElse2.AddChild(condition_bt_WrapperAI_Hero_HeroRoundAI_node3);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | condition_bt_WrapperAI_Hero_HeroRoundAI_node3.HasEvents());
			IfElse ifElse3 = new IfElse();
			ifElse3.SetClassNameString("IfElse");
			ifElse3.SetId(335);
			ifElse2.AddChild(ifElse3);
			Condition_bt_WrapperAI_Hero_HeroRoundAI_node336 condition_bt_WrapperAI_Hero_HeroRoundAI_node4 = new Condition_bt_WrapperAI_Hero_HeroRoundAI_node336();
			condition_bt_WrapperAI_Hero_HeroRoundAI_node4.SetClassNameString("Condition");
			condition_bt_WrapperAI_Hero_HeroRoundAI_node4.SetId(336);
			ifElse3.AddChild(condition_bt_WrapperAI_Hero_HeroRoundAI_node4);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | condition_bt_WrapperAI_Hero_HeroRoundAI_node4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(337);
			ifElse3.AddChild(sequence5);
			Action_bt_WrapperAI_Hero_HeroRoundAI_node338 action_bt_WrapperAI_Hero_HeroRoundAI_node3 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node338();
			action_bt_WrapperAI_Hero_HeroRoundAI_node3.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node3.SetId(338);
			sequence5.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node3);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node3.HasEvents());
			WaitFrames_bt_WrapperAI_Hero_HeroRoundAI_node445 waitFrames_bt_WrapperAI_Hero_HeroRoundAI_node = new WaitFrames_bt_WrapperAI_Hero_HeroRoundAI_node445();
			waitFrames_bt_WrapperAI_Hero_HeroRoundAI_node.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Hero_HeroRoundAI_node.SetId(445);
			sequence5.AddChild(waitFrames_bt_WrapperAI_Hero_HeroRoundAI_node);
			sequence5.SetHasEvents(sequence5.HasEvents() | waitFrames_bt_WrapperAI_Hero_HeroRoundAI_node.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(340);
			ifElse3.AddChild(sequence6);
			Action_bt_WrapperAI_Hero_HeroRoundAI_node444 action_bt_WrapperAI_Hero_HeroRoundAI_node4 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node444();
			action_bt_WrapperAI_Hero_HeroRoundAI_node4.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node4.SetId(444);
			sequence6.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node4);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node4.HasEvents());
			Action_bt_WrapperAI_Hero_HeroRoundAI_node341 action_bt_WrapperAI_Hero_HeroRoundAI_node5 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node341();
			action_bt_WrapperAI_Hero_HeroRoundAI_node5.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node5.SetId(341);
			sequence6.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node5);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node5.HasEvents());
			Action_bt_WrapperAI_Hero_HeroRoundAI_node342 action_bt_WrapperAI_Hero_HeroRoundAI_node6 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node342();
			action_bt_WrapperAI_Hero_HeroRoundAI_node6.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node6.SetId(342);
			sequence6.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node6.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence6.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | ifElse3.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(329);
			ifElse2.AddChild(sequence7);
			Action_bt_WrapperAI_Hero_HeroRoundAI_node447 action_bt_WrapperAI_Hero_HeroRoundAI_node7 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node447();
			action_bt_WrapperAI_Hero_HeroRoundAI_node7.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node7.SetId(447);
			sequence7.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node7.HasEvents());
			Action_bt_WrapperAI_Hero_HeroRoundAI_node137 action_bt_WrapperAI_Hero_HeroRoundAI_node8 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node137();
			action_bt_WrapperAI_Hero_HeroRoundAI_node8.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node8.SetId(137);
			sequence7.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node8);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node8.HasEvents());
			Action_bt_WrapperAI_Hero_HeroRoundAI_node138 action_bt_WrapperAI_Hero_HeroRoundAI_node9 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node138();
			action_bt_WrapperAI_Hero_HeroRoundAI_node9.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node9.SetId(138);
			sequence7.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node9);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node9.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | sequence7.HasEvents());
			sequence4.SetHasEvents(sequence4.HasEvents() | ifElse2.HasEvents());
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | sequence4.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition.HasEvents());
			WithPrecondition withPrecondition2 = new WithPrecondition();
			withPrecondition2.SetClassNameString("WithPrecondition");
			withPrecondition2.SetId(60);
			selectorLoop.AddChild(withPrecondition2);
			Condition_bt_WrapperAI_Hero_HeroRoundAI_node61 condition_bt_WrapperAI_Hero_HeroRoundAI_node5 = new Condition_bt_WrapperAI_Hero_HeroRoundAI_node61();
			condition_bt_WrapperAI_Hero_HeroRoundAI_node5.SetClassNameString("Condition");
			condition_bt_WrapperAI_Hero_HeroRoundAI_node5.SetId(61);
			withPrecondition2.AddChild(condition_bt_WrapperAI_Hero_HeroRoundAI_node5);
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | condition_bt_WrapperAI_Hero_HeroRoundAI_node5.HasEvents());
			Action_bt_WrapperAI_Hero_HeroRoundAI_node64 action_bt_WrapperAI_Hero_HeroRoundAI_node10 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node64();
			action_bt_WrapperAI_Hero_HeroRoundAI_node10.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node10.SetId(64);
			withPrecondition2.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node10);
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node10.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition2.HasEvents());
			WithPrecondition withPrecondition3 = new WithPrecondition();
			withPrecondition3.SetClassNameString("WithPrecondition");
			withPrecondition3.SetId(2);
			selectorLoop.AddChild(withPrecondition3);
			Condition_bt_WrapperAI_Hero_HeroRoundAI_node3 condition_bt_WrapperAI_Hero_HeroRoundAI_node6 = new Condition_bt_WrapperAI_Hero_HeroRoundAI_node3();
			condition_bt_WrapperAI_Hero_HeroRoundAI_node6.SetClassNameString("Condition");
			condition_bt_WrapperAI_Hero_HeroRoundAI_node6.SetId(3);
			withPrecondition3.AddChild(condition_bt_WrapperAI_Hero_HeroRoundAI_node6);
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | condition_bt_WrapperAI_Hero_HeroRoundAI_node6.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(59);
			withPrecondition3.AddChild(sequence8);
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(487);
			sequence8.AddChild(selector);
			Action_bt_WrapperAI_Hero_HeroRoundAI_node488 action_bt_WrapperAI_Hero_HeroRoundAI_node11 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node488();
			action_bt_WrapperAI_Hero_HeroRoundAI_node11.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node11.SetId(488);
			selector.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node11);
			selector.SetHasEvents(selector.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node11.HasEvents());
			Action_bt_WrapperAI_Hero_HeroRoundAI_node4 action_bt_WrapperAI_Hero_HeroRoundAI_node12 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node4();
			action_bt_WrapperAI_Hero_HeroRoundAI_node12.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node12.SetId(4);
			selector.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node12);
			selector.SetHasEvents(selector.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node12.HasEvents());
			sequence8.SetHasEvents(sequence8.HasEvents() | selector.HasEvents());
			DecoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node65 decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node2 = new DecoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node65();
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node2.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node2.SetId(65);
			sequence8.AddChild(decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node2);
			Noop noop2 = new Noop();
			noop2.SetClassNameString("Noop");
			noop2.SetId(66);
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node2.AddChild(noop2);
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node2.SetHasEvents(decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node2.HasEvents() | noop2.HasEvents());
			sequence8.SetHasEvents(sequence8.HasEvents() | decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node2.HasEvents());
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | sequence8.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition3.HasEvents());
			WithPrecondition withPrecondition4 = new WithPrecondition();
			withPrecondition4.SetClassNameString("WithPrecondition");
			withPrecondition4.SetId(450);
			selectorLoop.AddChild(withPrecondition4);
			Condition_bt_WrapperAI_Hero_HeroRoundAI_node454 condition_bt_WrapperAI_Hero_HeroRoundAI_node7 = new Condition_bt_WrapperAI_Hero_HeroRoundAI_node454();
			condition_bt_WrapperAI_Hero_HeroRoundAI_node7.SetClassNameString("Condition");
			condition_bt_WrapperAI_Hero_HeroRoundAI_node7.SetId(454);
			withPrecondition4.AddChild(condition_bt_WrapperAI_Hero_HeroRoundAI_node7);
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | condition_bt_WrapperAI_Hero_HeroRoundAI_node7.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(455);
			withPrecondition4.AddChild(sequence9);
			Action_bt_WrapperAI_Hero_HeroRoundAI_node456 action_bt_WrapperAI_Hero_HeroRoundAI_node13 = new Action_bt_WrapperAI_Hero_HeroRoundAI_node456();
			action_bt_WrapperAI_Hero_HeroRoundAI_node13.SetClassNameString("Action");
			action_bt_WrapperAI_Hero_HeroRoundAI_node13.SetId(456);
			sequence9.AddChild(action_bt_WrapperAI_Hero_HeroRoundAI_node13);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_WrapperAI_Hero_HeroRoundAI_node13.HasEvents());
			DecoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node457 decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node3 = new DecoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node457();
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node3.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node3.SetId(457);
			sequence9.AddChild(decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node3);
			Noop noop3 = new Noop();
			noop3.SetClassNameString("Noop");
			noop3.SetId(458);
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node3.AddChild(noop3);
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node3.SetHasEvents(decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node3.HasEvents() | noop3.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node3.HasEvents());
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | sequence9.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition4.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | selectorLoop.HasEvents());
			decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node.SetHasEvents(decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node.HasEvents() | sequence2.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorLoop_bt_WrapperAI_Hero_HeroRoundAI_node.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | sequence.HasEvents());
			return true;
		}
	}
}
