using System;

namespace behaviac
{
	public static class bt_WrapperAI_Soldier_BTSoldierPro
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("WrapperAI/Soldier/BTSoldierPro");
			bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
			bt.AddPar("uint", "p_targetID", "0", string.Empty);
			bt.AddPar("int", "p_srchRange", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
			bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
			bt.AddPar("uint", "p_CmdID", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("int", "p_skillAttackRange", "0", string.Empty);
			bt.AddPar("uint", "p_selfID", "0", string.Empty);
			bt.AddPar("uint", "p_tempTargetId", "0", string.Empty);
			bt.AddPar("short", "p_chooseTargetCount", "0", string.Empty);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			bt.AddChild(sequence);
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node106 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node106();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node.SetId(106);
			sequence.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node109 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node2 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node109();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetId(109);
			sequence.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node2);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node2.HasEvents());
			DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node14 decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node14();
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node.SetId(14);
			sequence.AddChild(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node);
			SelectorLoop selectorLoop = new SelectorLoop();
			selectorLoop.SetClassNameString("SelectorLoop");
			selectorLoop.SetId(1);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node.AddChild(selectorLoop);
			WithPrecondition withPrecondition = new WithPrecondition();
			withPrecondition.SetClassNameString("WithPrecondition");
			withPrecondition.SetId(59);
			selectorLoop.AddChild(withPrecondition);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node78 condition_bt_WrapperAI_Soldier_BTSoldierPro_node = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node78();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node.SetId(78);
			withPrecondition.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node);
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(142);
			withPrecondition.AddChild(sequence2);
			IfElse ifElse = new IfElse();
			ifElse.SetClassNameString("IfElse");
			ifElse.SetId(187);
			sequence2.AddChild(ifElse);
			And and = new And();
			and.SetClassNameString("And");
			and.SetId(188);
			ifElse.AddChild(and);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node189 condition_bt_WrapperAI_Soldier_BTSoldierPro_node2 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node189();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetId(189);
			and.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node2);
			and.SetHasEvents(and.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node2.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node190 condition_bt_WrapperAI_Soldier_BTSoldierPro_node3 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node190();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetId(190);
			and.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node3);
			and.SetHasEvents(and.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node3.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | and.HasEvents());
			Noop noop = new Noop();
			noop.SetClassNameString("Noop");
			noop.SetId(191);
			ifElse.AddChild(noop);
			ifElse.SetHasEvents(ifElse.HasEvents() | noop.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node135 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node3 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node135();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetId(135);
			ifElse.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node3);
			ifElse.SetHasEvents(ifElse.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node3.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | ifElse.HasEvents());
			IfElse ifElse2 = new IfElse();
			ifElse2.SetClassNameString("IfElse");
			ifElse2.SetId(122);
			sequence2.AddChild(ifElse2);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node124 condition_bt_WrapperAI_Soldier_BTSoldierPro_node4 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node124();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node4.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node4.SetId(124);
			ifElse2.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node4);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node4.HasEvents());
			Compute_bt_WrapperAI_Soldier_BTSoldierPro_node121 compute_bt_WrapperAI_Soldier_BTSoldierPro_node = new Compute_bt_WrapperAI_Soldier_BTSoldierPro_node121();
			compute_bt_WrapperAI_Soldier_BTSoldierPro_node.SetClassNameString("Compute");
			compute_bt_WrapperAI_Soldier_BTSoldierPro_node.SetId(121);
			ifElse2.AddChild(compute_bt_WrapperAI_Soldier_BTSoldierPro_node);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | compute_bt_WrapperAI_Soldier_BTSoldierPro_node.HasEvents());
			Noop noop2 = new Noop();
			noop2.SetClassNameString("Noop");
			noop2.SetId(134);
			ifElse2.AddChild(noop2);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | noop2.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | ifElse2.HasEvents());
			IfElse ifElse3 = new IfElse();
			ifElse3.SetClassNameString("IfElse");
			ifElse3.SetId(129);
			sequence2.AddChild(ifElse3);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node123 condition_bt_WrapperAI_Soldier_BTSoldierPro_node5 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node123();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node5.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node5.SetId(123);
			ifElse3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node5);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node5.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(9);
			ifElse3.AddChild(sequence3);
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node125 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node4 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node125();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node4.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node4.SetId(125);
			sequence3.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node4.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node126 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node5 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node126();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node5.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node5.SetId(126);
			sequence3.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node5.HasEvents());
			IfElse ifElse4 = new IfElse();
			ifElse4.SetClassNameString("IfElse");
			ifElse4.SetId(131);
			sequence3.AddChild(ifElse4);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node127 condition_bt_WrapperAI_Soldier_BTSoldierPro_node6 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node127();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node6.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node6.SetId(127);
			ifElse4.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node6);
			ifElse4.SetHasEvents(ifElse4.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node6.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node128 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node6 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node128();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node6.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node6.SetId(128);
			ifElse4.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node6);
			ifElse4.SetHasEvents(ifElse4.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node6.HasEvents());
			Noop noop3 = new Noop();
			noop3.SetClassNameString("Noop");
			noop3.SetId(133);
			ifElse4.AddChild(noop3);
			ifElse4.SetHasEvents(ifElse4.HasEvents() | noop3.HasEvents());
			sequence3.SetHasEvents(sequence3.HasEvents() | ifElse4.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence3.HasEvents());
			Noop noop4 = new Noop();
			noop4.SetClassNameString("Noop");
			noop4.SetId(130);
			ifElse3.AddChild(noop4);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | noop4.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | ifElse3.HasEvents());
			IfElse ifElse5 = new IfElse();
			ifElse5.SetClassNameString("IfElse");
			ifElse5.SetId(145);
			sequence2.AddChild(ifElse5);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node146 condition_bt_WrapperAI_Soldier_BTSoldierPro_node7 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node146();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node7.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node7.SetId(146);
			ifElse5.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node7);
			ifElse5.SetHasEvents(ifElse5.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node7.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(154);
			ifElse5.AddChild(sequence4);
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(152);
			sequence4.AddChild(selector);
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(153);
			selector.AddChild(sequence5);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node156 action_bt_WrapperAI_Soldier_BTSoldierPro_node = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node156();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node.SetId(156);
			sequence5.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node159 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node7 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node159();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node7.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node7.SetId(159);
			sequence5.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node7.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node160 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node8 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node160();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node8.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node8.SetId(160);
			sequence5.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node8);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node8.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(85);
			sequence5.AddChild(selector2);
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(86);
			selector2.AddChild(sequence6);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node712 action_bt_WrapperAI_Soldier_BTSoldierPro_node2 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node712();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetId(712);
			sequence6.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node2);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node2.HasEvents());
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(3);
			sequence6.AddChild(selector3);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node2 condition_bt_WrapperAI_Soldier_BTSoldierPro_node8 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node2();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node8.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node8.SetId(2);
			selector3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node8);
			selector3.SetHasEvents(selector3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node8.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node4 condition_bt_WrapperAI_Soldier_BTSoldierPro_node9 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node4();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node9.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node9.SetId(4);
			selector3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node9);
			selector3.SetHasEvents(selector3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node9.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node87 condition_bt_WrapperAI_Soldier_BTSoldierPro_node10 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node87();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node10.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node10.SetId(87);
			selector3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node10);
			selector3.SetHasEvents(selector3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node10.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | selector3.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node88 condition_bt_WrapperAI_Soldier_BTSoldierPro_node11 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node88();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node11.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node11.SetId(88);
			sequence6.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node11);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node11.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node89 action_bt_WrapperAI_Soldier_BTSoldierPro_node3 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node89();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetId(89);
			sequence6.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node3);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node3.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(90);
			selector2.AddChild(sequence7);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node91 condition_bt_WrapperAI_Soldier_BTSoldierPro_node12 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node91();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node12.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node12.SetId(91);
			sequence7.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node12);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node12.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node92 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node9 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node92();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node9.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node9.SetId(92);
			sequence7.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node9);
			sequence7.SetHasEvents(sequence7.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node9.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node93 condition_bt_WrapperAI_Soldier_BTSoldierPro_node13 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node93();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node13.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node13.SetId(93);
			sequence7.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node13);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node13.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node94 action_bt_WrapperAI_Soldier_BTSoldierPro_node4 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node94();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node4.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node4.SetId(94);
			sequence7.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node4);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node4.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(95);
			selector2.AddChild(sequence8);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node18 condition_bt_WrapperAI_Soldier_BTSoldierPro_node14 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node18();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node14.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node14.SetId(18);
			sequence8.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node14);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node14.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node96 condition_bt_WrapperAI_Soldier_BTSoldierPro_node15 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node96();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node15.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node15.SetId(96);
			sequence8.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node15);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node15.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node97 action_bt_WrapperAI_Soldier_BTSoldierPro_node5 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node97();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node5.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node5.SetId(97);
			sequence8.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node5);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node5.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence8.HasEvents());
			sequence5.SetHasEvents(sequence5.HasEvents() | selector2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(161);
			selector.AddChild(sequence9);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node140 action_bt_WrapperAI_Soldier_BTSoldierPro_node6 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node140();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node6.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node6.SetId(140);
			sequence9.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node6);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node6.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node162 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node10 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node162();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node10.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node10.SetId(162);
			sequence9.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node10);
			sequence9.SetHasEvents(sequence9.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node10.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node166 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node11 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node166();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node11.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node11.SetId(166);
			sequence9.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node11);
			sequence9.SetHasEvents(sequence9.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node11.HasEvents());
			Selector selector4 = new Selector();
			selector4.SetClassNameString("Selector");
			selector4.SetId(30);
			sequence9.AddChild(selector4);
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(98);
			selector4.AddChild(sequence10);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node100 action_bt_WrapperAI_Soldier_BTSoldierPro_node7 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node100();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node7.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node7.SetId(100);
			sequence10.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node7);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node7.HasEvents());
			Selector selector5 = new Selector();
			selector5.SetClassNameString("Selector");
			selector5.SetId(22);
			sequence10.AddChild(selector5);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node101 condition_bt_WrapperAI_Soldier_BTSoldierPro_node16 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node101();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node16.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node16.SetId(101);
			selector5.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node16);
			selector5.SetHasEvents(selector5.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node16.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node24 condition_bt_WrapperAI_Soldier_BTSoldierPro_node17 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node24();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node17.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node17.SetId(24);
			selector5.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node17);
			selector5.SetHasEvents(selector5.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node17.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node25 condition_bt_WrapperAI_Soldier_BTSoldierPro_node18 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node25();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node18.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node18.SetId(25);
			selector5.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node18);
			selector5.SetHasEvents(selector5.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node18.HasEvents());
			sequence10.SetHasEvents(sequence10.HasEvents() | selector5.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node26 condition_bt_WrapperAI_Soldier_BTSoldierPro_node19 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node26();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node19.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node19.SetId(26);
			sequence10.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node19);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node19.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node27 action_bt_WrapperAI_Soldier_BTSoldierPro_node8 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node27();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node8.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node8.SetId(27);
			sequence10.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node8);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node8.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(102);
			selector4.AddChild(sequence11);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node103 condition_bt_WrapperAI_Soldier_BTSoldierPro_node20 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node103();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node20.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node20.SetId(103);
			sequence11.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node20);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node20.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node104 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node12 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node104();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node12.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node12.SetId(104);
			sequence11.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node12);
			sequence11.SetHasEvents(sequence11.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node12.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node105 condition_bt_WrapperAI_Soldier_BTSoldierPro_node21 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node105();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node21.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node21.SetId(105);
			sequence11.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node21);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node21.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node33 action_bt_WrapperAI_Soldier_BTSoldierPro_node9 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node33();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node9.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node9.SetId(33);
			sequence11.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node9);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node9.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(34);
			selector4.AddChild(sequence12);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node35 condition_bt_WrapperAI_Soldier_BTSoldierPro_node22 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node35();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node22.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node22.SetId(35);
			sequence12.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node22);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node22.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node36 condition_bt_WrapperAI_Soldier_BTSoldierPro_node23 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node36();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node23.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node23.SetId(36);
			sequence12.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node23);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node23.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node37 action_bt_WrapperAI_Soldier_BTSoldierPro_node10 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node37();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node10.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node10.SetId(37);
			sequence12.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node10);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node10.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence12.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | selector4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence9.HasEvents());
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(167);
			selector.AddChild(sequence13);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node5 action_bt_WrapperAI_Soldier_BTSoldierPro_node11 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node5();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node11.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node11.SetId(5);
			sequence13.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node11);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node11.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node168 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node13 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node168();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node13.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node13.SetId(168);
			sequence13.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node13);
			sequence13.SetHasEvents(sequence13.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node13.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node172 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node14 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node172();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node14.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node14.SetId(172);
			sequence13.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node14);
			sequence13.SetHasEvents(sequence13.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node14.HasEvents());
			Selector selector6 = new Selector();
			selector6.SetClassNameString("Selector");
			selector6.SetId(31);
			sequence13.AddChild(selector6);
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(38);
			selector6.AddChild(sequence14);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node39 action_bt_WrapperAI_Soldier_BTSoldierPro_node12 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node39();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node12.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node12.SetId(39);
			sequence14.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node12);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node12.HasEvents());
			Selector selector7 = new Selector();
			selector7.SetClassNameString("Selector");
			selector7.SetId(40);
			sequence14.AddChild(selector7);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node41 condition_bt_WrapperAI_Soldier_BTSoldierPro_node24 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node41();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node24.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node24.SetId(41);
			selector7.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node24);
			selector7.SetHasEvents(selector7.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node24.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node42 condition_bt_WrapperAI_Soldier_BTSoldierPro_node25 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node42();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node25.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node25.SetId(42);
			selector7.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node25);
			selector7.SetHasEvents(selector7.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node25.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node43 condition_bt_WrapperAI_Soldier_BTSoldierPro_node26 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node43();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node26.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node26.SetId(43);
			selector7.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node26);
			selector7.SetHasEvents(selector7.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node26.HasEvents());
			sequence14.SetHasEvents(sequence14.HasEvents() | selector7.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node44 condition_bt_WrapperAI_Soldier_BTSoldierPro_node27 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node44();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node27.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node27.SetId(44);
			sequence14.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node27);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node27.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node45 action_bt_WrapperAI_Soldier_BTSoldierPro_node13 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node45();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node13.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node13.SetId(45);
			sequence14.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node13);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node13.HasEvents());
			selector6.SetHasEvents(selector6.HasEvents() | sequence14.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(46);
			selector6.AddChild(sequence15);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node47 condition_bt_WrapperAI_Soldier_BTSoldierPro_node28 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node47();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node28.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node28.SetId(47);
			sequence15.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node28);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node28.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node48 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node15 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node48();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node15.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node15.SetId(48);
			sequence15.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node15);
			sequence15.SetHasEvents(sequence15.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node15.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node49 condition_bt_WrapperAI_Soldier_BTSoldierPro_node29 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node49();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node29.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node29.SetId(49);
			sequence15.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node29);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node29.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node50 action_bt_WrapperAI_Soldier_BTSoldierPro_node14 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node50();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node14.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node14.SetId(50);
			sequence15.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node14);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node14.HasEvents());
			selector6.SetHasEvents(selector6.HasEvents() | sequence15.HasEvents());
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(51);
			selector6.AddChild(sequence16);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node52 condition_bt_WrapperAI_Soldier_BTSoldierPro_node30 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node52();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node30.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node30.SetId(52);
			sequence16.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node30);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node30.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node53 condition_bt_WrapperAI_Soldier_BTSoldierPro_node31 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node53();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node31.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node31.SetId(53);
			sequence16.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node31);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node31.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node54 action_bt_WrapperAI_Soldier_BTSoldierPro_node15 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node54();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node15.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node15.SetId(54);
			sequence16.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node15);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node15.HasEvents());
			selector6.SetHasEvents(selector6.HasEvents() | sequence16.HasEvents());
			sequence13.SetHasEvents(sequence13.HasEvents() | selector6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence13.HasEvents());
			Sequence sequence17 = new Sequence();
			sequence17.SetClassNameString("Sequence");
			sequence17.SetId(173);
			selector.AddChild(sequence17);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node82 action_bt_WrapperAI_Soldier_BTSoldierPro_node16 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node82();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node16.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node16.SetId(82);
			sequence17.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node16);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node16.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node174 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node16 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node174();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node16.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node16.SetId(174);
			sequence17.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node16);
			sequence17.SetHasEvents(sequence17.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node16.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node178 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node17 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node178();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node17.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node17.SetId(178);
			sequence17.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node17);
			sequence17.SetHasEvents(sequence17.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node17.HasEvents());
			Selector selector8 = new Selector();
			selector8.SetClassNameString("Selector");
			selector8.SetId(32);
			sequence17.AddChild(selector8);
			Sequence sequence18 = new Sequence();
			sequence18.SetClassNameString("Sequence");
			sequence18.SetId(55);
			selector8.AddChild(sequence18);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node56 action_bt_WrapperAI_Soldier_BTSoldierPro_node17 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node56();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node17.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node17.SetId(56);
			sequence18.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node17);
			sequence18.SetHasEvents(sequence18.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node17.HasEvents());
			Selector selector9 = new Selector();
			selector9.SetClassNameString("Selector");
			selector9.SetId(57);
			sequence18.AddChild(selector9);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node58 condition_bt_WrapperAI_Soldier_BTSoldierPro_node32 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node58();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node32.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node32.SetId(58);
			selector9.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node32);
			selector9.SetHasEvents(selector9.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node32.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node60 condition_bt_WrapperAI_Soldier_BTSoldierPro_node33 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node60();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node33.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node33.SetId(60);
			selector9.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node33);
			selector9.SetHasEvents(selector9.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node33.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node61 condition_bt_WrapperAI_Soldier_BTSoldierPro_node34 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node61();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node34.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node34.SetId(61);
			selector9.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node34);
			selector9.SetHasEvents(selector9.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node34.HasEvents());
			sequence18.SetHasEvents(sequence18.HasEvents() | selector9.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node62 condition_bt_WrapperAI_Soldier_BTSoldierPro_node35 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node62();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node35.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node35.SetId(62);
			sequence18.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node35);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node35.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node63 action_bt_WrapperAI_Soldier_BTSoldierPro_node18 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node63();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node18.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node18.SetId(63);
			sequence18.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node18);
			sequence18.SetHasEvents(sequence18.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node18.HasEvents());
			selector8.SetHasEvents(selector8.HasEvents() | sequence18.HasEvents());
			Sequence sequence19 = new Sequence();
			sequence19.SetClassNameString("Sequence");
			sequence19.SetId(64);
			selector8.AddChild(sequence19);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node65 condition_bt_WrapperAI_Soldier_BTSoldierPro_node36 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node65();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node36.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node36.SetId(65);
			sequence19.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node36);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node36.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node66 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node18 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node66();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node18.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node18.SetId(66);
			sequence19.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node18);
			sequence19.SetHasEvents(sequence19.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node18.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node67 condition_bt_WrapperAI_Soldier_BTSoldierPro_node37 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node67();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node37.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node37.SetId(67);
			sequence19.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node37);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node37.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node68 action_bt_WrapperAI_Soldier_BTSoldierPro_node19 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node68();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node19.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node19.SetId(68);
			sequence19.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node19);
			sequence19.SetHasEvents(sequence19.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node19.HasEvents());
			selector8.SetHasEvents(selector8.HasEvents() | sequence19.HasEvents());
			Sequence sequence20 = new Sequence();
			sequence20.SetClassNameString("Sequence");
			sequence20.SetId(69);
			selector8.AddChild(sequence20);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node70 condition_bt_WrapperAI_Soldier_BTSoldierPro_node38 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node70();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node38.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node38.SetId(70);
			sequence20.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node38);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node38.HasEvents());
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node71 condition_bt_WrapperAI_Soldier_BTSoldierPro_node39 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node71();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node39.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node39.SetId(71);
			sequence20.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node39);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node39.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node72 action_bt_WrapperAI_Soldier_BTSoldierPro_node20 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node72();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node20.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node20.SetId(72);
			sequence20.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node20);
			sequence20.SetHasEvents(sequence20.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node20.HasEvents());
			selector8.SetHasEvents(selector8.HasEvents() | sequence20.HasEvents());
			sequence17.SetHasEvents(sequence17.HasEvents() | selector8.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence17.HasEvents());
			IfElse ifElse6 = new IfElse();
			ifElse6.SetClassNameString("IfElse");
			ifElse6.SetId(6);
			selector.AddChild(ifElse6);
			Sequence sequence21 = new Sequence();
			sequence21.SetClassNameString("Sequence");
			sequence21.SetId(281);
			ifElse6.AddChild(sequence21);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node429 condition_bt_WrapperAI_Soldier_BTSoldierPro_node40 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node429();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node40.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node40.SetId(429);
			sequence21.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node40);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node40.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node430 action_bt_WrapperAI_Soldier_BTSoldierPro_node21 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node430();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node21.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node21.SetId(430);
			sequence21.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node21);
			sequence21.SetHasEvents(sequence21.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node21.HasEvents());
			ifElse6.SetHasEvents(ifElse6.HasEvents() | sequence21.HasEvents());
			Sequence sequence22 = new Sequence();
			sequence22.SetClassNameString("Sequence");
			sequence22.SetId(431);
			ifElse6.AddChild(sequence22);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node444 action_bt_WrapperAI_Soldier_BTSoldierPro_node22 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node444();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node22.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node22.SetId(444);
			sequence22.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node22);
			sequence22.SetHasEvents(sequence22.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node22.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node432 action_bt_WrapperAI_Soldier_BTSoldierPro_node23 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node432();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node23.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node23.SetId(432);
			sequence22.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node23);
			sequence22.SetHasEvents(sequence22.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node23.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node438 action_bt_WrapperAI_Soldier_BTSoldierPro_node24 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node438();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node24.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node24.SetId(438);
			sequence22.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node24);
			sequence22.SetHasEvents(sequence22.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node24.HasEvents());
			ifElse6.SetHasEvents(ifElse6.HasEvents() | sequence22.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node439 action_bt_WrapperAI_Soldier_BTSoldierPro_node25 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node439();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node25.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node25.SetId(439);
			ifElse6.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node25);
			ifElse6.SetHasEvents(ifElse6.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node25.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | ifElse6.HasEvents());
			sequence4.SetHasEvents(sequence4.HasEvents() | selector.HasEvents());
			Sequence sequence23 = new Sequence();
			sequence23.SetClassNameString("Sequence");
			sequence23.SetId(148);
			sequence4.AddChild(sequence23);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node74 action_bt_WrapperAI_Soldier_BTSoldierPro_node26 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node74();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node26.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node26.SetId(74);
			sequence23.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node26);
			sequence23.SetHasEvents(sequence23.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node26.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node20 action_bt_WrapperAI_Soldier_BTSoldierPro_node27 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node20();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node27.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node27.SetId(20);
			sequence23.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node27);
			sequence23.SetHasEvents(sequence23.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node27.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node99 decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node99();
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node.SetId(99);
			sequence23.AddChild(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node132 condition_bt_WrapperAI_Soldier_BTSoldierPro_node41 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node132();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node41.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node41.SetId(132);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node41);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node41.HasEvents());
			sequence23.SetHasEvents(sequence23.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node.HasEvents());
			sequence4.SetHasEvents(sequence4.HasEvents() | sequence23.HasEvents());
			ifElse5.SetHasEvents(ifElse5.HasEvents() | sequence4.HasEvents());
			Sequence sequence24 = new Sequence();
			sequence24.SetClassNameString("Sequence");
			sequence24.SetId(7);
			ifElse5.AddChild(sequence24);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node8 action_bt_WrapperAI_Soldier_BTSoldierPro_node28 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node8();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node28.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node28.SetId(8);
			sequence24.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node28);
			sequence24.SetHasEvents(sequence24.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node28.HasEvents());
			IfElse ifElse7 = new IfElse();
			ifElse7.SetClassNameString("IfElse");
			ifElse7.SetId(10);
			sequence24.AddChild(ifElse7);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node11 condition_bt_WrapperAI_Soldier_BTSoldierPro_node42 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node11();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node42.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node42.SetId(11);
			ifElse7.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node42);
			ifElse7.SetHasEvents(ifElse7.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node42.HasEvents());
			Sequence sequence25 = new Sequence();
			sequence25.SetClassNameString("Sequence");
			sequence25.SetId(12);
			ifElse7.AddChild(sequence25);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node13 action_bt_WrapperAI_Soldier_BTSoldierPro_node29 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node13();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node29.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node29.SetId(13);
			sequence25.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node29);
			sequence25.SetHasEvents(sequence25.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node29.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node21 action_bt_WrapperAI_Soldier_BTSoldierPro_node30 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node21();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node30.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node30.SetId(21);
			sequence25.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node30);
			sequence25.SetHasEvents(sequence25.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node30.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node15 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node19 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node15();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node19.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node19.SetId(15);
			sequence25.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node19);
			sequence25.SetHasEvents(sequence25.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node19.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node16 action_bt_WrapperAI_Soldier_BTSoldierPro_node31 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node16();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node31.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node31.SetId(16);
			sequence25.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node31);
			sequence25.SetHasEvents(sequence25.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node31.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node17 action_bt_WrapperAI_Soldier_BTSoldierPro_node32 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node17();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node32.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node32.SetId(17);
			sequence25.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node32);
			sequence25.SetHasEvents(sequence25.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node32.HasEvents());
			ifElse7.SetHasEvents(ifElse7.HasEvents() | sequence25.HasEvents());
			Sequence sequence26 = new Sequence();
			sequence26.SetClassNameString("Sequence");
			sequence26.SetId(19);
			ifElse7.AddChild(sequence26);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node23 action_bt_WrapperAI_Soldier_BTSoldierPro_node33 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node23();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node33.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node33.SetId(23);
			sequence26.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node33);
			sequence26.SetHasEvents(sequence26.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node33.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node28 action_bt_WrapperAI_Soldier_BTSoldierPro_node34 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node28();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node34.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node34.SetId(28);
			sequence26.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node34);
			sequence26.SetHasEvents(sequence26.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node34.HasEvents());
			WaitFrames_bt_WrapperAI_Soldier_BTSoldierPro_node29 waitFrames_bt_WrapperAI_Soldier_BTSoldierPro_node = new WaitFrames_bt_WrapperAI_Soldier_BTSoldierPro_node29();
			waitFrames_bt_WrapperAI_Soldier_BTSoldierPro_node.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Soldier_BTSoldierPro_node.SetId(29);
			sequence26.AddChild(waitFrames_bt_WrapperAI_Soldier_BTSoldierPro_node);
			sequence26.SetHasEvents(sequence26.HasEvents() | waitFrames_bt_WrapperAI_Soldier_BTSoldierPro_node.HasEvents());
			ifElse7.SetHasEvents(ifElse7.HasEvents() | sequence26.HasEvents());
			sequence24.SetHasEvents(sequence24.HasEvents() | ifElse7.HasEvents());
			ifElse5.SetHasEvents(ifElse5.HasEvents() | sequence24.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | ifElse5.HasEvents());
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | sequence2.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition.HasEvents());
			WithPrecondition withPrecondition2 = new WithPrecondition();
			withPrecondition2.SetClassNameString("WithPrecondition");
			withPrecondition2.SetId(515);
			selectorLoop.AddChild(withPrecondition2);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node516 condition_bt_WrapperAI_Soldier_BTSoldierPro_node43 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node516();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node43.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node43.SetId(516);
			withPrecondition2.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node43);
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node43.HasEvents());
			Selector selector10 = new Selector();
			selector10.SetClassNameString("Selector");
			selector10.SetId(73);
			withPrecondition2.AddChild(selector10);
			Sequence sequence27 = new Sequence();
			sequence27.SetClassNameString("Sequence");
			sequence27.SetId(75);
			selector10.AddChild(sequence27);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node76 condition_bt_WrapperAI_Soldier_BTSoldierPro_node44 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node76();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node44.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node44.SetId(76);
			sequence27.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node44);
			sequence27.SetHasEvents(sequence27.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node44.HasEvents());
			Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node77 assignment_bt_WrapperAI_Soldier_BTSoldierPro_node20 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node77();
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node20.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Soldier_BTSoldierPro_node20.SetId(77);
			sequence27.AddChild(assignment_bt_WrapperAI_Soldier_BTSoldierPro_node20);
			sequence27.SetHasEvents(sequence27.HasEvents() | assignment_bt_WrapperAI_Soldier_BTSoldierPro_node20.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node79 action_bt_WrapperAI_Soldier_BTSoldierPro_node35 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node79();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node35.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node35.SetId(79);
			sequence27.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node35);
			sequence27.SetHasEvents(sequence27.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node35.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node80 action_bt_WrapperAI_Soldier_BTSoldierPro_node36 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node80();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node36.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node36.SetId(80);
			sequence27.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node36);
			sequence27.SetHasEvents(sequence27.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node36.HasEvents());
			selector10.SetHasEvents(selector10.HasEvents() | sequence27.HasEvents());
			Sequence sequence28 = new Sequence();
			sequence28.SetClassNameString("Sequence");
			sequence28.SetId(517);
			selector10.AddChild(sequence28);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node81 condition_bt_WrapperAI_Soldier_BTSoldierPro_node45 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node81();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node45.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node45.SetId(81);
			sequence28.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node45);
			sequence28.SetHasEvents(sequence28.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node45.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node518 action_bt_WrapperAI_Soldier_BTSoldierPro_node37 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node518();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node37.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node37.SetId(518);
			sequence28.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node37);
			sequence28.SetHasEvents(sequence28.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node37.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node519 action_bt_WrapperAI_Soldier_BTSoldierPro_node38 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node519();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node38.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node38.SetId(519);
			sequence28.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node38);
			sequence28.SetHasEvents(sequence28.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node38.HasEvents());
			IfElse ifElse8 = new IfElse();
			ifElse8.SetClassNameString("IfElse");
			ifElse8.SetId(520);
			sequence28.AddChild(ifElse8);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node521 condition_bt_WrapperAI_Soldier_BTSoldierPro_node46 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node521();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node46.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node46.SetId(521);
			ifElse8.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node46);
			ifElse8.SetHasEvents(ifElse8.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node46.HasEvents());
			Sequence sequence29 = new Sequence();
			sequence29.SetClassNameString("Sequence");
			sequence29.SetId(522);
			ifElse8.AddChild(sequence29);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node523 action_bt_WrapperAI_Soldier_BTSoldierPro_node39 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node523();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node39.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node39.SetId(523);
			sequence29.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node39);
			sequence29.SetHasEvents(sequence29.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node39.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node524 action_bt_WrapperAI_Soldier_BTSoldierPro_node40 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node524();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node40.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node40.SetId(524);
			sequence29.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node40);
			sequence29.SetHasEvents(sequence29.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node40.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node526 action_bt_WrapperAI_Soldier_BTSoldierPro_node41 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node526();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node41.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node41.SetId(526);
			sequence29.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node41);
			sequence29.SetHasEvents(sequence29.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node41.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node83 action_bt_WrapperAI_Soldier_BTSoldierPro_node42 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node83();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node42.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node42.SetId(83);
			sequence29.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node42);
			sequence29.SetHasEvents(sequence29.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node42.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node530 action_bt_WrapperAI_Soldier_BTSoldierPro_node43 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node530();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node43.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node43.SetId(530);
			sequence29.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node43);
			sequence29.SetHasEvents(sequence29.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node43.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node531 decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node2 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node531();
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetId(531);
			sequence29.AddChild(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node2);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node532 condition_bt_WrapperAI_Soldier_BTSoldierPro_node47 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node532();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node47.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node47.SetId(532);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node2.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node47);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node2.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node47.HasEvents());
			sequence29.SetHasEvents(sequence29.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node2.HasEvents());
			ifElse8.SetHasEvents(ifElse8.HasEvents() | sequence29.HasEvents());
			Sequence sequence30 = new Sequence();
			sequence30.SetClassNameString("Sequence");
			sequence30.SetId(533);
			ifElse8.AddChild(sequence30);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node84 action_bt_WrapperAI_Soldier_BTSoldierPro_node44 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node84();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node44.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node44.SetId(84);
			sequence30.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node44);
			sequence30.SetHasEvents(sequence30.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node44.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node535 action_bt_WrapperAI_Soldier_BTSoldierPro_node45 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node535();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node45.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node45.SetId(535);
			sequence30.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node45);
			sequence30.SetHasEvents(sequence30.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node45.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node536 decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node3 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node536();
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetId(536);
			sequence30.AddChild(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node3);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node537 condition_bt_WrapperAI_Soldier_BTSoldierPro_node48 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node537();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node48.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node48.SetId(537);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node48);
			decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node48.HasEvents());
			sequence30.SetHasEvents(sequence30.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node3.HasEvents());
			ifElse8.SetHasEvents(ifElse8.HasEvents() | sequence30.HasEvents());
			sequence28.SetHasEvents(sequence28.HasEvents() | ifElse8.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node538 action_bt_WrapperAI_Soldier_BTSoldierPro_node46 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node538();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node46.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node46.SetId(538);
			sequence28.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node46);
			sequence28.SetHasEvents(sequence28.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node46.HasEvents());
			selector10.SetHasEvents(selector10.HasEvents() | sequence28.HasEvents());
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | selector10.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition2.HasEvents());
			WithPrecondition withPrecondition3 = new WithPrecondition();
			withPrecondition3.SetClassNameString("WithPrecondition");
			withPrecondition3.SetId(110);
			selectorLoop.AddChild(withPrecondition3);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node111 condition_bt_WrapperAI_Soldier_BTSoldierPro_node49 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node111();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node49.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node49.SetId(111);
			withPrecondition3.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node49);
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node49.HasEvents());
			Sequence sequence31 = new Sequence();
			sequence31.SetClassNameString("Sequence");
			sequence31.SetId(112);
			withPrecondition3.AddChild(sequence31);
			Selector selector11 = new Selector();
			selector11.SetClassNameString("Selector");
			selector11.SetId(487);
			sequence31.AddChild(selector11);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node488 action_bt_WrapperAI_Soldier_BTSoldierPro_node47 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node488();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node47.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node47.SetId(488);
			selector11.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node47);
			selector11.SetHasEvents(selector11.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node47.HasEvents());
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node113 action_bt_WrapperAI_Soldier_BTSoldierPro_node48 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node113();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node48.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node48.SetId(113);
			selector11.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node48);
			selector11.SetHasEvents(selector11.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node48.HasEvents());
			sequence31.SetHasEvents(sequence31.HasEvents() | selector11.HasEvents());
			DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node114 decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node2 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node114();
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetId(114);
			sequence31.AddChild(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node2);
			Noop noop5 = new Noop();
			noop5.SetClassNameString("Noop");
			noop5.SetId(115);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node2.AddChild(noop5);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node2.SetHasEvents(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node2.HasEvents() | noop5.HasEvents());
			sequence31.SetHasEvents(sequence31.HasEvents() | decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node2.HasEvents());
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | sequence31.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition3.HasEvents());
			WithPrecondition withPrecondition4 = new WithPrecondition();
			withPrecondition4.SetClassNameString("WithPrecondition");
			withPrecondition4.SetId(450);
			selectorLoop.AddChild(withPrecondition4);
			Condition_bt_WrapperAI_Soldier_BTSoldierPro_node454 condition_bt_WrapperAI_Soldier_BTSoldierPro_node50 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node454();
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node50.SetClassNameString("Condition");
			condition_bt_WrapperAI_Soldier_BTSoldierPro_node50.SetId(454);
			withPrecondition4.AddChild(condition_bt_WrapperAI_Soldier_BTSoldierPro_node50);
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | condition_bt_WrapperAI_Soldier_BTSoldierPro_node50.HasEvents());
			Sequence sequence32 = new Sequence();
			sequence32.SetClassNameString("Sequence");
			sequence32.SetId(455);
			withPrecondition4.AddChild(sequence32);
			Action_bt_WrapperAI_Soldier_BTSoldierPro_node456 action_bt_WrapperAI_Soldier_BTSoldierPro_node49 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node456();
			action_bt_WrapperAI_Soldier_BTSoldierPro_node49.SetClassNameString("Action");
			action_bt_WrapperAI_Soldier_BTSoldierPro_node49.SetId(456);
			sequence32.AddChild(action_bt_WrapperAI_Soldier_BTSoldierPro_node49);
			sequence32.SetHasEvents(sequence32.HasEvents() | action_bt_WrapperAI_Soldier_BTSoldierPro_node49.HasEvents());
			DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node457 decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node3 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node457();
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetId(457);
			sequence32.AddChild(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node3);
			Noop noop6 = new Noop();
			noop6.SetClassNameString("Noop");
			noop6.SetId(458);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node3.AddChild(noop6);
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node3.SetHasEvents(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node3.HasEvents() | noop6.HasEvents());
			sequence32.SetHasEvents(sequence32.HasEvents() | decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node3.HasEvents());
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | sequence32.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition4.HasEvents());
			decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node.SetHasEvents(decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node.HasEvents() | selectorLoop.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | sequence.HasEvents());
			return true;
		}
	}
}
