using System;

namespace behaviac
{
	public static class bt_WrapperAI_TowerExampleInput
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("WrapperAI/TowerExampleInput");
			bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
			bt.AddPar("uint", "p_targetID", "0", string.Empty);
			bt.AddPar("int", "p_srchRange", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
			bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
			bt.AddPar("uint", "p_CmdID", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("int", "p_organType", "0", string.Empty);
			bt.AddPar("int", "p_bornWaitFrame", "0", string.Empty);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			bt.AddChild(sequence);
			Assignment_bt_WrapperAI_TowerExampleInput_node82 assignment_bt_WrapperAI_TowerExampleInput_node = new Assignment_bt_WrapperAI_TowerExampleInput_node82();
			assignment_bt_WrapperAI_TowerExampleInput_node.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_TowerExampleInput_node.SetId(82);
			sequence.AddChild(assignment_bt_WrapperAI_TowerExampleInput_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_TowerExampleInput_node.HasEvents());
			Assignment_bt_WrapperAI_TowerExampleInput_node33 assignment_bt_WrapperAI_TowerExampleInput_node2 = new Assignment_bt_WrapperAI_TowerExampleInput_node33();
			assignment_bt_WrapperAI_TowerExampleInput_node2.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_TowerExampleInput_node2.SetId(33);
			sequence.AddChild(assignment_bt_WrapperAI_TowerExampleInput_node2);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_TowerExampleInput_node2.HasEvents());
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(48);
			sequence.AddChild(selector);
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(49);
			selector.AddChild(sequence2);
			Condition_bt_WrapperAI_TowerExampleInput_node36 condition_bt_WrapperAI_TowerExampleInput_node = new Condition_bt_WrapperAI_TowerExampleInput_node36();
			condition_bt_WrapperAI_TowerExampleInput_node.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node.SetId(36);
			sequence2.AddChild(condition_bt_WrapperAI_TowerExampleInput_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node.HasEvents());
			Assignment_bt_WrapperAI_TowerExampleInput_node34 assignment_bt_WrapperAI_TowerExampleInput_node3 = new Assignment_bt_WrapperAI_TowerExampleInput_node34();
			assignment_bt_WrapperAI_TowerExampleInput_node3.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_TowerExampleInput_node3.SetId(34);
			sequence2.AddChild(assignment_bt_WrapperAI_TowerExampleInput_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | assignment_bt_WrapperAI_TowerExampleInput_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(50);
			selector.AddChild(sequence3);
			Condition_bt_WrapperAI_TowerExampleInput_node39 condition_bt_WrapperAI_TowerExampleInput_node2 = new Condition_bt_WrapperAI_TowerExampleInput_node39();
			condition_bt_WrapperAI_TowerExampleInput_node2.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node2.SetId(39);
			sequence3.AddChild(condition_bt_WrapperAI_TowerExampleInput_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node2.HasEvents());
			Assignment_bt_WrapperAI_TowerExampleInput_node37 assignment_bt_WrapperAI_TowerExampleInput_node4 = new Assignment_bt_WrapperAI_TowerExampleInput_node37();
			assignment_bt_WrapperAI_TowerExampleInput_node4.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_TowerExampleInput_node4.SetId(37);
			sequence3.AddChild(assignment_bt_WrapperAI_TowerExampleInput_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | assignment_bt_WrapperAI_TowerExampleInput_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(51);
			selector.AddChild(sequence4);
			Condition_bt_WrapperAI_TowerExampleInput_node42 condition_bt_WrapperAI_TowerExampleInput_node3 = new Condition_bt_WrapperAI_TowerExampleInput_node42();
			condition_bt_WrapperAI_TowerExampleInput_node3.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node3.SetId(42);
			sequence4.AddChild(condition_bt_WrapperAI_TowerExampleInput_node3);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node3.HasEvents());
			Assignment_bt_WrapperAI_TowerExampleInput_node40 assignment_bt_WrapperAI_TowerExampleInput_node5 = new Assignment_bt_WrapperAI_TowerExampleInput_node40();
			assignment_bt_WrapperAI_TowerExampleInput_node5.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_TowerExampleInput_node5.SetId(40);
			sequence4.AddChild(assignment_bt_WrapperAI_TowerExampleInput_node5);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_WrapperAI_TowerExampleInput_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(52);
			selector.AddChild(sequence5);
			Condition_bt_WrapperAI_TowerExampleInput_node45 condition_bt_WrapperAI_TowerExampleInput_node4 = new Condition_bt_WrapperAI_TowerExampleInput_node45();
			condition_bt_WrapperAI_TowerExampleInput_node4.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node4.SetId(45);
			sequence5.AddChild(condition_bt_WrapperAI_TowerExampleInput_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node4.HasEvents());
			Assignment_bt_WrapperAI_TowerExampleInput_node43 assignment_bt_WrapperAI_TowerExampleInput_node6 = new Assignment_bt_WrapperAI_TowerExampleInput_node43();
			assignment_bt_WrapperAI_TowerExampleInput_node6.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_TowerExampleInput_node6.SetId(43);
			sequence5.AddChild(assignment_bt_WrapperAI_TowerExampleInput_node6);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_WrapperAI_TowerExampleInput_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | selector.HasEvents());
			Assignment_bt_WrapperAI_TowerExampleInput_node47 assignment_bt_WrapperAI_TowerExampleInput_node7 = new Assignment_bt_WrapperAI_TowerExampleInput_node47();
			assignment_bt_WrapperAI_TowerExampleInput_node7.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_TowerExampleInput_node7.SetId(47);
			sequence.AddChild(assignment_bt_WrapperAI_TowerExampleInput_node7);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_TowerExampleInput_node7.HasEvents());
			WaitFrames_bt_WrapperAI_TowerExampleInput_node46 waitFrames_bt_WrapperAI_TowerExampleInput_node = new WaitFrames_bt_WrapperAI_TowerExampleInput_node46();
			waitFrames_bt_WrapperAI_TowerExampleInput_node.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_TowerExampleInput_node.SetId(46);
			sequence.AddChild(waitFrames_bt_WrapperAI_TowerExampleInput_node);
			sequence.SetHasEvents(sequence.HasEvents() | waitFrames_bt_WrapperAI_TowerExampleInput_node.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(14);
			sequence.AddChild(selector2);
			Action_bt_WrapperAI_TowerExampleInput_node29 action_bt_WrapperAI_TowerExampleInput_node = new Action_bt_WrapperAI_TowerExampleInput_node29();
			action_bt_WrapperAI_TowerExampleInput_node.SetClassNameString("Action");
			action_bt_WrapperAI_TowerExampleInput_node.SetId(29);
			selector2.AddChild(action_bt_WrapperAI_TowerExampleInput_node);
			selector2.SetHasEvents(selector2.HasEvents() | action_bt_WrapperAI_TowerExampleInput_node.HasEvents());
			True @true = new True();
			@true.SetClassNameString("True");
			@true.SetId(30);
			selector2.AddChild(@true);
			selector2.SetHasEvents(selector2.HasEvents() | @true.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | selector2.HasEvents());
			DecoratorLoop_bt_WrapperAI_TowerExampleInput_node28 decoratorLoop_bt_WrapperAI_TowerExampleInput_node = new DecoratorLoop_bt_WrapperAI_TowerExampleInput_node28();
			decoratorLoop_bt_WrapperAI_TowerExampleInput_node.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_TowerExampleInput_node.SetId(28);
			sequence.AddChild(decoratorLoop_bt_WrapperAI_TowerExampleInput_node);
			SelectorLoop selectorLoop = new SelectorLoop();
			selectorLoop.SetClassNameString("SelectorLoop");
			selectorLoop.SetId(1);
			decoratorLoop_bt_WrapperAI_TowerExampleInput_node.AddChild(selectorLoop);
			WithPrecondition withPrecondition = new WithPrecondition();
			withPrecondition.SetClassNameString("WithPrecondition");
			withPrecondition.SetId(11);
			selectorLoop.AddChild(withPrecondition);
			Condition_bt_WrapperAI_TowerExampleInput_node12 condition_bt_WrapperAI_TowerExampleInput_node5 = new Condition_bt_WrapperAI_TowerExampleInput_node12();
			condition_bt_WrapperAI_TowerExampleInput_node5.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node5.SetId(12);
			withPrecondition.AddChild(condition_bt_WrapperAI_TowerExampleInput_node5);
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(13);
			withPrecondition.AddChild(sequence6);
			IfElse ifElse = new IfElse();
			ifElse.SetClassNameString("IfElse");
			ifElse.SetId(9);
			sequence6.AddChild(ifElse);
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(26);
			ifElse.AddChild(sequence7);
			Condition_bt_WrapperAI_TowerExampleInput_node15 condition_bt_WrapperAI_TowerExampleInput_node6 = new Condition_bt_WrapperAI_TowerExampleInput_node15();
			condition_bt_WrapperAI_TowerExampleInput_node6.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node6.SetId(15);
			sequence7.AddChild(condition_bt_WrapperAI_TowerExampleInput_node6);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node6.HasEvents());
			Condition_bt_WrapperAI_TowerExampleInput_node27 condition_bt_WrapperAI_TowerExampleInput_node7 = new Condition_bt_WrapperAI_TowerExampleInput_node27();
			condition_bt_WrapperAI_TowerExampleInput_node7.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node7.SetId(27);
			sequence7.AddChild(condition_bt_WrapperAI_TowerExampleInput_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node7.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(17);
			ifElse.AddChild(sequence8);
			Action_bt_WrapperAI_TowerExampleInput_node16 action_bt_WrapperAI_TowerExampleInput_node2 = new Action_bt_WrapperAI_TowerExampleInput_node16();
			action_bt_WrapperAI_TowerExampleInput_node2.SetClassNameString("Action");
			action_bt_WrapperAI_TowerExampleInput_node2.SetId(16);
			sequence8.AddChild(action_bt_WrapperAI_TowerExampleInput_node2);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_TowerExampleInput_node2.HasEvents());
			Assignment_bt_WrapperAI_TowerExampleInput_node18 assignment_bt_WrapperAI_TowerExampleInput_node8 = new Assignment_bt_WrapperAI_TowerExampleInput_node18();
			assignment_bt_WrapperAI_TowerExampleInput_node8.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_TowerExampleInput_node8.SetId(18);
			sequence8.AddChild(assignment_bt_WrapperAI_TowerExampleInput_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | assignment_bt_WrapperAI_TowerExampleInput_node8.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | sequence8.HasEvents());
			Noop noop = new Noop();
			noop.SetClassNameString("Noop");
			noop.SetId(19);
			ifElse.AddChild(noop);
			ifElse.SetHasEvents(ifElse.HasEvents() | noop.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | ifElse.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(81);
			sequence6.AddChild(sequence9);
			IfElse ifElse2 = new IfElse();
			ifElse2.SetClassNameString("IfElse");
			ifElse2.SetId(10);
			sequence9.AddChild(ifElse2);
			And and = new And();
			and.SetClassNameString("And");
			and.SetId(21);
			ifElse2.AddChild(and);
			Condition_bt_WrapperAI_TowerExampleInput_node20 condition_bt_WrapperAI_TowerExampleInput_node8 = new Condition_bt_WrapperAI_TowerExampleInput_node20();
			condition_bt_WrapperAI_TowerExampleInput_node8.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node8.SetId(20);
			and.AddChild(condition_bt_WrapperAI_TowerExampleInput_node8);
			and.SetHasEvents(and.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node8.HasEvents());
			Condition_bt_WrapperAI_TowerExampleInput_node22 condition_bt_WrapperAI_TowerExampleInput_node9 = new Condition_bt_WrapperAI_TowerExampleInput_node22();
			condition_bt_WrapperAI_TowerExampleInput_node9.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node9.SetId(22);
			and.AddChild(condition_bt_WrapperAI_TowerExampleInput_node9);
			and.SetHasEvents(and.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node9.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | and.HasEvents());
			Noop noop2 = new Noop();
			noop2.SetClassNameString("Noop");
			noop2.SetId(23);
			ifElse2.AddChild(noop2);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | noop2.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(24);
			ifElse2.AddChild(sequence10);
			Action_bt_WrapperAI_TowerExampleInput_node25 action_bt_WrapperAI_TowerExampleInput_node3 = new Action_bt_WrapperAI_TowerExampleInput_node25();
			action_bt_WrapperAI_TowerExampleInput_node3.SetClassNameString("Action");
			action_bt_WrapperAI_TowerExampleInput_node3.SetId(25);
			sequence10.AddChild(action_bt_WrapperAI_TowerExampleInput_node3);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_TowerExampleInput_node3.HasEvents());
			Assignment_bt_WrapperAI_TowerExampleInput_node83 assignment_bt_WrapperAI_TowerExampleInput_node9 = new Assignment_bt_WrapperAI_TowerExampleInput_node83();
			assignment_bt_WrapperAI_TowerExampleInput_node9.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_TowerExampleInput_node9.SetId(83);
			sequence10.AddChild(assignment_bt_WrapperAI_TowerExampleInput_node9);
			sequence10.SetHasEvents(sequence10.HasEvents() | assignment_bt_WrapperAI_TowerExampleInput_node9.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | sequence10.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | ifElse2.HasEvents());
			IfElse ifElse3 = new IfElse();
			ifElse3.SetClassNameString("IfElse");
			ifElse3.SetId(84);
			sequence9.AddChild(ifElse3);
			Condition_bt_WrapperAI_TowerExampleInput_node85 condition_bt_WrapperAI_TowerExampleInput_node10 = new Condition_bt_WrapperAI_TowerExampleInput_node85();
			condition_bt_WrapperAI_TowerExampleInput_node10.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node10.SetId(85);
			ifElse3.AddChild(condition_bt_WrapperAI_TowerExampleInput_node10);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(86);
			ifElse3.AddChild(sequence11);
			Action_bt_WrapperAI_TowerExampleInput_node140 action_bt_WrapperAI_TowerExampleInput_node4 = new Action_bt_WrapperAI_TowerExampleInput_node140();
			action_bt_WrapperAI_TowerExampleInput_node4.SetClassNameString("Action");
			action_bt_WrapperAI_TowerExampleInput_node4.SetId(140);
			sequence11.AddChild(action_bt_WrapperAI_TowerExampleInput_node4);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_TowerExampleInput_node4.HasEvents());
			Action_bt_WrapperAI_TowerExampleInput_node87 action_bt_WrapperAI_TowerExampleInput_node5 = new Action_bt_WrapperAI_TowerExampleInput_node87();
			action_bt_WrapperAI_TowerExampleInput_node5.SetClassNameString("Action");
			action_bt_WrapperAI_TowerExampleInput_node5.SetId(87);
			sequence11.AddChild(action_bt_WrapperAI_TowerExampleInput_node5);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_TowerExampleInput_node5.HasEvents());
			Action_bt_WrapperAI_TowerExampleInput_node88 action_bt_WrapperAI_TowerExampleInput_node6 = new Action_bt_WrapperAI_TowerExampleInput_node88();
			action_bt_WrapperAI_TowerExampleInput_node6.SetClassNameString("Action");
			action_bt_WrapperAI_TowerExampleInput_node6.SetId(88);
			sequence11.AddChild(action_bt_WrapperAI_TowerExampleInput_node6);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_TowerExampleInput_node6.HasEvents());
			Action_bt_WrapperAI_TowerExampleInput_node91 action_bt_WrapperAI_TowerExampleInput_node7 = new Action_bt_WrapperAI_TowerExampleInput_node91();
			action_bt_WrapperAI_TowerExampleInput_node7.SetClassNameString("Action");
			action_bt_WrapperAI_TowerExampleInput_node7.SetId(91);
			sequence11.AddChild(action_bt_WrapperAI_TowerExampleInput_node7);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_TowerExampleInput_node7.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_TowerExampleInput_node92 decoratorLoopUntil_bt_WrapperAI_TowerExampleInput_node = new DecoratorLoopUntil_bt_WrapperAI_TowerExampleInput_node92();
			decoratorLoopUntil_bt_WrapperAI_TowerExampleInput_node.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_TowerExampleInput_node.SetId(92);
			sequence11.AddChild(decoratorLoopUntil_bt_WrapperAI_TowerExampleInput_node);
			Condition_bt_WrapperAI_TowerExampleInput_node93 condition_bt_WrapperAI_TowerExampleInput_node11 = new Condition_bt_WrapperAI_TowerExampleInput_node93();
			condition_bt_WrapperAI_TowerExampleInput_node11.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node11.SetId(93);
			decoratorLoopUntil_bt_WrapperAI_TowerExampleInput_node.AddChild(condition_bt_WrapperAI_TowerExampleInput_node11);
			decoratorLoopUntil_bt_WrapperAI_TowerExampleInput_node.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_TowerExampleInput_node.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node11.HasEvents());
			sequence11.SetHasEvents(sequence11.HasEvents() | decoratorLoopUntil_bt_WrapperAI_TowerExampleInput_node.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence11.HasEvents());
			WaitFrames_bt_WrapperAI_TowerExampleInput_node5 waitFrames_bt_WrapperAI_TowerExampleInput_node2 = new WaitFrames_bt_WrapperAI_TowerExampleInput_node5();
			waitFrames_bt_WrapperAI_TowerExampleInput_node2.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_TowerExampleInput_node2.SetId(5);
			ifElse3.AddChild(waitFrames_bt_WrapperAI_TowerExampleInput_node2);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | waitFrames_bt_WrapperAI_TowerExampleInput_node2.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | ifElse3.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | sequence9.HasEvents());
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | sequence6.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition.HasEvents());
			WithPrecondition withPrecondition2 = new WithPrecondition();
			withPrecondition2.SetClassNameString("WithPrecondition");
			withPrecondition2.SetId(2);
			selectorLoop.AddChild(withPrecondition2);
			Condition_bt_WrapperAI_TowerExampleInput_node3 condition_bt_WrapperAI_TowerExampleInput_node12 = new Condition_bt_WrapperAI_TowerExampleInput_node3();
			condition_bt_WrapperAI_TowerExampleInput_node12.SetClassNameString("Condition");
			condition_bt_WrapperAI_TowerExampleInput_node12.SetId(3);
			withPrecondition2.AddChild(condition_bt_WrapperAI_TowerExampleInput_node12);
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | condition_bt_WrapperAI_TowerExampleInput_node12.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(6);
			withPrecondition2.AddChild(sequence12);
			Action_bt_WrapperAI_TowerExampleInput_node4 action_bt_WrapperAI_TowerExampleInput_node8 = new Action_bt_WrapperAI_TowerExampleInput_node4();
			action_bt_WrapperAI_TowerExampleInput_node8.SetClassNameString("Action");
			action_bt_WrapperAI_TowerExampleInput_node8.SetId(4);
			sequence12.AddChild(action_bt_WrapperAI_TowerExampleInput_node8);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_WrapperAI_TowerExampleInput_node8.HasEvents());
			DecoratorLoop_bt_WrapperAI_TowerExampleInput_node7 decoratorLoop_bt_WrapperAI_TowerExampleInput_node2 = new DecoratorLoop_bt_WrapperAI_TowerExampleInput_node7();
			decoratorLoop_bt_WrapperAI_TowerExampleInput_node2.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_TowerExampleInput_node2.SetId(7);
			sequence12.AddChild(decoratorLoop_bt_WrapperAI_TowerExampleInput_node2);
			Noop noop3 = new Noop();
			noop3.SetClassNameString("Noop");
			noop3.SetId(8);
			decoratorLoop_bt_WrapperAI_TowerExampleInput_node2.AddChild(noop3);
			decoratorLoop_bt_WrapperAI_TowerExampleInput_node2.SetHasEvents(decoratorLoop_bt_WrapperAI_TowerExampleInput_node2.HasEvents() | noop3.HasEvents());
			sequence12.SetHasEvents(sequence12.HasEvents() | decoratorLoop_bt_WrapperAI_TowerExampleInput_node2.HasEvents());
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | sequence12.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition2.HasEvents());
			decoratorLoop_bt_WrapperAI_TowerExampleInput_node.SetHasEvents(decoratorLoop_bt_WrapperAI_TowerExampleInput_node.HasEvents() | selectorLoop.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorLoop_bt_WrapperAI_TowerExampleInput_node.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | sequence.HasEvents());
			return true;
		}
	}
}
