using System;

namespace behaviac
{
	public static class bt_WrapperAI_Monster_BTMonsterPassiveThief
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("WrapperAI/Monster/BTMonsterPassiveThief");
			bt.AddPar("uint", "p_targetID", "0", string.Empty);
			bt.AddPar("int", "p_srchRange", "0", string.Empty);
			bt.AddPar("uint", "p_selfID", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_randomPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			bt.AddChild(sequence);
			Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node98 assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node98();
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.SetId(98);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node48 assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node48();
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.SetId(48);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node11 assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node11();
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.SetId(11);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node14 decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node14();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.SetId(14);
			sequence.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node);
			SelectorLoop selectorLoop = new SelectorLoop();
			selectorLoop.SetClassNameString("SelectorLoop");
			selectorLoop.SetId(1);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.AddChild(selectorLoop);
			WithPrecondition withPrecondition = new WithPrecondition();
			withPrecondition.SetClassNameString("WithPrecondition");
			withPrecondition.SetId(60);
			selectorLoop.AddChild(withPrecondition);
			Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node61 condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node61();
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.SetId(61);
			withPrecondition.AddChild(condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node);
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.HasEvents());
			IfElse ifElse = new IfElse();
			ifElse.SetClassNameString("IfElse");
			ifElse.SetId(245);
			withPrecondition.AddChild(ifElse);
			Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node246 condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node246();
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.SetId(246);
			ifElse.AddChild(condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2);
			ifElse.SetHasEvents(ifElse.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.HasEvents());
			IfElse ifElse2 = new IfElse();
			ifElse2.SetClassNameString("IfElse");
			ifElse2.SetId(27);
			ifElse.AddChild(ifElse2);
			Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node28 condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node28();
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.SetId(28);
			ifElse2.AddChild(condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(247);
			ifElse2.AddChild(sequence2);
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node248 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node248();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.SetId(248);
			sequence2.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node66 decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node66();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.SetId(66);
			sequence2.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2);
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(7);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.AddChild(sequence3);
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(15);
			sequence3.AddChild(selector);
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(17);
			selector.AddChild(sequence4);
			Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node30 assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node30();
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.SetId(30);
			sequence4.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node18 assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node18();
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.SetId(18);
			sequence4.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node20 condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node20();
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.SetId(20);
			sequence4.AddChild(condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node26 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node26();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.SetId(26);
			sequence4.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node21 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node21();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.SetId(21);
			sequence4.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(68);
			selector.AddChild(sequence5);
			Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node69 condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node69();
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.SetId(69);
			sequence5.AddChild(condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node231 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node231();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.SetId(231);
			sequence5.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node232 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node232();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.SetId(232);
			sequence5.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node233 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node233();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6.SetId(233);
			sequence5.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node234 assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node234();
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6.SetId(234);
			sequence5.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node32 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node32();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7.SetId(32);
			sequence5.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node13 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node13();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8.SetId(13);
			sequence5.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			sequence3.SetHasEvents(sequence3.HasEvents() | selector.HasEvents());
			WaitFrames_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8 waitFrames_bt_WrapperAI_Monster_BTMonsterPassiveThief_node = new WaitFrames_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8();
			waitFrames_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.SetId(8);
			sequence3.AddChild(waitFrames_bt_WrapperAI_Monster_BTMonsterPassiveThief_node);
			sequence3.SetHasEvents(sequence3.HasEvents() | waitFrames_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.HasEvents());
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.HasEvents() | sequence3.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node2.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | sequence2.HasEvents());
			Noop noop = new Noop();
			noop.SetClassNameString("Noop");
			noop.SetId(29);
			ifElse2.AddChild(noop);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | noop.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | ifElse2.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(255);
			ifElse.AddChild(sequence6);
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node19 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node19();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9.SetId(19);
			sequence6.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node256 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node256();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10.SetId(256);
			sequence6.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node257 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node11 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node257();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node11.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node11.SetId(257);
			sequence6.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node11);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node11.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | sequence6.HasEvents());
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | ifElse.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition.HasEvents());
			WithPrecondition withPrecondition2 = new WithPrecondition();
			withPrecondition2.SetClassNameString("WithPrecondition");
			withPrecondition2.SetId(70);
			selectorLoop.AddChild(withPrecondition2);
			Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node71 condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node71();
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6.SetId(71);
			withPrecondition2.AddChild(condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6);
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(12);
			withPrecondition2.AddChild(sequence7);
			Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node16 assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node16();
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7.SetId(16);
			sequence7.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node224 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node12 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node224();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node12.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node12.SetId(224);
			sequence7.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node12);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node12.HasEvents());
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | sequence7.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition2.HasEvents());
			WithPrecondition withPrecondition3 = new WithPrecondition();
			withPrecondition3.SetClassNameString("WithPrecondition");
			withPrecondition3.SetId(515);
			selectorLoop.AddChild(withPrecondition3);
			Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node516 condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node516();
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7.SetId(516);
			withPrecondition3.AddChild(condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7);
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(517);
			withPrecondition3.AddChild(sequence8);
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node518 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node13 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node518();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node13.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node13.SetId(518);
			sequence8.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node13);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node13.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9 assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9();
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8.SetId(9);
			sequence8.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node14 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node14.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node14.SetId(10);
			sequence8.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node14);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node14.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node538 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node15 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node538();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node15.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node15.SetId(538);
			sequence8.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node15);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node15.HasEvents());
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | sequence8.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition3.HasEvents());
			WithPrecondition withPrecondition4 = new WithPrecondition();
			withPrecondition4.SetClassNameString("WithPrecondition");
			withPrecondition4.SetId(24);
			selectorLoop.AddChild(withPrecondition4);
			Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node25 condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node25();
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8.SetId(25);
			withPrecondition4.AddChild(condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8);
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(59);
			withPrecondition4.AddChild(sequence9);
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(487);
			sequence9.AddChild(selector2);
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node488 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node16 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node488();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node16.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node16.SetId(488);
			selector2.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node16);
			selector2.SetHasEvents(selector2.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node16.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node31 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node17 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node31();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node17.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node17.SetId(31);
			selector2.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node17);
			selector2.SetHasEvents(selector2.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node17.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | selector2.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node65 decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node65();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.SetId(65);
			sequence9.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3);
			Noop noop2 = new Noop();
			noop2.SetClassNameString("Noop");
			noop2.SetId(33);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.AddChild(noop2);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.HasEvents() | noop2.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node3.HasEvents());
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | sequence9.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition4.HasEvents());
			WithPrecondition withPrecondition5 = new WithPrecondition();
			withPrecondition5.SetClassNameString("WithPrecondition");
			withPrecondition5.SetId(34);
			selectorLoop.AddChild(withPrecondition5);
			Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node40 condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node40();
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9.SetId(40);
			withPrecondition5.AddChild(condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9);
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(41);
			withPrecondition5.AddChild(sequence10);
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node42 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node18 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node42();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node18.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node18.SetId(42);
			sequence10.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node18);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node18.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node43 decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node43();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.SetId(43);
			sequence10.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4);
			Noop noop3 = new Noop();
			noop3.SetClassNameString("Noop");
			noop3.SetId(458);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.AddChild(noop3);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.HasEvents() | noop3.HasEvents());
			sequence10.SetHasEvents(sequence10.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node4.HasEvents());
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | sequence10.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition5.HasEvents());
			WithPrecondition withPrecondition6 = new WithPrecondition();
			withPrecondition6.SetClassNameString("WithPrecondition");
			withPrecondition6.SetId(450);
			selectorLoop.AddChild(withPrecondition6);
			Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node454 condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node454();
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10.SetId(454);
			withPrecondition6.AddChild(condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10);
			withPrecondition6.SetHasEvents(withPrecondition6.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(455);
			withPrecondition6.AddChild(sequence11);
			Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node456 action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node19 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node456();
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node19.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node19.SetId(456);
			sequence11.AddChild(action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node19);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node19.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node457 decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node457();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.SetId(457);
			sequence11.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5);
			Noop noop4 = new Noop();
			noop4.SetClassNameString("Noop");
			noop4.SetId(2);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.AddChild(noop4);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.HasEvents() | noop4.HasEvents());
			sequence11.SetHasEvents(sequence11.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node5.HasEvents());
			withPrecondition6.SetHasEvents(withPrecondition6.HasEvents() | sequence11.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition6.HasEvents());
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.HasEvents() | selectorLoop.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | sequence.HasEvents());
			return true;
		}
	}
}
