using System;

namespace behaviac
{
	public static class bt_WrapperAI_Monster_BTMonsterRob
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("WrapperAI/Monster/BTMonsterRob");
			bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
			bt.AddPar("uint", "p_targetID", "0", string.Empty);
			bt.AddPar("int", "p_srchRange", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
			bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
			bt.AddPar("uint", "p_CmdID", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("int", "p_skillAttackRange", "0", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_orignalPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("int", "p_follow_range", "9000", string.Empty);
			bt.AddPar("UnityEngine.Vector3", "p_orignalDirection", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
			bt.AddPar("int", "p_pursuitRange", "0", string.Empty);
			bt.AddPar("int", "p_waitFramesToSearch", "10", string.Empty);
			bt.AddPar("uint", "p_selfID", "0", string.Empty);
			bt.AddPar("int", "p_attackOneTime", "0", string.Empty);
			bt.AddPar("uint", "p_teamTarget", "0", string.Empty);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			bt.AddChild(sequence);
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node98 assignment_bt_WrapperAI_Monster_BTMonsterRob_node = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node98();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node.SetId(98);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node20 assignment_bt_WrapperAI_Monster_BTMonsterRob_node2 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node20();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node2.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node2.SetId(20);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node2);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node2.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node31 assignment_bt_WrapperAI_Monster_BTMonsterRob_node3 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node31();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node3.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node3.SetId(31);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node3);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node3.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node48 assignment_bt_WrapperAI_Monster_BTMonsterRob_node4 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node48();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node4.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node4.SetId(48);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node4);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node4.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node11 assignment_bt_WrapperAI_Monster_BTMonsterRob_node5 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node11();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node5.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node5.SetId(11);
			sequence.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node5);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node5.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node14 decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node14();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node.SetId(14);
			sequence.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node);
			SelectorLoop selectorLoop = new SelectorLoop();
			selectorLoop.SetClassNameString("SelectorLoop");
			selectorLoop.SetId(1);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node.AddChild(selectorLoop);
			WithPrecondition withPrecondition = new WithPrecondition();
			withPrecondition.SetClassNameString("WithPrecondition");
			withPrecondition.SetId(60);
			selectorLoop.AddChild(withPrecondition);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node61 condition_bt_WrapperAI_Monster_BTMonsterRob_node = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node61();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node.SetId(61);
			withPrecondition.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node);
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(46);
			withPrecondition.AddChild(sequence2);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node47 action_bt_WrapperAI_Monster_BTMonsterRob_node = new Action_bt_WrapperAI_Monster_BTMonsterRob_node47();
			action_bt_WrapperAI_Monster_BTMonsterRob_node.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node.SetId(47);
			sequence2.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node.HasEvents());
			IfElse ifElse = new IfElse();
			ifElse.SetClassNameString("IfElse");
			ifElse.SetId(245);
			sequence2.AddChild(ifElse);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node246 condition_bt_WrapperAI_Monster_BTMonsterRob_node2 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node246();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node2.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node2.SetId(246);
			ifElse.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node2);
			ifElse.SetHasEvents(ifElse.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node2.HasEvents());
			IfElse ifElse2 = new IfElse();
			ifElse2.SetClassNameString("IfElse");
			ifElse2.SetId(27);
			ifElse.AddChild(ifElse2);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node28 condition_bt_WrapperAI_Monster_BTMonsterRob_node3 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node28();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node3.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node3.SetId(28);
			ifElse2.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node3);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node3.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(247);
			ifElse2.AddChild(sequence3);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node248 action_bt_WrapperAI_Monster_BTMonsterRob_node2 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node248();
			action_bt_WrapperAI_Monster_BTMonsterRob_node2.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node2.SetId(248);
			sequence3.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node2.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node21 action_bt_WrapperAI_Monster_BTMonsterRob_node3 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node21();
			action_bt_WrapperAI_Monster_BTMonsterRob_node3.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node3.SetId(21);
			sequence3.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node3.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node66 decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node2 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node66();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node2.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node2.SetId(66);
			sequence3.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node2);
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(18);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node2.AddChild(sequence4);
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(67);
			sequence4.AddChild(selector);
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(22);
			selector.AddChild(sequence5);
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node30 assignment_bt_WrapperAI_Monster_BTMonsterRob_node6 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node30();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node6.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node6.SetId(30);
			sequence5.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node6);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node6.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node16 assignment_bt_WrapperAI_Monster_BTMonsterRob_node7 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node16();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node7.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node7.SetId(16);
			sequence5.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node7.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node23 condition_bt_WrapperAI_Monster_BTMonsterRob_node4 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node23();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node4.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node4.SetId(23);
			sequence5.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node4.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node24 action_bt_WrapperAI_Monster_BTMonsterRob_node4 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node24();
			action_bt_WrapperAI_Monster_BTMonsterRob_node4.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node4.SetId(24);
			sequence5.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node4.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node25 action_bt_WrapperAI_Monster_BTMonsterRob_node5 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node25();
			action_bt_WrapperAI_Monster_BTMonsterRob_node5.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node5.SetId(25);
			sequence5.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node5.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node26 action_bt_WrapperAI_Monster_BTMonsterRob_node6 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node26();
			action_bt_WrapperAI_Monster_BTMonsterRob_node6.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node6.SetId(26);
			sequence5.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node6);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node6.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node13 action_bt_WrapperAI_Monster_BTMonsterRob_node7 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node13();
			action_bt_WrapperAI_Monster_BTMonsterRob_node7.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node7.SetId(13);
			sequence5.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(68);
			selector.AddChild(sequence6);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node69 condition_bt_WrapperAI_Monster_BTMonsterRob_node5 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node69();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node5.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node5.SetId(69);
			sequence6.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node5);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node5.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node231 action_bt_WrapperAI_Monster_BTMonsterRob_node8 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node231();
			action_bt_WrapperAI_Monster_BTMonsterRob_node8.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node8.SetId(231);
			sequence6.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node8);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node8.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node232 action_bt_WrapperAI_Monster_BTMonsterRob_node9 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node232();
			action_bt_WrapperAI_Monster_BTMonsterRob_node9.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node9.SetId(232);
			sequence6.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node9);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node9.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node233 action_bt_WrapperAI_Monster_BTMonsterRob_node10 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node233();
			action_bt_WrapperAI_Monster_BTMonsterRob_node10.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node10.SetId(233);
			sequence6.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node10);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node10.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node234 assignment_bt_WrapperAI_Monster_BTMonsterRob_node8 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node234();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node8.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node8.SetId(234);
			sequence6.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node8);
			sequence6.SetHasEvents(sequence6.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node8.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node32 action_bt_WrapperAI_Monster_BTMonsterRob_node11 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node32();
			action_bt_WrapperAI_Monster_BTMonsterRob_node11.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node11.SetId(32);
			sequence6.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node11);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node11.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node15 action_bt_WrapperAI_Monster_BTMonsterRob_node12 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node15();
			action_bt_WrapperAI_Monster_BTMonsterRob_node12.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node12.SetId(15);
			sequence6.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node12);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node12.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(235);
			selector.AddChild(sequence7);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node236 condition_bt_WrapperAI_Monster_BTMonsterRob_node6 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node236();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node6.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node6.SetId(236);
			sequence7.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node6);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node6.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node237 action_bt_WrapperAI_Monster_BTMonsterRob_node13 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node237();
			action_bt_WrapperAI_Monster_BTMonsterRob_node13.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node13.SetId(237);
			sequence7.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node13);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node13.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node238 action_bt_WrapperAI_Monster_BTMonsterRob_node14 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node238();
			action_bt_WrapperAI_Monster_BTMonsterRob_node14.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node14.SetId(238);
			sequence7.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node14);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node14.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node239 assignment_bt_WrapperAI_Monster_BTMonsterRob_node9 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node239();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node9.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node9.SetId(239);
			sequence7.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node9);
			sequence7.SetHasEvents(sequence7.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node9.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node33 action_bt_WrapperAI_Monster_BTMonsterRob_node15 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node33();
			action_bt_WrapperAI_Monster_BTMonsterRob_node15.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node15.SetId(33);
			sequence7.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node15);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node15.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			sequence4.SetHasEvents(sequence4.HasEvents() | selector.HasEvents());
			WaitFrames_bt_WrapperAI_Monster_BTMonsterRob_node9 waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node = new WaitFrames_bt_WrapperAI_Monster_BTMonsterRob_node9();
			waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node.SetId(9);
			sequence4.AddChild(waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node);
			sequence4.SetHasEvents(sequence4.HasEvents() | waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node.HasEvents());
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node2.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node2.HasEvents() | sequence4.HasEvents());
			sequence3.SetHasEvents(sequence3.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node2.HasEvents());
			ifElse2.SetHasEvents(ifElse2.HasEvents() | sequence3.HasEvents());
			Noop noop = new Noop();
			noop.SetClassNameString("Noop");
			noop.SetId(29);
			ifElse2.AddChild(noop);
			ifElse2.SetHasEvents(ifElse2.HasEvents() | noop.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | ifElse2.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(255);
			ifElse.AddChild(sequence8);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node19 action_bt_WrapperAI_Monster_BTMonsterRob_node16 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node19();
			action_bt_WrapperAI_Monster_BTMonsterRob_node16.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node16.SetId(19);
			sequence8.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node16);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node16.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node256 action_bt_WrapperAI_Monster_BTMonsterRob_node17 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node256();
			action_bt_WrapperAI_Monster_BTMonsterRob_node17.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node17.SetId(256);
			sequence8.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node17);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node17.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node257 action_bt_WrapperAI_Monster_BTMonsterRob_node18 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node257();
			action_bt_WrapperAI_Monster_BTMonsterRob_node18.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node18.SetId(257);
			sequence8.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node18);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node18.HasEvents());
			ifElse.SetHasEvents(ifElse.HasEvents() | sequence8.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | ifElse.HasEvents());
			WaitFrames_bt_WrapperAI_Monster_BTMonsterRob_node34 waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node2 = new WaitFrames_bt_WrapperAI_Monster_BTMonsterRob_node34();
			waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node2.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node2.SetId(34);
			sequence2.AddChild(waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node2.HasEvents());
			withPrecondition.SetHasEvents(withPrecondition.HasEvents() | sequence2.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition.HasEvents());
			WithPrecondition withPrecondition2 = new WithPrecondition();
			withPrecondition2.SetClassNameString("WithPrecondition");
			withPrecondition2.SetId(70);
			selectorLoop.AddChild(withPrecondition2);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node71 condition_bt_WrapperAI_Monster_BTMonsterRob_node7 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node71();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node7.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node7.SetId(71);
			withPrecondition2.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node7);
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node7.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(64);
			withPrecondition2.AddChild(selector2);
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(65);
			selector2.AddChild(sequence9);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node130 condition_bt_WrapperAI_Monster_BTMonsterRob_node8 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node130();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node8.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node8.SetId(130);
			sequence9.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node8);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node8.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node72 action_bt_WrapperAI_Monster_BTMonsterRob_node19 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node72();
			action_bt_WrapperAI_Monster_BTMonsterRob_node19.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node19.SetId(72);
			sequence9.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node19);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node19.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(75);
			selector2.AddChild(sequence10);
			IfElse ifElse3 = new IfElse();
			ifElse3.SetClassNameString("IfElse");
			ifElse3.SetId(77);
			sequence10.AddChild(ifElse3);
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(6);
			ifElse3.AddChild(sequence11);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node100 condition_bt_WrapperAI_Monster_BTMonsterRob_node9 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node100();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node9.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node9.SetId(100);
			sequence11.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node9);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node9.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node36 condition_bt_WrapperAI_Monster_BTMonsterRob_node10 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node36();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node10.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node10.SetId(36);
			sequence11.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node10);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node10.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence11.HasEvents());
			Noop noop2 = new Noop();
			noop2.SetClassNameString("Noop");
			noop2.SetId(131);
			ifElse3.AddChild(noop2);
			ifElse3.SetHasEvents(ifElse3.HasEvents() | noop2.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(37);
			ifElse3.AddChild(sequence12);
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node133 assignment_bt_WrapperAI_Monster_BTMonsterRob_node10 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node133();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node10.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node10.SetId(133);
			sequence12.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node10);
			sequence12.SetHasEvents(sequence12.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node10.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node38 assignment_bt_WrapperAI_Monster_BTMonsterRob_node11 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node38();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node11.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node11.SetId(38);
			sequence12.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node11);
			sequence12.SetHasEvents(sequence12.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node11.HasEvents());
			ifElse3.SetHasEvents(ifElse3.HasEvents() | sequence12.HasEvents());
			sequence10.SetHasEvents(sequence10.HasEvents() | ifElse3.HasEvents());
			Compute_bt_WrapperAI_Monster_BTMonsterRob_node39 compute_bt_WrapperAI_Monster_BTMonsterRob_node = new Compute_bt_WrapperAI_Monster_BTMonsterRob_node39();
			compute_bt_WrapperAI_Monster_BTMonsterRob_node.SetClassNameString("Compute");
			compute_bt_WrapperAI_Monster_BTMonsterRob_node.SetId(39);
			sequence10.AddChild(compute_bt_WrapperAI_Monster_BTMonsterRob_node);
			sequence10.SetHasEvents(sequence10.HasEvents() | compute_bt_WrapperAI_Monster_BTMonsterRob_node.HasEvents());
			IfElse ifElse4 = new IfElse();
			ifElse4.SetClassNameString("IfElse");
			ifElse4.SetId(134);
			sequence10.AddChild(ifElse4);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node5 condition_bt_WrapperAI_Monster_BTMonsterRob_node11 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node5();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node11.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node11.SetId(5);
			ifElse4.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node11);
			ifElse4.SetHasEvents(ifElse4.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node11.HasEvents());
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(137);
			ifElse4.AddChild(sequence13);
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(138);
			sequence13.AddChild(selector3);
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(153);
			selector3.AddChild(sequence14);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node140 action_bt_WrapperAI_Monster_BTMonsterRob_node20 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node140();
			action_bt_WrapperAI_Monster_BTMonsterRob_node20.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node20.SetId(140);
			sequence14.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node20);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node20.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node159 assignment_bt_WrapperAI_Monster_BTMonsterRob_node12 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node159();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node12.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node12.SetId(159);
			sequence14.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node12);
			sequence14.SetHasEvents(sequence14.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node12.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node160 assignment_bt_WrapperAI_Monster_BTMonsterRob_node13 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node160();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node13.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node13.SetId(160);
			sequence14.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node13);
			sequence14.SetHasEvents(sequence14.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node13.HasEvents());
			Selector selector4 = new Selector();
			selector4.SetClassNameString("Selector");
			selector4.SetId(141);
			sequence14.AddChild(selector4);
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(148);
			selector4.AddChild(sequence15);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node712 action_bt_WrapperAI_Monster_BTMonsterRob_node21 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node712();
			action_bt_WrapperAI_Monster_BTMonsterRob_node21.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node21.SetId(712);
			sequence15.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node21);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node21.HasEvents());
			Selector selector5 = new Selector();
			selector5.SetClassNameString("Selector");
			selector5.SetId(3);
			sequence15.AddChild(selector5);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node2 condition_bt_WrapperAI_Monster_BTMonsterRob_node12 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node2();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node12.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node12.SetId(2);
			selector5.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node12);
			selector5.SetHasEvents(selector5.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node12.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node4 condition_bt_WrapperAI_Monster_BTMonsterRob_node13 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node4();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node13.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node13.SetId(4);
			selector5.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node13);
			selector5.SetHasEvents(selector5.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node13.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node149 condition_bt_WrapperAI_Monster_BTMonsterRob_node14 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node149();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node14.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node14.SetId(149);
			selector5.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node14);
			selector5.SetHasEvents(selector5.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node14.HasEvents());
			sequence15.SetHasEvents(sequence15.HasEvents() | selector5.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node10 condition_bt_WrapperAI_Monster_BTMonsterRob_node15 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node10();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node15.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node15.SetId(10);
			sequence15.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node15);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node15.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node12 action_bt_WrapperAI_Monster_BTMonsterRob_node22 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node12();
			action_bt_WrapperAI_Monster_BTMonsterRob_node22.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node22.SetId(12);
			sequence15.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node22);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node22.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence15.HasEvents());
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(150);
			selector4.AddChild(sequence16);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node151 condition_bt_WrapperAI_Monster_BTMonsterRob_node16 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node151();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node16.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node16.SetId(151);
			sequence16.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node16);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node16.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node152 assignment_bt_WrapperAI_Monster_BTMonsterRob_node14 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node152();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node14.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node14.SetId(152);
			sequence16.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node14);
			sequence16.SetHasEvents(sequence16.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node14.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node154 condition_bt_WrapperAI_Monster_BTMonsterRob_node17 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node154();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node17.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node17.SetId(154);
			sequence16.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node17);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node17.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node155 action_bt_WrapperAI_Monster_BTMonsterRob_node23 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node155();
			action_bt_WrapperAI_Monster_BTMonsterRob_node23.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node23.SetId(155);
			sequence16.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node23);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node23.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence16.HasEvents());
			Sequence sequence17 = new Sequence();
			sequence17.SetClassNameString("Sequence");
			sequence17.SetId(157);
			selector4.AddChild(sequence17);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node44 condition_bt_WrapperAI_Monster_BTMonsterRob_node18 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node44();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node18.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node18.SetId(44);
			sequence17.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node18);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node18.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node45 condition_bt_WrapperAI_Monster_BTMonsterRob_node19 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node45();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node19.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node19.SetId(45);
			sequence17.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node19);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node19.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node49 action_bt_WrapperAI_Monster_BTMonsterRob_node24 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node49();
			action_bt_WrapperAI_Monster_BTMonsterRob_node24.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node24.SetId(49);
			sequence17.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node24);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node24.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence17.HasEvents());
			sequence14.SetHasEvents(sequence14.HasEvents() | selector4.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence14.HasEvents());
			Sequence sequence18 = new Sequence();
			sequence18.SetClassNameString("Sequence");
			sequence18.SetId(51);
			selector3.AddChild(sequence18);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node156 action_bt_WrapperAI_Monster_BTMonsterRob_node25 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node156();
			action_bt_WrapperAI_Monster_BTMonsterRob_node25.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node25.SetId(156);
			sequence18.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node25);
			sequence18.SetHasEvents(sequence18.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node25.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node52 assignment_bt_WrapperAI_Monster_BTMonsterRob_node15 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node52();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node15.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node15.SetId(52);
			sequence18.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node15);
			sequence18.SetHasEvents(sequence18.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node15.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node53 assignment_bt_WrapperAI_Monster_BTMonsterRob_node16 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node53();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node16.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node16.SetId(53);
			sequence18.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node16);
			sequence18.SetHasEvents(sequence18.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node16.HasEvents());
			Selector selector6 = new Selector();
			selector6.SetClassNameString("Selector");
			selector6.SetId(54);
			sequence18.AddChild(selector6);
			Sequence sequence19 = new Sequence();
			sequence19.SetClassNameString("Sequence");
			sequence19.SetId(50);
			selector6.AddChild(sequence19);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node55 action_bt_WrapperAI_Monster_BTMonsterRob_node26 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node55();
			action_bt_WrapperAI_Monster_BTMonsterRob_node26.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node26.SetId(55);
			sequence19.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node26);
			sequence19.SetHasEvents(sequence19.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node26.HasEvents());
			Selector selector7 = new Selector();
			selector7.SetClassNameString("Selector");
			selector7.SetId(56);
			sequence19.AddChild(selector7);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node158 condition_bt_WrapperAI_Monster_BTMonsterRob_node20 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node158();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node20.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node20.SetId(158);
			selector7.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node20);
			selector7.SetHasEvents(selector7.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node20.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node161 condition_bt_WrapperAI_Monster_BTMonsterRob_node21 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node161();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node21.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node21.SetId(161);
			selector7.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node21);
			selector7.SetHasEvents(selector7.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node21.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node162 condition_bt_WrapperAI_Monster_BTMonsterRob_node22 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node162();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node22.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node22.SetId(162);
			selector7.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node22);
			selector7.SetHasEvents(selector7.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node22.HasEvents());
			sequence19.SetHasEvents(sequence19.HasEvents() | selector7.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node169 condition_bt_WrapperAI_Monster_BTMonsterRob_node23 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node169();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node23.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node23.SetId(169);
			sequence19.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node23);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node23.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node170 action_bt_WrapperAI_Monster_BTMonsterRob_node27 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node170();
			action_bt_WrapperAI_Monster_BTMonsterRob_node27.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node27.SetId(170);
			sequence19.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node27);
			sequence19.SetHasEvents(sequence19.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node27.HasEvents());
			selector6.SetHasEvents(selector6.HasEvents() | sequence19.HasEvents());
			Sequence sequence20 = new Sequence();
			sequence20.SetClassNameString("Sequence");
			sequence20.SetId(73);
			selector6.AddChild(sequence20);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node74 condition_bt_WrapperAI_Monster_BTMonsterRob_node24 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node74();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node24.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node24.SetId(74);
			sequence20.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node24);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node24.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node76 assignment_bt_WrapperAI_Monster_BTMonsterRob_node17 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node76();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node17.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node17.SetId(76);
			sequence20.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node17);
			sequence20.SetHasEvents(sequence20.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node17.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node78 condition_bt_WrapperAI_Monster_BTMonsterRob_node25 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node78();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node25.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node25.SetId(78);
			sequence20.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node25);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node25.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node79 action_bt_WrapperAI_Monster_BTMonsterRob_node28 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node79();
			action_bt_WrapperAI_Monster_BTMonsterRob_node28.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node28.SetId(79);
			sequence20.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node28);
			sequence20.SetHasEvents(sequence20.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node28.HasEvents());
			selector6.SetHasEvents(selector6.HasEvents() | sequence20.HasEvents());
			Sequence sequence21 = new Sequence();
			sequence21.SetClassNameString("Sequence");
			sequence21.SetId(80);
			selector6.AddChild(sequence21);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node81 condition_bt_WrapperAI_Monster_BTMonsterRob_node26 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node81();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node26.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node26.SetId(81);
			sequence21.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node26);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node26.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node82 condition_bt_WrapperAI_Monster_BTMonsterRob_node27 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node82();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node27.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node27.SetId(82);
			sequence21.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node27);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node27.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node83 action_bt_WrapperAI_Monster_BTMonsterRob_node29 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node83();
			action_bt_WrapperAI_Monster_BTMonsterRob_node29.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node29.SetId(83);
			sequence21.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node29);
			sequence21.SetHasEvents(sequence21.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node29.HasEvents());
			selector6.SetHasEvents(selector6.HasEvents() | sequence21.HasEvents());
			sequence18.SetHasEvents(sequence18.HasEvents() | selector6.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence18.HasEvents());
			Sequence sequence22 = new Sequence();
			sequence22.SetClassNameString("Sequence");
			sequence22.SetId(104);
			selector3.AddChild(sequence22);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node105 action_bt_WrapperAI_Monster_BTMonsterRob_node30 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node105();
			action_bt_WrapperAI_Monster_BTMonsterRob_node30.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node30.SetId(105);
			sequence22.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node30);
			sequence22.SetHasEvents(sequence22.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node30.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node106 assignment_bt_WrapperAI_Monster_BTMonsterRob_node18 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node106();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node18.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node18.SetId(106);
			sequence22.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node18);
			sequence22.SetHasEvents(sequence22.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node18.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node107 assignment_bt_WrapperAI_Monster_BTMonsterRob_node19 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node107();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node19.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node19.SetId(107);
			sequence22.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node19);
			sequence22.SetHasEvents(sequence22.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node19.HasEvents());
			Selector selector8 = new Selector();
			selector8.SetClassNameString("Selector");
			selector8.SetId(108);
			sequence22.AddChild(selector8);
			Sequence sequence23 = new Sequence();
			sequence23.SetClassNameString("Sequence");
			sequence23.SetId(84);
			selector8.AddChild(sequence23);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node171 action_bt_WrapperAI_Monster_BTMonsterRob_node31 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node171();
			action_bt_WrapperAI_Monster_BTMonsterRob_node31.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node31.SetId(171);
			sequence23.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node31);
			sequence23.SetHasEvents(sequence23.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node31.HasEvents());
			Selector selector9 = new Selector();
			selector9.SetClassNameString("Selector");
			selector9.SetId(172);
			sequence23.AddChild(selector9);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node173 condition_bt_WrapperAI_Monster_BTMonsterRob_node28 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node173();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node28.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node28.SetId(173);
			selector9.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node28);
			selector9.SetHasEvents(selector9.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node28.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node174 condition_bt_WrapperAI_Monster_BTMonsterRob_node29 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node174();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node29.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node29.SetId(174);
			selector9.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node29);
			selector9.SetHasEvents(selector9.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node29.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node89 condition_bt_WrapperAI_Monster_BTMonsterRob_node30 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node89();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node30.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node30.SetId(89);
			selector9.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node30);
			selector9.SetHasEvents(selector9.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node30.HasEvents());
			sequence23.SetHasEvents(sequence23.HasEvents() | selector9.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node90 condition_bt_WrapperAI_Monster_BTMonsterRob_node31 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node90();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node31.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node31.SetId(90);
			sequence23.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node31);
			sequence23.SetHasEvents(sequence23.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node31.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node91 action_bt_WrapperAI_Monster_BTMonsterRob_node32 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node91();
			action_bt_WrapperAI_Monster_BTMonsterRob_node32.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node32.SetId(91);
			sequence23.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node32);
			sequence23.SetHasEvents(sequence23.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node32.HasEvents());
			selector8.SetHasEvents(selector8.HasEvents() | sequence23.HasEvents());
			Sequence sequence24 = new Sequence();
			sequence24.SetClassNameString("Sequence");
			sequence24.SetId(92);
			selector8.AddChild(sequence24);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node93 condition_bt_WrapperAI_Monster_BTMonsterRob_node32 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node93();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node32.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node32.SetId(93);
			sequence24.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node32);
			sequence24.SetHasEvents(sequence24.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node32.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node94 assignment_bt_WrapperAI_Monster_BTMonsterRob_node20 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node94();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node20.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node20.SetId(94);
			sequence24.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node20);
			sequence24.SetHasEvents(sequence24.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node20.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node95 condition_bt_WrapperAI_Monster_BTMonsterRob_node33 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node95();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node33.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node33.SetId(95);
			sequence24.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node33);
			sequence24.SetHasEvents(sequence24.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node33.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node96 action_bt_WrapperAI_Monster_BTMonsterRob_node33 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node96();
			action_bt_WrapperAI_Monster_BTMonsterRob_node33.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node33.SetId(96);
			sequence24.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node33);
			sequence24.SetHasEvents(sequence24.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node33.HasEvents());
			selector8.SetHasEvents(selector8.HasEvents() | sequence24.HasEvents());
			Sequence sequence25 = new Sequence();
			sequence25.SetClassNameString("Sequence");
			sequence25.SetId(97);
			selector8.AddChild(sequence25);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node99 condition_bt_WrapperAI_Monster_BTMonsterRob_node34 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node99();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node34.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node34.SetId(99);
			sequence25.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node34);
			sequence25.SetHasEvents(sequence25.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node34.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node101 condition_bt_WrapperAI_Monster_BTMonsterRob_node35 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node101();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node35.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node35.SetId(101);
			sequence25.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node35);
			sequence25.SetHasEvents(sequence25.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node35.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node102 action_bt_WrapperAI_Monster_BTMonsterRob_node34 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node102();
			action_bt_WrapperAI_Monster_BTMonsterRob_node34.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node34.SetId(102);
			sequence25.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node34);
			sequence25.SetHasEvents(sequence25.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node34.HasEvents());
			selector8.SetHasEvents(selector8.HasEvents() | sequence25.HasEvents());
			sequence22.SetHasEvents(sequence22.HasEvents() | selector8.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence22.HasEvents());
			Sequence sequence26 = new Sequence();
			sequence26.SetClassNameString("Sequence");
			sequence26.SetId(121);
			selector3.AddChild(sequence26);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node122 action_bt_WrapperAI_Monster_BTMonsterRob_node35 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node122();
			action_bt_WrapperAI_Monster_BTMonsterRob_node35.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node35.SetId(122);
			sequence26.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node35);
			sequence26.SetHasEvents(sequence26.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node35.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node123 assignment_bt_WrapperAI_Monster_BTMonsterRob_node21 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node123();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node21.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node21.SetId(123);
			sequence26.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node21);
			sequence26.SetHasEvents(sequence26.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node21.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node124 assignment_bt_WrapperAI_Monster_BTMonsterRob_node22 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node124();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node22.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node22.SetId(124);
			sequence26.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node22);
			sequence26.SetHasEvents(sequence26.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node22.HasEvents());
			Selector selector10 = new Selector();
			selector10.SetClassNameString("Selector");
			selector10.SetId(125);
			sequence26.AddChild(selector10);
			Sequence sequence27 = new Sequence();
			sequence27.SetClassNameString("Sequence");
			sequence27.SetId(103);
			selector10.AddChild(sequence27);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node109 action_bt_WrapperAI_Monster_BTMonsterRob_node36 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node109();
			action_bt_WrapperAI_Monster_BTMonsterRob_node36.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node36.SetId(109);
			sequence27.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node36);
			sequence27.SetHasEvents(sequence27.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node36.HasEvents());
			Selector selector11 = new Selector();
			selector11.SetClassNameString("Selector");
			selector11.SetId(110);
			sequence27.AddChild(selector11);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node111 condition_bt_WrapperAI_Monster_BTMonsterRob_node36 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node111();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node36.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node36.SetId(111);
			selector11.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node36);
			selector11.SetHasEvents(selector11.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node36.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node112 condition_bt_WrapperAI_Monster_BTMonsterRob_node37 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node112();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node37.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node37.SetId(112);
			selector11.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node37);
			selector11.SetHasEvents(selector11.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node37.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node113 condition_bt_WrapperAI_Monster_BTMonsterRob_node38 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node113();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node38.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node38.SetId(113);
			selector11.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node38);
			selector11.SetHasEvents(selector11.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node38.HasEvents());
			sequence27.SetHasEvents(sequence27.HasEvents() | selector11.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node114 condition_bt_WrapperAI_Monster_BTMonsterRob_node39 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node114();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node39.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node39.SetId(114);
			sequence27.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node39);
			sequence27.SetHasEvents(sequence27.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node39.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node115 action_bt_WrapperAI_Monster_BTMonsterRob_node37 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node115();
			action_bt_WrapperAI_Monster_BTMonsterRob_node37.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node37.SetId(115);
			sequence27.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node37);
			sequence27.SetHasEvents(sequence27.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node37.HasEvents());
			selector10.SetHasEvents(selector10.HasEvents() | sequence27.HasEvents());
			Sequence sequence28 = new Sequence();
			sequence28.SetClassNameString("Sequence");
			sequence28.SetId(116);
			selector10.AddChild(sequence28);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node117 condition_bt_WrapperAI_Monster_BTMonsterRob_node40 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node117();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node40.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node40.SetId(117);
			sequence28.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node40);
			sequence28.SetHasEvents(sequence28.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node40.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node118 assignment_bt_WrapperAI_Monster_BTMonsterRob_node23 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node118();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node23.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node23.SetId(118);
			sequence28.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node23);
			sequence28.SetHasEvents(sequence28.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node23.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node119 condition_bt_WrapperAI_Monster_BTMonsterRob_node41 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node119();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node41.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node41.SetId(119);
			sequence28.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node41);
			sequence28.SetHasEvents(sequence28.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node41.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node120 action_bt_WrapperAI_Monster_BTMonsterRob_node38 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node120();
			action_bt_WrapperAI_Monster_BTMonsterRob_node38.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node38.SetId(120);
			sequence28.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node38);
			sequence28.SetHasEvents(sequence28.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node38.HasEvents());
			selector10.SetHasEvents(selector10.HasEvents() | sequence28.HasEvents());
			Sequence sequence29 = new Sequence();
			sequence29.SetClassNameString("Sequence");
			sequence29.SetId(126);
			selector10.AddChild(sequence29);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node127 condition_bt_WrapperAI_Monster_BTMonsterRob_node42 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node127();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node42.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node42.SetId(127);
			sequence29.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node42);
			sequence29.SetHasEvents(sequence29.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node42.HasEvents());
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node128 condition_bt_WrapperAI_Monster_BTMonsterRob_node43 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node128();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node43.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node43.SetId(128);
			sequence29.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node43);
			sequence29.SetHasEvents(sequence29.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node43.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node129 action_bt_WrapperAI_Monster_BTMonsterRob_node39 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node129();
			action_bt_WrapperAI_Monster_BTMonsterRob_node39.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node39.SetId(129);
			sequence29.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node39);
			sequence29.SetHasEvents(sequence29.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node39.HasEvents());
			selector10.SetHasEvents(selector10.HasEvents() | sequence29.HasEvents());
			sequence26.SetHasEvents(sequence26.HasEvents() | selector10.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence26.HasEvents());
			IfElse ifElse5 = new IfElse();
			ifElse5.SetClassNameString("IfElse");
			ifElse5.SetId(58);
			selector3.AddChild(ifElse5);
			Sequence sequence30 = new Sequence();
			sequence30.SetClassNameString("Sequence");
			sequence30.SetId(62);
			ifElse5.AddChild(sequence30);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node57 condition_bt_WrapperAI_Monster_BTMonsterRob_node44 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node57();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node44.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node44.SetId(57);
			sequence30.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node44);
			sequence30.SetHasEvents(sequence30.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node44.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node8 action_bt_WrapperAI_Monster_BTMonsterRob_node40 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node8();
			action_bt_WrapperAI_Monster_BTMonsterRob_node40.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node40.SetId(8);
			sequence30.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node40);
			sequence30.SetHasEvents(sequence30.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node40.HasEvents());
			ifElse5.SetHasEvents(ifElse5.HasEvents() | sequence30.HasEvents());
			Sequence sequence31 = new Sequence();
			sequence31.SetClassNameString("Sequence");
			sequence31.SetId(59);
			ifElse5.AddChild(sequence31);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node444 action_bt_WrapperAI_Monster_BTMonsterRob_node41 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node444();
			action_bt_WrapperAI_Monster_BTMonsterRob_node41.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node41.SetId(444);
			sequence31.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node41);
			sequence31.SetHasEvents(sequence31.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node41.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node201 action_bt_WrapperAI_Monster_BTMonsterRob_node42 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node201();
			action_bt_WrapperAI_Monster_BTMonsterRob_node42.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node42.SetId(201);
			sequence31.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node42);
			sequence31.SetHasEvents(sequence31.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node42.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node241 action_bt_WrapperAI_Monster_BTMonsterRob_node43 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node241();
			action_bt_WrapperAI_Monster_BTMonsterRob_node43.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node43.SetId(241);
			sequence31.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node43);
			sequence31.SetHasEvents(sequence31.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node43.HasEvents());
			ifElse5.SetHasEvents(ifElse5.HasEvents() | sequence31.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node7 action_bt_WrapperAI_Monster_BTMonsterRob_node44 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node7();
			action_bt_WrapperAI_Monster_BTMonsterRob_node44.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node44.SetId(7);
			ifElse5.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node44);
			ifElse5.SetHasEvents(ifElse5.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node44.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | ifElse5.HasEvents());
			sequence13.SetHasEvents(sequence13.HasEvents() | selector3.HasEvents());
			Sequence sequence32 = new Sequence();
			sequence32.SetClassNameString("Sequence");
			sequence32.SetId(202);
			sequence13.AddChild(sequence32);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node85 action_bt_WrapperAI_Monster_BTMonsterRob_node45 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node85();
			action_bt_WrapperAI_Monster_BTMonsterRob_node45.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node45.SetId(85);
			sequence32.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node45);
			sequence32.SetHasEvents(sequence32.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node45.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node86 action_bt_WrapperAI_Monster_BTMonsterRob_node46 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node86();
			action_bt_WrapperAI_Monster_BTMonsterRob_node46.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node46.SetId(86);
			sequence32.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node46);
			sequence32.SetHasEvents(sequence32.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node46.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node87 decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node87();
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node.SetId(87);
			sequence32.AddChild(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node88 condition_bt_WrapperAI_Monster_BTMonsterRob_node45 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node88();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node45.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node45.SetId(88);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node45);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node45.HasEvents());
			sequence32.SetHasEvents(sequence32.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node.HasEvents());
			sequence13.SetHasEvents(sequence13.HasEvents() | sequence32.HasEvents());
			ifElse4.SetHasEvents(ifElse4.HasEvents() | sequence13.HasEvents());
			Sequence sequence33 = new Sequence();
			sequence33.SetClassNameString("Sequence");
			sequence33.SetId(208);
			ifElse4.AddChild(sequence33);
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node229 assignment_bt_WrapperAI_Monster_BTMonsterRob_node24 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node229();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node24.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node24.SetId(229);
			sequence33.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node24);
			sequence33.SetHasEvents(sequence33.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node24.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node224 action_bt_WrapperAI_Monster_BTMonsterRob_node47 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node224();
			action_bt_WrapperAI_Monster_BTMonsterRob_node47.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node47.SetId(224);
			sequence33.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node47);
			sequence33.SetHasEvents(sequence33.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node47.HasEvents());
			ifElse4.SetHasEvents(ifElse4.HasEvents() | sequence33.HasEvents());
			sequence10.SetHasEvents(sequence10.HasEvents() | ifElse4.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node63 action_bt_WrapperAI_Monster_BTMonsterRob_node48 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node63();
			action_bt_WrapperAI_Monster_BTMonsterRob_node48.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node48.SetId(63);
			sequence10.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node48);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node48.HasEvents());
			WaitFrames_bt_WrapperAI_Monster_BTMonsterRob_node17 waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node3 = new WaitFrames_bt_WrapperAI_Monster_BTMonsterRob_node17();
			waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node3.SetClassNameString("WaitFrames");
			waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node3.SetId(17);
			sequence10.AddChild(waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node3);
			sequence10.SetHasEvents(sequence10.HasEvents() | waitFrames_bt_WrapperAI_Monster_BTMonsterRob_node3.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence10.HasEvents());
			withPrecondition2.SetHasEvents(withPrecondition2.HasEvents() | selector2.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition2.HasEvents());
			WithPrecondition withPrecondition3 = new WithPrecondition();
			withPrecondition3.SetClassNameString("WithPrecondition");
			withPrecondition3.SetId(515);
			selectorLoop.AddChild(withPrecondition3);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node516 condition_bt_WrapperAI_Monster_BTMonsterRob_node46 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node516();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node46.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node46.SetId(516);
			withPrecondition3.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node46);
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node46.HasEvents());
			Selector selector12 = new Selector();
			selector12.SetClassNameString("Selector");
			selector12.SetId(132);
			withPrecondition3.AddChild(selector12);
			Sequence sequence34 = new Sequence();
			sequence34.SetClassNameString("Sequence");
			sequence34.SetId(135);
			selector12.AddChild(sequence34);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node136 condition_bt_WrapperAI_Monster_BTMonsterRob_node47 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node136();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node47.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node47.SetId(136);
			sequence34.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node47);
			sequence34.SetHasEvents(sequence34.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node47.HasEvents());
			Assignment_bt_WrapperAI_Monster_BTMonsterRob_node139 assignment_bt_WrapperAI_Monster_BTMonsterRob_node25 = new Assignment_bt_WrapperAI_Monster_BTMonsterRob_node139();
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node25.SetClassNameString("Assignment");
			assignment_bt_WrapperAI_Monster_BTMonsterRob_node25.SetId(139);
			sequence34.AddChild(assignment_bt_WrapperAI_Monster_BTMonsterRob_node25);
			sequence34.SetHasEvents(sequence34.HasEvents() | assignment_bt_WrapperAI_Monster_BTMonsterRob_node25.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node142 action_bt_WrapperAI_Monster_BTMonsterRob_node49 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node142();
			action_bt_WrapperAI_Monster_BTMonsterRob_node49.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node49.SetId(142);
			sequence34.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node49);
			sequence34.SetHasEvents(sequence34.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node49.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node143 action_bt_WrapperAI_Monster_BTMonsterRob_node50 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node143();
			action_bt_WrapperAI_Monster_BTMonsterRob_node50.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node50.SetId(143);
			sequence34.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node50);
			sequence34.SetHasEvents(sequence34.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node50.HasEvents());
			selector12.SetHasEvents(selector12.HasEvents() | sequence34.HasEvents());
			Sequence sequence35 = new Sequence();
			sequence35.SetClassNameString("Sequence");
			sequence35.SetId(517);
			selector12.AddChild(sequence35);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node144 condition_bt_WrapperAI_Monster_BTMonsterRob_node48 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node144();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node48.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node48.SetId(144);
			sequence35.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node48);
			sequence35.SetHasEvents(sequence35.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node48.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node518 action_bt_WrapperAI_Monster_BTMonsterRob_node51 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node518();
			action_bt_WrapperAI_Monster_BTMonsterRob_node51.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node51.SetId(518);
			sequence35.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node51);
			sequence35.SetHasEvents(sequence35.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node51.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node519 action_bt_WrapperAI_Monster_BTMonsterRob_node52 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node519();
			action_bt_WrapperAI_Monster_BTMonsterRob_node52.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node52.SetId(519);
			sequence35.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node52);
			sequence35.SetHasEvents(sequence35.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node52.HasEvents());
			IfElse ifElse6 = new IfElse();
			ifElse6.SetClassNameString("IfElse");
			ifElse6.SetId(520);
			sequence35.AddChild(ifElse6);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node521 condition_bt_WrapperAI_Monster_BTMonsterRob_node49 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node521();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node49.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node49.SetId(521);
			ifElse6.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node49);
			ifElse6.SetHasEvents(ifElse6.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node49.HasEvents());
			Sequence sequence36 = new Sequence();
			sequence36.SetClassNameString("Sequence");
			sequence36.SetId(522);
			ifElse6.AddChild(sequence36);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node523 action_bt_WrapperAI_Monster_BTMonsterRob_node53 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node523();
			action_bt_WrapperAI_Monster_BTMonsterRob_node53.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node53.SetId(523);
			sequence36.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node53);
			sequence36.SetHasEvents(sequence36.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node53.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node524 action_bt_WrapperAI_Monster_BTMonsterRob_node54 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node524();
			action_bt_WrapperAI_Monster_BTMonsterRob_node54.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node54.SetId(524);
			sequence36.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node54);
			sequence36.SetHasEvents(sequence36.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node54.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node526 action_bt_WrapperAI_Monster_BTMonsterRob_node55 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node526();
			action_bt_WrapperAI_Monster_BTMonsterRob_node55.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node55.SetId(526);
			sequence36.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node55);
			sequence36.SetHasEvents(sequence36.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node55.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node145 action_bt_WrapperAI_Monster_BTMonsterRob_node56 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node145();
			action_bt_WrapperAI_Monster_BTMonsterRob_node56.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node56.SetId(145);
			sequence36.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node56);
			sequence36.SetHasEvents(sequence36.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node56.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node530 action_bt_WrapperAI_Monster_BTMonsterRob_node57 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node530();
			action_bt_WrapperAI_Monster_BTMonsterRob_node57.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node57.SetId(530);
			sequence36.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node57);
			sequence36.SetHasEvents(sequence36.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node57.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node531 decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node2 = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node531();
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node2.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node2.SetId(531);
			sequence36.AddChild(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node2);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node532 condition_bt_WrapperAI_Monster_BTMonsterRob_node50 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node532();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node50.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node50.SetId(532);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node2.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node50);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node2.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node2.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node50.HasEvents());
			sequence36.SetHasEvents(sequence36.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node2.HasEvents());
			ifElse6.SetHasEvents(ifElse6.HasEvents() | sequence36.HasEvents());
			Sequence sequence37 = new Sequence();
			sequence37.SetClassNameString("Sequence");
			sequence37.SetId(533);
			ifElse6.AddChild(sequence37);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node146 action_bt_WrapperAI_Monster_BTMonsterRob_node58 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node146();
			action_bt_WrapperAI_Monster_BTMonsterRob_node58.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node58.SetId(146);
			sequence37.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node58);
			sequence37.SetHasEvents(sequence37.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node58.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node535 action_bt_WrapperAI_Monster_BTMonsterRob_node59 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node535();
			action_bt_WrapperAI_Monster_BTMonsterRob_node59.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node59.SetId(535);
			sequence37.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node59);
			sequence37.SetHasEvents(sequence37.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node59.HasEvents());
			DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node536 decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node3 = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node536();
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node3.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node3.SetId(536);
			sequence37.AddChild(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node3);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node537 condition_bt_WrapperAI_Monster_BTMonsterRob_node51 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node537();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node51.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node51.SetId(537);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node3.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node51);
			decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node3.SetHasEvents(decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node3.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node51.HasEvents());
			sequence37.SetHasEvents(sequence37.HasEvents() | decoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRob_node3.HasEvents());
			ifElse6.SetHasEvents(ifElse6.HasEvents() | sequence37.HasEvents());
			sequence35.SetHasEvents(sequence35.HasEvents() | ifElse6.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node538 action_bt_WrapperAI_Monster_BTMonsterRob_node60 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node538();
			action_bt_WrapperAI_Monster_BTMonsterRob_node60.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node60.SetId(538);
			sequence35.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node60);
			sequence35.SetHasEvents(sequence35.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node60.HasEvents());
			selector12.SetHasEvents(selector12.HasEvents() | sequence35.HasEvents());
			withPrecondition3.SetHasEvents(withPrecondition3.HasEvents() | selector12.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition3.HasEvents());
			WithPrecondition withPrecondition4 = new WithPrecondition();
			withPrecondition4.SetClassNameString("WithPrecondition");
			withPrecondition4.SetId(163);
			selectorLoop.AddChild(withPrecondition4);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node164 condition_bt_WrapperAI_Monster_BTMonsterRob_node52 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node164();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node52.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node52.SetId(164);
			withPrecondition4.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node52);
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node52.HasEvents());
			Sequence sequence38 = new Sequence();
			sequence38.SetClassNameString("Sequence");
			sequence38.SetId(165);
			withPrecondition4.AddChild(sequence38);
			Selector selector13 = new Selector();
			selector13.SetClassNameString("Selector");
			selector13.SetId(487);
			sequence38.AddChild(selector13);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node488 action_bt_WrapperAI_Monster_BTMonsterRob_node61 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node488();
			action_bt_WrapperAI_Monster_BTMonsterRob_node61.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node61.SetId(488);
			selector13.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node61);
			selector13.SetHasEvents(selector13.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node61.HasEvents());
			Action_bt_WrapperAI_Monster_BTMonsterRob_node166 action_bt_WrapperAI_Monster_BTMonsterRob_node62 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node166();
			action_bt_WrapperAI_Monster_BTMonsterRob_node62.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node62.SetId(166);
			selector13.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node62);
			selector13.SetHasEvents(selector13.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node62.HasEvents());
			sequence38.SetHasEvents(sequence38.HasEvents() | selector13.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node167 decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node3 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node167();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node3.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node3.SetId(167);
			sequence38.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node3);
			Noop noop3 = new Noop();
			noop3.SetClassNameString("Noop");
			noop3.SetId(168);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node3.AddChild(noop3);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node3.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node3.HasEvents() | noop3.HasEvents());
			sequence38.SetHasEvents(sequence38.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node3.HasEvents());
			withPrecondition4.SetHasEvents(withPrecondition4.HasEvents() | sequence38.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition4.HasEvents());
			WithPrecondition withPrecondition5 = new WithPrecondition();
			withPrecondition5.SetClassNameString("WithPrecondition");
			withPrecondition5.SetId(35);
			selectorLoop.AddChild(withPrecondition5);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node40 condition_bt_WrapperAI_Monster_BTMonsterRob_node53 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node40();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node53.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node53.SetId(40);
			withPrecondition5.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node53);
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node53.HasEvents());
			Sequence sequence39 = new Sequence();
			sequence39.SetClassNameString("Sequence");
			sequence39.SetId(41);
			withPrecondition5.AddChild(sequence39);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node42 action_bt_WrapperAI_Monster_BTMonsterRob_node63 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node42();
			action_bt_WrapperAI_Monster_BTMonsterRob_node63.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node63.SetId(42);
			sequence39.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node63);
			sequence39.SetHasEvents(sequence39.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node63.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node43 decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node4 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node43();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node4.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node4.SetId(43);
			sequence39.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node4);
			Noop noop4 = new Noop();
			noop4.SetClassNameString("Noop");
			noop4.SetId(458);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node4.AddChild(noop4);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node4.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node4.HasEvents() | noop4.HasEvents());
			sequence39.SetHasEvents(sequence39.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node4.HasEvents());
			withPrecondition5.SetHasEvents(withPrecondition5.HasEvents() | sequence39.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition5.HasEvents());
			WithPrecondition withPrecondition6 = new WithPrecondition();
			withPrecondition6.SetClassNameString("WithPrecondition");
			withPrecondition6.SetId(450);
			selectorLoop.AddChild(withPrecondition6);
			Condition_bt_WrapperAI_Monster_BTMonsterRob_node454 condition_bt_WrapperAI_Monster_BTMonsterRob_node54 = new Condition_bt_WrapperAI_Monster_BTMonsterRob_node454();
			condition_bt_WrapperAI_Monster_BTMonsterRob_node54.SetClassNameString("Condition");
			condition_bt_WrapperAI_Monster_BTMonsterRob_node54.SetId(454);
			withPrecondition6.AddChild(condition_bt_WrapperAI_Monster_BTMonsterRob_node54);
			withPrecondition6.SetHasEvents(withPrecondition6.HasEvents() | condition_bt_WrapperAI_Monster_BTMonsterRob_node54.HasEvents());
			Sequence sequence40 = new Sequence();
			sequence40.SetClassNameString("Sequence");
			sequence40.SetId(455);
			withPrecondition6.AddChild(sequence40);
			Action_bt_WrapperAI_Monster_BTMonsterRob_node456 action_bt_WrapperAI_Monster_BTMonsterRob_node64 = new Action_bt_WrapperAI_Monster_BTMonsterRob_node456();
			action_bt_WrapperAI_Monster_BTMonsterRob_node64.SetClassNameString("Action");
			action_bt_WrapperAI_Monster_BTMonsterRob_node64.SetId(456);
			sequence40.AddChild(action_bt_WrapperAI_Monster_BTMonsterRob_node64);
			sequence40.SetHasEvents(sequence40.HasEvents() | action_bt_WrapperAI_Monster_BTMonsterRob_node64.HasEvents());
			DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node457 decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node5 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node457();
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node5.SetClassNameString("DecoratorLoop");
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node5.SetId(457);
			sequence40.AddChild(decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node5);
			Noop noop5 = new Noop();
			noop5.SetClassNameString("Noop");
			noop5.SetId(147);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node5.AddChild(noop5);
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node5.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node5.HasEvents() | noop5.HasEvents());
			sequence40.SetHasEvents(sequence40.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node5.HasEvents());
			withPrecondition6.SetHasEvents(withPrecondition6.HasEvents() | sequence40.HasEvents());
			selectorLoop.SetHasEvents(selectorLoop.HasEvents() | withPrecondition6.HasEvents());
			decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node.SetHasEvents(decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node.HasEvents() | selectorLoop.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorLoop_bt_WrapperAI_Monster_BTMonsterRob_node.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | sequence.HasEvents());
			return true;
		}
	}
}
