using System;

namespace CSProtocol
{
	public enum CSSYNC_TYPE_DEF
	{
		CSSYNC_CMD_NULL,
		CSSYNC_CMD_USEOBJECTIVESKILL = 128,
		CSSYNC_CMD_USEDIRECTIONALSKILL,
		CSSYNC_CMD_USEPOSITIONSKILL,
		CSSYNC_CMD_MOVE,
		CSSYNC_CMD_BASEATTACK
	}
}
