using System;

public enum NewbieGuideTriggerConditionType
{
	completeNewbieDungeon = 1,
	completeNormalDungeon,
	completeNewbieGuide,
	unCompleteNewbieGuide,
	aHeroStarUpAvailable,
	aHeroStepUpAvailable,
	aTaskRewardAvailable,
	aHeroSummonAvailable,
	aHeroSkillUpgradeAvailable,
	aHeroEquipAvailable,
	hasHerosOfNumber,
	aHeroBuyable,
	aExpItemBuyable,
	shopUnlocked,
	chapterFullStar,
	levelFullStar,
	unlockPvP,
	hasMopupTicket,
	unlockTrial,
	unlockZhuangzi,
	unlockBurning,
	unlockElitePvE,
	unlockGuild,
	unlockSymbol,
	unlockMysteryShop,
	unlockHonorShop,
	unlockTask,
	aHeroEquipCanAdvance,
	completeHumanAi33Match = 30,
	completeHuman33Match,
	complete33Guide,
	hasCoin,
	hasEquipmentInc,
	aHeroLevelUpAvailable = 36,
	hasItemInBag,
	boughtHero,
	hasNumberOfHero,
	aRuneAvailable,
	unlockTournament,
	completeHumanAi33,
	hasEnoughSymbolDebris,
	unlockAddedSkill,
	battleAddedSkillAvailable,
	CompleteWeakGuide,
	UnCompleteWeakGuide,
	hasAtLeastTwoSymbolPage,
	hasTaskRewardLevel,
	hasSymbleFreeDraw,
	unlockPlayingMethod,
	oldPlayerUnguided,
	isMuiltGame,
	hasCompleteTrainLevel55,
	VictoryTipsEnable,
	HasRecord,
	isTheMapId,
	isUseChuanSong
}
