using System;

namespace Apollo
{
	public enum APO_PAY_CHANNEL
	{
		APO_PAYCHANEL_UNKOWN = -1,
		APO_PAYCHANEL_ACCT_QDQB,
		APO_PAYCHANEL_TENPAY_CFT,
		APO_PAYCHANEL_TENPAY_BANK,
		APO_PAYCHANEL_TENPAY_KJ,
		APO_PAYCHANEL_QQCARD,
		APO_PAYCHANEL_MCARD,
		APO_PAYCHANEL_YB = 7,
		APO_PAYCHANEL_WECHAT,
		APO_PAYCHANEL_HF,
		APO_PAYCHANEL_GOLDCOUPONS,
		APO_PAYCHANEL_ACCT_QBQD
	}
}
