using System;

namespace CSProtocol
{
	public enum COM_FIGHT_HISTORY_ACHIVE_BIT
	{
		FIGHT_HISTORY_ACHIVE_GODLIKE,
		FIGHT_HISTORY_ACHIVE_PENTAKILL,
		FIGHT_HISTORY_ACHIVE_QUATARYKILL,
		FIGHT_HISTORY_ACHIVE_TRIPLEKILL,
		FIGHT_HISTORY_ACHIVE_DOUBLEKILL,
		FIGHT_HISTORY_ACHIVE_KILLMOST,
		FIGHT_HISTORY_ACHIVE_HURTTOHEROMOST,
		FIGHT_HISTORY_ACHIVE_RECVDAMAGEMOST,
		FIGHT_HISTORY_ACHIVE_ASSISTMOST,
		FIGHT_HISTORY_ACHIVE_GETMOENYMOST,
		FIGHT_HISTORY_ACHIVE_KILLORGANMOST,
		FIGHT_HISTORY_ACHIVE_RUNAWAY,
		FIGHT_HISTORY_ACHIVE_FIGHTACHIVECOUNT,
		FIGHT_HISTORY_ACHIVE_FIGHTWITHFRIEND,
		FIGHT_HISTORY_ACHIVE_WINMVP,
		FIGHT_HISTORY_ACHIVE_LOSEMVP,
		FIGHT_HISTORY_ACHIVE_ISCOMPUTER,
		FIGHT_HISTORY_ACHIVE_ISWARMBATTLE,
		FIGHT_HISTORY_ACHIVE_LADDER5V5,
		FIGHT_HISTORY_ACHIVE_LADDER4,
		FIGHT_HISTORY_ACHIVE_LADDER3,
		FIGHT_HISTORY_ACHIVE_LADDER2,
		FIGHT_HISTORY_ACHIVE_COUNT
	}
}
