using System;

namespace CSProtocol
{
	public enum COM_REDDOTENTER_TYPE
	{
		COM_REDDOTENTER_SAISHI = 1,
		COM_REDDOTENTER_SHOP,
		COM_REDDOTENTER_HUODONG,
		COM_REDDOTENTER_SHOPTUIJIAN,
		COM_REDDOTENTER_SHOPXINPIN,
		COM_REDDOTENTER_SHOPHERO,
		COM_REDDOTENTER_SHOPSKIN,
		COM_REDDOTENTER_SHOPTEHUI
	}
}
