using System;

namespace CSProtocol
{
	public enum COM_GUILD_EVENT_TYPE
	{
		COM_GUILD_EVENT_TYPE_JOIN = 1,
		COM_GUILD_EVENT_TYPE_QUIT,
		COM_GUILD_EVENT_TYPE_BEKICK,
		COM_GUILD_EVENT_TYPE_PINGJI_UP,
		COM_GUILD_EVENT_TYPE_MEMBERNUM_UP,
		COM_GUILD_EVENT_TYPE_NEWMATCH_START,
		COM_GUILD_EVENT_TYPE_MEMBERUPTO_WANGZHE
	}
}
