using System;

namespace CSProtocol
{
	public enum COM_ACNT_NEWCLIENT_BITS_TYPE
	{
		COM_ACNT_NEWCLIENT_BITS_TYPE_NEWBITGIFT_SHOW,
		COM_ACNT_NEWCLIENT_BITS_TYPE_PROPITEM_ADD,
		COM_ACNT_NEWCLIENT_BITS_TYPE_GIFTITEM_ADD,
		COM_ACNT_NEWCLIENT_BITS_TYPE_SHOW_HERO_TRICK_TIPS,
		COM_ACNT_NEWCLIENT_BITS_TYPE_ShOW_LBS_GUIDE,
		COM_ACNT_NEWCLIENT_BITS_TYPE_Show_MoreHero_Guide,
		COM_ACNT_NEWCLIENT_BITS_TYPE_SHOW_ACTIVE_EQUIP_GUIDE,
		COM_ACNT_NEWCLIENT_BITS_TYPE_SHOW_GUILD_PLATFORM_GROUP_GUIDE,
		COM_ACNT_NEWCLIENT_BITS_TYPE_CLTUSE_START = 100,
		COM_ACNT_NEWCLIENT_BITS_TYPE_CLTUSE_END = 200,
		COM_ACNT_NEWCLIENT_BITS_TYPE_MAX
	}
}
