using System;

namespace CSProtocol
{
	public enum COM_INVITE_RELATION_TYPE
	{
		COM_INVITE_RELATION_FRIEND,
		COM_INVITE_RELATION_GUILDMEMBER,
		COM_INVITE_RELATION_LBS,
		COM_INVITE_RELATION_MAX
	}
}
