using System;

namespace CSProtocol
{
	public enum COM_COIN_LIMIT_MASK
	{
		COM_COIN_LIMIT_NULL,
		COM_COIN_LIMIT_CREDIT_ADD,
		COM_COIN_LIMIT_CREDIT_REDUCE,
		COM_COIN_LIMIT_ACTIVE_ADD = 4,
		COM_COIN_LIMIT_LADDER_ADD = 8
	}
}
