using System;

namespace CSProtocol
{
	public enum COM_MATCHTEAMERRORCODE_DEF
	{
		COM_MATCHTEAMEERR_LIMIT_PRIVILEGE = 1,
		COM_MATCHTEAMEERR_INVALIDPARAM,
		COM_MATCHTEAMEERR_NOTFOUND_FRIEND,
		COM_MATCHTEAMEERR_FRIEND_OFFLINE,
		COM_MATCHTEAMEERR_FRIEND_BUSY,
		COM_MATCHTEAMEERR_INVITE_DENY,
		COM_MATCHTEAMEERR_DESTROY,
		COM_MATCHTEAMEERR_BEGIN_MATCH,
		COM_MATCHTEAMEERR_MEMBER_FULL,
		COM_MATCHTEAMEERR_GAMEREADY_ERROR,
		COM_MATCHTEAMEERR_LEAVETEAM_FAILED,
		COM_MATCHTEAMEERR_LIMIT_RANK_FUNC,
		COM_MATCHTEAMEERR_BANTIME,
		COM_MATCHTEAMEERR_HIGHVERSION,
		COM_MATCHTEAMEERR_LOWVERSION,
		COM_MATCHTEAMEERR_LIMIT_ENTERTAINMENT_FUNC,
		COM_MATCHTEAMEERR_BEPUNISHED,
		COM_MATCHTEAMEERR_RANK_INVALID_GRADEDIFF,
		COM_MATCHTEAMEERR_RANK_INVALID_GUILDMEM,
		COM_MATCHTEAMEERR_TEAMERLEAVE,
		COM_MATCHTEAMEERR_INVALID_RANKSTATE_OF_REWARD,
		COM_MATCHTEAMEERR_INVALID_TIME,
		COM_MATCHTEAMEERR_INVALID_CREDIT_VALUE,
		COM_MATCHTEAMEERR_OTHERS,
		COM_MATCHTEAMEERR_DUPJOIN,
		COM_MATCHTEAMEERR_PLAT_CHANNEL_CLOSE,
		COM_MATCHTEAMEERR_OBING,
		COM_MATCHTEAMEERR_FORBID_LADDER,
		COM_MATCHTEAMEERR_BANLADDERTIME,
		COM_MATCHTEAMEERR_BANFIVEVSFIVETIME,
		COM_MATCHTEAMEERR_BANTHREEVSTHREETIME,
		COM_MATCHTEAMEERR_BANONEVSONETIME,
		COM_MATCHTEAMEERR_BANENTERMAINTTIME,
		COM_MATCHTEAMEERR_ANTI_DISTURB
	}
}
