using System;

namespace CSProtocol
{
	public enum COM_MAILACCESS_TYPE
	{
		COM_MAILACCESS_PROP = 1,
		COM_MAILACCESS_MONEY,
		COM_MAILACCESS_HEART,
		COM_MAILACCESS_RONGYU,
		COM_MAILACCESS_EXP,
		COM_MAILACCESS_HERO,
		COM_MAILACCESS_PIFU,
		COM_MAILACCESS_EXPHERO,
		COM_MAILACCESS_EXPSKIN,
		COM_MAILACCESS_HEADIMG,
		COM_MAILACCESS_MASTERPOINT
	}
}
