using System;

namespace CSProtocol
{
	public enum COM_INTIMACY_STATE
	{
		COM_INTIMACY_STATE_NULL,
		COM_INTIMACY_STATE_GAY,
		COM_INTIMACY_STATE_LOVER,
		COM_INTIMACY_STATE_SIDEKICK,
		COM_INTIMACY_STATE_BESTIE,
		COM_INTIMACY_STATE_MAX,
		COM_INTIMACY_STATE_GAY_CONFIRM = 20,
		COM_INTIMACY_STATE_GAY_DENY,
		COM_INTIMACY_STATE_LOVER_CONFIRM,
		COM_INTIMACY_STATE_LOVER_DENY,
		COM_INTIMACY_STATE_SIDEKICK_CONFIRM,
		COM_INTIMACY_STATE_SIDEKICK_DENY,
		COM_INTIMACY_STATE_BESTIE_CONFIRM,
		COM_INTIMACY_STATE_BESTIE_DENY,
		COM_INTIMACY_STATE_VALUE_FULL
	}
}
