using System;

namespace CSProtocol
{
	public enum COM_CHGFRIEND_EVENT_TYPE
	{
		COM_CHGFRIEND_EVENT_DEL = 1,
		COM_CHGFRIEND_EVENT_ADD,
		COM_CHGFRIEND_EVENT_ADDBYINTIMACY,
		COM_CHGFRIEND_EVENT_ADDBYRECRUIT,
		COM_CHGFRIEND_EVENT_DELBYASSIT,
		COM_CHGFRIEND_EVENT_DELBYBLACK,
		COM_CHGFRIEND_EVENT_ADDBYASSIT
	}
}
