using System;

namespace CSProtocol
{
	public enum COM_RANK_SUBSTATE_TYPE
	{
		COM_RANK_SUBSTATE_OF_NULL,
		COM_RANK_SUBSTATE_OF_NORMAL,
		COM_RANK_SUBSTATE_OF_GRADEUP,
		COM_RANK_SUBSTATE_OF_GRADEDOWN
	}
}
