using System;

namespace CSProtocol
{
	public enum COM_MATCH_ERR_ERRCODE
	{
		COM_MATCH_ERRCODE_BANTIME = 1,
		COM_MATCH_ERRCODE_NEEDITEM,
		COM_MATCH_ERRCODE_WRONGTIME,
		COM_MATCH_ERRCODE_BEPUNISHED,
		COM_MATCH_ERRCODE_ABORT,
		COM_MATCH_ERRCODE_OTHERS,
		COM_MATCH_ERRCODE_CREDIT,
		COM_MATCH_ERRCODE_INVALID_LADDERBP,
		COM_MATCH_ERRCODE_FORBID_LADDER,
		COM_MATCH_ERRCODE_BANLADDERTIME,
		COM_MATCH_ERRCODE_BANONEVSONE
	}
}
