using System;

namespace CSProtocol
{
	public enum CS_AKALISHOP_ERROR
	{
		CS_AKALISHOP_ERROR_SHOPNOTOPEN = 1,
		CS_AKALISHOP_ERROR_SHOPCLOSE,
		CS_AKALISHOP_ERROR_OVERTOTALLIMIT,
		CS_AKALISHOP_ERROR_GOODSNOTINSHOP,
		CS_AKALISHOP_ERROR_GOODSALREADYBUY,
		CS_AKALISHOP_ERROR_BUYFAIL,
		CS_AKALISHOP_ERROR_INVALID,
		CS_AKALISHOP_ERROR_COINLIMIT,
		CS_AKALISHOP_ERROR_STATEERR
	}
}
