using System;

namespace CSProtocol
{
	public enum CS_ACNT_ASKFORREQ_ERRCODE
	{
		CS_ACNT_ASKFORREQ_ERR_SYS = 1,
		CS_ACNT_ASKFORREQ_ERR_INDEX,
		CS_ACNT_ASKFORREQ_ERR_UNDEL,
		CS_ACNT_ASKFORREQ_ERR_VERSION,
		CS_ACNT_ASKFORREQ_ERR_NODATA,
		CS_ACNT_ASKFORREQ_ERR_STATE,
		CS_ACNT_ASKFORREQ_ERR_MSGDIRTY,
		CS_ACNT_ASKFORREQ_ERR_LOCK,
		CS_ACNT_ASKFORREQ_ERR_SELF,
		CS_ACNT_ASKFORREQ_ERR_MAXCNT,
		CS_ACNT_ASKFORREQ_ERR_PLAT,
		CS_ACNT_ASKFORREQ_ERR_ITEM,
		CS_ACNT_ASKFORREQ_ERR_NOFRIEND,
		CS_ACNT_ASKFORREQ_ERR_NOALLOW,
		CS_ACNT_ASKFORREQ_ERR_READWAIT,
		CS_ACNT_ASKFORREQ_ERR_MSGTYPE,
		CS_ACNT_ASKFORREQ_ERR_MSGID,
		CS_ACNT_ASKFORREQ_ERR_PSWDCHK,
		CS_ACNT_ASKFORREQ_ERR_OFFSHELF,
		CS_ACNT_ASKFORREQ_ERR_PAY,
		CS_ACNT_ASKFORREQ_ERR_COINLIMIT,
		CS_ACNT_ASKFORREQ_ERR_MAILFAIL,
		CS_ACNT_ASKFORREQ_ERR_NOOPEN,
		CS_ACNT_ASKFORREQ_ERR_FRIENDTIME,
		CS_ACNT_ASKFORREQ_ERR_ITEMHAVE,
		CS_ACNT_ASKFORREQ_ERR_ITEMHAVE_SELF
	}
}
