using System;

namespace CSProtocol
{
	public enum CS_ACTIVITY_ERRCODE
	{
		CS_ACTIVITY_SUCC,
		CS_ACTIVITY_LOCK,
		CS_ACTIVITY_NOAP,
		CS_ACTIVITY_FULLTIMES,
		CS_ACTIVITY_CDLIMIT,
		CS_ACTIVITY_ACNTLVLLIMIT,
		CS_ACTIVITY_NOTFIND,
		CS_ACTIVITY_MEMNOTFIND,
		CS_ACTIVITY_OTHER
	}
}
