using System;

namespace CSProtocol
{
	public enum CS_ADDHEROSKIN_ERRCODE
	{
		CS_ADDHEROSKIN_SKININVALID = 1,
		CS_ADDHEROSKIN_PROMOTION,
		CS_ADDHEROSKIN_BUYFAIL,
		CS_ADDHEROSKIN_NOHERO,
		CS_ADDHEROSKIN_SKINHAS,
		CS_ADDHEROSKIN_COINLIMIT,
		CS_ADDHEROSKIN_COUPONS,
		CS_ADDHEROSKIN_OTHER,
		CS_ADDHEROSKIN_RANKGRADE
	}
}
