using System;

namespace CSProtocol
{
	public enum CS_COUPONS_PAYTYPE
	{
		CS_COUPONS_PAYTYPE_NULL,
		CS_COUPONS_PAYTYPE_FIRST,
		CS_COUPONS_PAYTYPE_RENEW,
		CS_COUPONS_PAYTYPE_UPDATE,
		CS_COUPONS_PAYTYPE_LOGIN,
		CS_COUPONS_PAYTYPE_PAY,
		CS_COUPONS_PAYTYPE_QUERY
	}
}
