using System;

namespace CSProtocol
{
	public enum CS_ITEMOPT_TYPE
	{
		CS_ITEMOPT_GM = 1,
		CS_ITEMOPT_BUY,
		CS_ITEMOPT_SALE,
		CS_ITEMOPT_USE,
		CS_ITEMOPT_COMP,
		CS_ITEMOPT_TASK,
		CS_ITEMOPT_WEAR,
		CS_ITEMOPT_UPGRADESTAR,
		CS_ITEMOPT_REWARD,
		CS_ITEMOPT_EQUIPSMELT,
		CS_ITEMOPT_MAILGETACCESS,
		CS_ITEMOPT_HEROADV,
		CS_ITEMOPT_GEARADV,
		CS_ITEMOPT_GUILDSYMBOL,
		CS_ITEMOPT_MAKE,
		CS_ITEMOPT_BREAK,
		CS_ITEMOPT_HEROWAKE,
		CS_ITEMOPT_ACHIEVEMENT,
		CS_ITEMOPT_CHGNAME,
		CS_ITEMOPT_EXCHANGE,
		CS_ITEMOPT_HUOYUEDUREWARD,
		CS_ITEMOPT_WEAL,
		CS_ITEMOPT_IDIP,
		CS_ITEMOPT_LEVELREWARD,
		CS_ITEMOPT_RECRUITMENTREWARD
	}
}
