using System;

namespace CSProtocol
{
	public enum CS_LUCKYDRAW_ERRCODE
	{
		CS_LUCKYDRAW_LACKMONEY = 1,
		CS_LUCKYDRAW_MONEYTYPE,
		CS_LUCKYDRAW_DRAWCNT,
		CS_LUCKYDRAW_APOLLO,
		CS_LUCKYDRAW_COMSUME,
		CS_LUCKYDRAW_PAYTIMEOUT,
		CS_LUCKYDRAW_REWARDLIMIT,
		CS_LUCKYDRAW_OTHER
	}
}
