using System;

namespace CSProtocol
{
	public enum CS_PVP_NTF_CLIENT_TYPE
	{
		CS_PVP_NTF_CLIENT_TYPE_REPORT_GAMEDATA = 1,
		CS_PVP_NTF_CLIENT_TYPE_REPORT_GAMELOG,
		CS_PVP_NTF_CLIENT_TYPE_RESTART_GAME
	}
}
