using System;

namespace CSProtocol
{
	public enum CS_ROOMERRORCODE_DEF
	{
		CS_ROOMERR_RELAYSVR_LIMIT = 1,
		CS_ROOMERR_GAMEABORT,
		CS_ROOMERR_TIMEOUT,
		CS_ROOMERR_ACNTLEAVE,
		CS_ROOMERR_ROOM_NOT_FOUND,
		CS_ROOMERR_ROOM_ALREADY_START,
		CS_ROOMERR_ROOM_MEMBERFULL,
		CS_ROOMERR_ROOM_OTHERS,
		CS_ROOMERR_ROOM_LIMIT_PRIVILEGE,
		CS_ROOMERR_ROOM_INVALIDPARAM,
		CS_ROOMERR_ROOM_NOTFOUND_FRIEND,
		CS_ROOMERR_ROOM_FRIEND_OFFLINE,
		CS_ROOMERR_ROOM_FRIEND_BUSY,
		CS_ROOMERR_ROOM_INVITE_DENY,
		CS_ROOMERR_ROOM_UNCONFIRM,
		CS_ROOMERR_ROOM_TEAMERUNCONFIRM,
		CS_ROOMERR_ROOM_TEAMERLEAVE,
		CS_ROOMERR_ROOM_OTHERSUNCONFIRM,
		CS_ROOMERR_ROOM_OTHERSLEAVE,
		CS_ROOMERR_ROOM_BANTIME,
		CS_ROOMERR_ROOM_VERSION_LIMIT,
		CS_ROOMERR_ROOM_HIGHVERSION,
		CS_ROOMERR_ROOM_LOWVERSION,
		CS_ROOMERR_ROOM_LIMIT_ENTERTAINMENT_FUNC,
		CS_ROOMERR_ROOM_LIMIT_REWARDMATCH_FUNC,
		CS_ROOMERR_ROOM_INBANTIME,
		CS_ROOMERR_ROOM_LIMIT_FUNC,
		CS_ROOMERR_ROOM_BAN_PICK_LIMIT,
		CS_ROOMERR_PLAT_CHANNEL_CLOSE,
		CS_ROOMERR_ROOM_BAN_PICK_HERO_LIMIT,
		CS_ROOMERR_ROOM_ANTI_DISTURB
	}
}
