using System;

namespace CSProtocol
{
	public enum CS_USER_SHARE_SUBTYPE
	{
		CS_USER_SHARE_SUBTYPE_XUANYAOYIXIA,
		CS_USER_SHARE_SUBTYPE_BAOCUNDAOSHOUJI,
		CS_USER_SHARE_SUBTYPE_FENXIANGHAOYOU_QQ,
		CS_USER_SHARE_SUBTYPE_FENXIANGHAOYOU_WX,
		CS_USER_SHARE_SUBTYPE_FENXIANG_QQKONGJIAN,
		CS_USER_SHARE_SUBTYPE_FENXIANG_WXPENGYOUQUAN
	}
}
