using System;

namespace CSProtocol
{
	public enum CS_WEALDRAW_ERRCODE
	{
		CS_WEALDRAW_ERR_INVALIDTIME = 1,
		CS_WEALDRAW_ERR_INVALIDPERIODTIME,
		CS_WEALDRAW_ERR_INCOMPLETE,
		CS_WEALDRAW_ERR_DRAWED,
		CS_WEALDRAW_ERR_NORES,
		CS_WEALDRAW_ERR_FILLINPRICE,
		CS_WEALDRAW_ERR_LACKCOUPONS,
		CS_WEALDRAW_ERR_PAY,
		CS_WEALDRAW_ERR_PAYTIMEOUT,
		CS_WEALDRAW_ERR_NOWWEALCON,
		CS_WEALDRAW_ERR_PERIOD,
		CS_WEALDRAW_ERR_NOREWARDDATA,
		CS_WEALDRAW_ERR_REWARDACNT,
		CS_WEALDRAW_ERR_OTHERS,
		CS_WEALDRAW_ERR_LACKITEM,
		CS_WEALDRAW_ERR_RECORDFULL,
		CS_WEALDRAW_ERR_LACKPOINT,
		CS_WEALDRAW_ERR_DRAWCNT
	}
}
