using System;

namespace CSProtocol
{
	public enum MAIL_OPT_MAILLISTTYPE
	{
		MAIL_OPT_MAILLISTREFRESH = 1,
		MAIL_OPT_SYSMAILLISTREFRESH,
		MAIL_OPT_FRIENDMAILLISTREFRESH,
		MAIL_OPT_MAILLISTSYS,
		MAIL_OPT_MAILLISTFRIEND
	}
}
