using System;

namespace ResData
{
	public enum RES_HEADIMG_SOURCE_TYPE
	{
		RES_HEADIMG_SOURCE_INIT,
		RES_HEADIMG_SOURCE_NOBE,
		RES_HEADIMG_SOURCE_ACTIVITY,
		RES_HEADIMG_SOURCE_SKIN,
		RES_HEADIMG_SOURCE_BATTLE,
		RES_HEADIMG_SOURCE_SYSTEM,
		RES_HEADIMG_SOURCE_MATCH,
		RES_HEADIMG_SOURCE_MAX
	}
}
