using System;

namespace ResData
{
	public enum RES_BANNER_IMAGE_TYPE
	{
		RES_BANNER_TYPE_NONE,
		RES_BANNER_TYPE_INNTER_BROWSER,
		RES_BANNER_TYPE_IN_GAME,
		RES_BANNER_TYPE_WECHAT_DEEP_LINK,
		RES_BANNER_TYPE_LOADING,
		RES_BANNER_TYPE_OUTER_BROWSER,
		RES_BANNER_TYPE_CHECKIN,
		RES_BANNER_TYPE_QQ_BOX,
		RES_BANNER_TYPE_PandoraOpen,
		BANNER_TYPE_BlockWaifaChannel,
		BANNER_TYPE_CDNUrl,
		RES_BANNER_TYPE_14CHECKIN,
		RES_BANNER_TYPE_WeixinZone,
		BANNER_TYPE_GSDK
	}
}
