using System;

namespace ResData
{
	public enum RES_POINT_GETTYPE
	{
		RES_POINT_GET_COUPONSBUY = 1,
		RES_POINT_GET_COUPONSCOST,
		RES_POINT_GET_DIAMONDCOST,
		RES_POINT_GET_COINCOST,
		RES_POINT_GET_MAX
	}
}
