using System;

namespace ResData
{
	public enum RES_CALL_MONSTER_ADD_TYPE
	{
		RES_CALL_MONSTER_ADD_ATTACK = 1,
		RES_CALL_MONSTER_ADD_MAGIC,
		RES_CALL_MONSTER_ADD_ATTACK_AND_MAGIC,
		RES_CALL_MONSTER_ADD_SEPERATELY
	}
}
