using System;

namespace ResData
{
	public enum RES_WEAL_CON_TYPE
	{
		RES_WEAL_CON_TYPE_NULL,
		RES_WEAL_CON_TYPE_ACNT_LVL,
		RES_WEAL_CON_TYPE_PVP_LVL,
		RES_WEAL_CON_TYPE_PVE_CNT,
		RES_WEAL_CON_TYPE_PVP_CNT,
		RES_WEAL_CON_TYPE_PVP_KILL,
		RES_WEAL_CON_TYPE_SUPPLY_ONCE,
		RES_WEAL_CON_TYPE_SUPPLY_ALL,
		RES_WEAL_CON_TYPE_EXPEND_ALL,
		RES_WEAL_CON_TYPE_OWN_STH,
		RES_WEAL_CON_TYPE_GAMEVIP_LVL,
		RES_WEAL_CON_TYPE_LADDER_GRADE,
		RES_WEAL_CON_TYPE_TEAMMATCH_FRIENDNUM,
		RES_WEAL_CON_TYPE_TEAMMATCH_GAMENUM,
		RES_WEAL_CON_TYPE_SHARECONTENT,
		RES_WEAL_CON_TYPE_GAME_TIME,
		RES_WEAL_CON_TYPE_PRESENT_STH,
		RES_WEAL_CON_TYPE_MAX
	}
}
