using System;

namespace ResData
{
	public enum RES_INCOME_MEMBER_CHOOSE_TYPE
	{
		RES_INCOME_MEMBER_CAMP = 1,
		RES_INCOME_MEMBER_RANGE,
		RES_INCOME_MEMBER_LAST_KILL,
		RES_INCOME_MEMBER_ASSIST,
		RES_INCOME_MEMBER_ALL_KILL
	}
}
