using System;

namespace ResData
{
	public enum RES_LICENSE_ID
	{
		RES_LICENSE_NONE,
		RES_LICENSE_DALUANDOU,
		RES_LICENSE_PVPRANK,
		RES_LICENSE_SYMBOL,
		RES_LICENSE_LIUGUOYUANZHENG,
		RES_LICENSE_WUDAOHUI,
		RES_LICENSE_SUMMONERSKILL,
		RES_LICENSE_TEAMLEADER,
		RES_LICENSE_MAX
	}
}
