using System;

namespace ResData
{
	public enum RES_TASKOPEN_TYPE
	{
		RES_TASKOPEN_BORN = 1,
		RES_TASKOPEN_ACNTLVL,
		RES_TASKOPEN_INITHERO = 4,
		RES_TASKOPEN_FPVESTAGECLEAR = 8,
		RES_TASKOPEN_HEROWAKE = 16,
		RES_TASKOPEN_TUDI = 32,
		RES_TASKOPEN_SHIFU = 64
	}
}
