using System;

namespace ResData
{
	public enum RES_HONOR_TYPE
	{
		RES_HONOR_TYPE_NULL,
		RES_HONOR_TYPE_MVP,
		RES_HONOR_TYPE_MAXDAMAGETOHERO,
		RES_HONOR_TYPE_MAXKILL,
		RES_HONOR_TYPE_MAXMONEY,
		RES_HONOR_TYPE_MAXASSIS,
		RES_HONOR_TYPE_MAXRECVDAMAGE,
		RES_HONOR_TYPE_MAX
	}
}
