using System;

namespace ResData
{
	public enum RES_FUNCTION_SWITCH_TYPE
	{
		RES_FUNCTION_SWITCH_NEWBIE,
		RES_FUNCTION_SWITCH_HALL,
		RES_FUNCTION_SWITCH_FRIEND,
		RES_FUNCTION_SWITCH_SOCIAL,
		RES_FUNCTION_SWITCH_ACTIVITY,
		RES_FUNCTION_SWITCH_STORY,
		RES_FUNCTION_SWITCH_VIP,
		RES_FUNCTION_SWITCH_TODO,
		RES_FUNCTION_SWITCH_GAMEVIP,
		RES_FUNCTION_SWITCH_PRIVILEGELOGIN,
		RES_FUNCTION_SWITCH_CHATPAY,
		RES_FUNCTION_SWITCH_JIFENQIANG,
		RES_FUNCTION_SWITCH_RECALLFRIEND,
		RES_FUNCTION_SWITCH_MAX
	}
}
