using System;

namespace ResData
{
	public enum RES_INCOME_KILL_TYPE
	{
		RES_INCOME_KILL_ORGAN = 1,
		RES_INCOME_KILL_SOLDIER,
		RES_INCOME_KILL_HERO,
		RES_INCOME_KILL_MONSTER,
		RES_INCOME_KILL_BOSS,
		RES_INCOME_KILL_EYE,
		RES_INCOME_KILL_RUNAWAYCAT,
		RES_INCOME_KILL_MAX
	}
}
