using System;

namespace ResData
{
	public enum RES_COMPLAINT_TYPE
	{
		RES_COMPLAINT_GUAJI = 1,
		RES_COMPLAINT_SONG,
		RES_COMPLAINT_XIAOJI,
		RES_COMPLAINT_MAREN,
		RES_COMPLAINT_YANYUAN,
		RES_COMPLAINT_GUA
	}
}
