using System;

namespace ResData
{
	public enum RES_RANK_LIMIT_TYPE
	{
		RES_RANK_LIMIT_NULL,
		RES_RANK_LIMIT_CURGRADE,
		RES_RANK_LIMIT_SEASONGRADE,
		RES_RANK_LIMIT_MAXGRADE,
		RES_RANK_LIMIT_HISTORYGRADE,
		RES_RANK_LIMIT_MAX
	}
}
