using System;

namespace ResData
{
	public enum RES_SKILLFUNC_OVERLAY_RULE
	{
		RES_SKILLFUNC_OVERLAY_FORBID = 1,
		RES_SKILLFUNC_OVERLAY_CLEAR,
		RES_SKILLFUNC_OVERLAY_REPLACE,
		RES_SKILLFUNC_OVERLAY_UPDATE
	}
}
