using System;

namespace ResData
{
	public enum RES_REWARDS_TYPE
	{
		RES_REWARDS_TYPE_NULL,
		RES_REWARDS_TYPE_ITEM = 2,
		RES_REWARDS_TYPE_EXP,
		RES_REWARDS_TYPE_COUPONS,
		RES_REWARDS_TYPE_EQUIP,
		RES_REWARDS_TYPE_SYMBOL,
		RES_REWARDS_TYPE_BURNINGCOIN,
		RES_REWARDS_TYPE_ARENACOIN,
		RES_REWARDS_TYPE_HONOUR,
		RES_REWARDS_TYPE_SKINCOIN,
		RES_REWARDS_TYPE_HEROPOOLEXP,
		RES_REWARDS_TYPE_AP,
		RES_REWARDS_TYPE_SKIN,
		RES_REWARDS_TYPE_SYMBOLCOIN,
		RES_REWARDS_TYPE_PVPEXP,
		RES_REWARDS_TYPE_DIAMOND,
		RES_REWARDS_TYPE_HUOYUEDU,
		RES_REWARDS_TYPE_MATCHPOINT_PERSON,
		RES_REWARDS_TYPE_MATCHPOINT_GUILD,
		RES_REWARDS_TYPE_HEADIMAGE,
		RES_REWARDS_TYPE_ACHIEVE,
		RES_REWARDS_TYPE_HERO,
		RES_REWARDS_TYPE_MINGSHIPOINT,
		RES_REWARDS_TYPE_MAX
	}
}
