using System;

namespace ResData
{
	public enum RES_WARM_BATTLE_STAGE
	{
		RES_WARM_BATTLE_STAGE_OF_LOW = 1,
		RES_WARM_BATTLE_STAGE_OF_MID,
		RES_WARM_BATTLE_STAGE_OF_HIGH,
		RES_WARM_BATTLE_STAGE_OF_QINGTONG,
		RES_WARM_BATTLE_STAGE_OF_BAIYIN,
		RES_WARM_BATTLE_STAGE_OF_HUANGJIN,
		RES_WARM_BATTLE_STAGE_OF_BOJING,
		RES_WARM_BATTLE_STAGE_OF_ZUANSHI,
		RES_WARM_BATTLE_STAGE_OF_WANGZHE,
		RES_WARM_BATTLE_STAGE_NUM
	}
}
