using System;

namespace ResData
{
	public enum RES_RANDOM_REWARD_TYPE
	{
		RES_RANDOM_REWARD_TYPE_NULL,
		RES_RANDOM_REWARD_TYPE_ITEM,
		RES_RANDOM_REWARD_TYPE_EQUIP,
		RES_RANDOM_REWARD_TYPE_NEST,
		RES_RANDOM_REWARD_TYPE_HERO,
		RES_RANDOM_REWARD_TYPE_SYMBOL,
		RES_RANDOM_REWARD_TYPE_AP,
		RES_RANDOM_REWARD_TYPE_COIN,
		RES_RANDOM_REWARD_TYPE_COUPONS,
		RES_RANDOM_REWARD_TYPE_BURNINGCOIN,
		RES_RANDOM_REWARD_TYPE_ARENACOIN,
		RES_RANDOM_REWARD_TYPE_SKIN,
		RES_RANDOM_REWARD_TYPE_SKINCOIN,
		RES_RANDOM_REWARD_TYPE_HEROPOOLEXP,
		RES_RANDOM_REWARD_TYPE_SYMBOLCOIN,
		RES_RANDOM_REWARD_TYPE_DIAMOND,
		RES_RANDOM_REWARD_TYPE_HEADIMG,
		RES_RANDOM_REWARD_TYPE_ACHIEVE,
		RES_RANDOM_REWARD_TYPE_MAX
	}
}
