using System;

namespace ResData
{
	public enum RES_LEVEL_TYPE
	{
		RES_LEVEL_TYPE_PVP,
		RES_LEVEL_TYPE_STORY,
		RES_LEVEL_TYPE_SURVIVAL,
		RES_LEVEL_TYPE_BOSS,
		RES_LEVEL_TYPE_GUIDE,
		RES_LEVEL_TYPE_DEFEND,
		RES_LEVEL_TYPE_ACTIVITY
	}
}
