using System;

namespace ResData
{
	public enum RES_SPECIAL_TIP_POS
	{
		RES_SPECIAL_TIP_POS_UP,
		RES_SPECIAL_TIP_POS_DOWN,
		RES_SPECIAL_TIP_POS_LEFT,
		RES_SPECIAL_TIP_POS_RIGHT,
		RES_SPECIAL_TIP_POS_UPLEFT,
		RES_SPECIAL_TIP_POS_UPRIGHT,
		RES_SPECIAL_TIP_POS_DOWNLEFT,
		RES_SPECIAL_TIP_POS_DOWNRIGHT,
		RES_SPECIAL_TIP_POS_MAX
	}
}
