using System;

namespace ResData
{
	public enum RES_ITEM_TYPE
	{
		RES_ITEMTYPE_PROP = 2,
		RES_ITEMTYPE_EQUIP,
		RES_ITEMTYPE_HERO,
		RES_ITEMTYPE_SYMBOL,
		RES_ITEMTYPE_GEAR,
		RES_ITEMTYPE_HEROSKIN,
		RES_ITEMTYPE_HEADIMG
	}
}
