using System;

namespace ResData
{
	public enum RES_MULTI_GAME_EXP_TYPE
	{
		RES_MULTI_EXP_NULL,
		RES_MULTI_EXP_WIN,
		RES_MULTI_EXP_LOSE,
		RES_MULTI_EXP_DRAW,
		RES_MULTI_EXP_BALANCE_MODE,
		RES_MULTI_EXP_ENTER_MODE,
		RES_MULTI_EXP_MATCH,
		RES_MULTI_EXP_NORMAL,
		RES_MULTI_EXP_PVP,
		RES_MULTI_EXP_MAX
	}
}
