using System;

namespace ResData
{
	public enum RES_COMPARE_OPERATOR_TYPE
	{
		RES_COMPARE_OPERATOR_TYPE_NULL,
		RES_COMPARE_OPERATOR_TYPE_LESS,
		RES_COMPARE_OPERATOR_TYPE_LESS_EQUAL,
		RES_COMPARE_OPERATOR_TYPE_EQUAL,
		RES_COMPARE_OPERATOR_TYPE_BIGGER,
		RES_COMPARE_OPERATOR_TYPE_BIGGER_EQUAL,
		RES_COMPARE_OPERATOR_TYPE_MAX
	}
}
