using System;

namespace ResData
{
	public enum RES_ORGAN_TYPE
	{
		RES_ORGAN_TYPE_DEFENSE = 1,
		RES_ORGAN_TYPE_BASE,
		RES_ORGAN_TYPE_BARRACKS,
		RES_ORGAN_TYPE_HighTower,
		RES_ORGAN_TYPE_TRIGGER = 11,
		RES_ORGAN_TYPE_SPRING,
		RES_ORGAN_TYPE_SPRINGTOWER
	}
}
