using System;

namespace ResData
{
	public enum RES_HERO_JOB_FEATURE
	{
		RES_JOB_FEATURE_DASH = 1,
		RES_JOB_FEATURE_CONTROL,
		RES_JOB_FEATURE_ACTIVE,
		RES_JOB_FEATURE_SLAVE,
		RES_JOB_FEATURE_RECOVER,
		RES_JOB_FEATURE_HPSTEAL,
		RES_JOB_FEATURE_POKE,
		RES_JOB_FEATURE_BUFF
	}
}
