using System;

namespace ResData
{
	public enum ResSkillCombineEffectType
	{
		SKILL_COMBINE_TYPE_POSITIVE,
		SKILL_COMBINE_TYPE_NEGATIVE,
		SKILL_COMBINE_TYPE_CONTROL,
		SKILL_COMBINE_TYPE_PERSIST
	}
}
